const cheIntPortfolioSchemas = {
  baseTemplate: {
    EN: [
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    IT: [
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    DE: [
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    FR: [
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
      ],
    ],
  },
  marketingTemplate: {
    EN: [
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Legacy CH Number",
        "Business identification number",
        "Company Book Number",
        "Office type",
        "Last update date",
        "Legal form group",
        "Legal form",
        "Company status",
        "CRIF Id",
        "Incorporation date",
        "End date",
        "Purpose",
        "Purpose - language",
        "Number of Local Units",
        "Province",
        "Canton",
        "Municipality",
        "Town",
        "Post code",
        "Street",
        "Housenumber",
        "Address-additional info",
        "Official Language of SOGC",
        "Phone number",
        "Email",
        "Website URL",
        "Fax number",
        "Mobile number",
        "Manager title (1)",
        "Manager surname (1)",
        "Manager first name / Company name (1)",
        "Manager Year of Birth (1)",
        "Manager origin (1)",
        "Manager function (1)",
        "Manager function - authority to sign (1)",
        "Manager - operative function (1)",
        "Manager title (2)",
        "Manager surname (2)",
        "Manager first name / Company name (2)",
        "Manager Year of Birth (2)",
        "Manager origin (2)",
        "Manager function (2)",
        "Manager function - authority to sign (2)",
        "Manager - operative function (2)",
        "Manager title (3)",
        "Manager surname (3)",
        "Manager first name / Company name (3)",
        "Manager Year of Birth (3)",
        "Manager origin (3)",
        "Manager function (3)",
        "Manager function - authority to sign (3)",
        "Manager - operative function (3)",
        "Manager title (4)",
        "Manager surname (4)",
        "Manager first name / Company name (4)",
        "Manager Year of Birth (4)",
        "Manager origin (4)",
        "Manager function (4)",
        "Manager function - authority to sign (4)",
        "Manager - operative function (4)",
        "Manager title (5)",
        "Manager surname (5)",
        "Manager first name / Company name (5)",
        "Manager Year of Birth (5)",
        "Manager origin (5)",
        "Manager function (5)",
        "Manager function - authority to sign (5)",
        "Manager - operative function (5)",
        "Auditing company - Company belongs to a Company group",
        "Auditing company name",
        "Auditing company - Country",
        "Auditing company - Canton",
        "Auditing company - Municipality",
        "Auditing company - City",
      ],
    ],
    IT: [
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Ragione Sociale",
        "Vat code",
        "CH Key",
        "Identificativo Azienda",
        "Company Book Number",
        "Tipo di sede",
        "Data ultimo aggiornamento",
        "Forma legale",
        "Forma legale dettagliata",
        "Stato impresa",
        "CRIF Id",
        "Data di costituzione",
        "Data cessazione",
        "Descrizione attività",
        "Descrizione attività - Lingua",
        "Numero unità locali",
        "Province",
        "Cantone",
        "Città metropolitana",
        "Città",
        "Cap",
        "Indirizzo",
        "Civico",
        "Indirizzo - Ulteriori informazioni",
        "Lingua del messaggio SOGC",
        "Numero di telefono",
        "Email",
        "Sito web",
        "Fax number",
        "Mobile number",
        "Titolo esponente (1)",
        "Nome esponente (1)",
        "Cognome / Denominazione esponente (1)",
        "Anno di nascita (1)",
        "Nazionalità esponente (1)",
        "Carica esponente (1)",
        "Autorizzazione a firmare esponente (1)",
        "Funzione operativa esponente (1)",
        "Titolo esponente (2)",
        "Nome esponente (2)",
        "Cognome / Denominazione esponente (2)",
        "Anno di nascita (2)",
        "Nazionalità esponente (2)",
        "Carica esponente (2)",
        "Autorizzazione a firmare esponente (2)",
        "Funzione operativa esponente (2)",
        "Titolo esponente (3)",
        "Nome esponente (3)",
        "Cognome / Denominazione esponente (3)",
        "Anno di nascita (3)",
        "Nazionalità esponente (3)",
        "Carica esponente (3)",
        "Autorizzazione a firmare esponente (3)",
        "Funzione operativa esponente (3)",
        "Titolo esponente (4)",
        "Nome esponente (4)",
        "Cognome / Denominazione esponente (4)",
        "Anno di nascita (4)",
        "Nazionalità esponente (4)",
        "Carica esponente (4)",
        "Autorizzazione a firmare esponente (4)",
        "Funzione operativa esponente (4)",
        "Titolo esponente (5)",
        "Nome esponente (5)",
        "Cognome / Denominazione esponente (5)",
        "Anno di nascita (5)",
        "Nazionalità esponente (5)",
        "Carica esponente (5)",
        "Autorizzazione a firmare esponente (5)",
        "Funzione operativa esponente (5)",
        "Appartenenza ad un gruppo",
        "Società di revisione",
        "Società di revisione - Stato",
        "Società di revisione - Cantone",
        "Società di revisione - Città metropolitana",
        "Società di revisione - Città",
      ],
    ],
    DE: [
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Firmenname",
        "UID-Nummer / MWST-Nr.",
        "CH Key",
        "Unternehmens-Identifikationsnummer",
        "Firmenbuchnummer",
        "Hauptsitz/Zweigniederlassung",
        "Datum des letzten Updates",
        "Rechtsform",
        "Rechtsstatus",
        "Firmenstatus",
        "CRIF Id",
        "Beginn Geschäftstätigkeit",
        "Löschdatum",
        "HR-Zweck",
        "HR-Zweck Sprache",
        "Anzahl der Filialen",
        "Province",
        "Kanton",
        "Gemeinde",
        "Ort",
        "PLZ",
        "Strasse",
        "Hausnummer",
        "Adresse-Zusatzinfo",
        "SHAB-Meldungssprache",
        "Telefonnummer",
        "Email",
        "Website URL",
        "Faxnummer",
        "Handynummer",
        "Manager Title (1)",
        "Manager Nachname (1)",
        "Manager Vorname(n) / Firmenname",
        "Manager Year of Birth (1)",
        "Manager Heimatort (1)",
        "Manager Funktion (1)",
        "Manager Unterschriftsberechtigung (1)",
        "Manager – Operative Funktion (1)",
        "Manager Title (2)",
        "Manager Nachname (2)",
        "Manager Vorname(2) / Firmenname",
        "Manager Year of Birth (2)",
        "Manager Heimatort (2)",
        "Manager Funktion (2)",
        "Manager Unterschriftsberechtigung (2)",
        "Manager – Operative Funktion (2)",
        "Manager Title (3)",
        "Manager Nachname (3)",
        "Manager Vorname(3) / Firmenname",
        "Manager Year of Birth (3)",
        "Manager Heimatort (3)",
        "Manager Funktion (3)",
        "Manager Unterschriftsberechtigung (3)",
        "Manager – Operative Funktion (3)",
        "Manager Title (4)",
        "Manager Nachname (4)",
        "Manager Vorname(4) / Firmenname",
        "Manager Year of Birth (4)",
        "Manager Heimatort (4)",
        "Manager Funktion (4)",
        "Manager Unterschriftsberechtigung (4)",
        "Manager – Operative Funktion (4)",
        "Manager Title (5)",
        "Manager Nachname (5)",
        "Manager Vorname(5) / Firmenname",
        "Manager Year of Birth (5)",
        "Manager Heimatort (5)",
        "Manager Funktion (5)",
        "Manager Unterschriftsberechtigung (5)",
        "Manager – Operative Funktion (5)",
        "Firma gehört zu Firmengruppe",
        "Revisionsstelle",
        "Revisionsstelle - Land",
        "Revisionsstelle - Kanton",
        "Revisionsstelle - Gemeinde",
        "Revisionsstelle - Ort",
      ],
    ],
    FR: [
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
        "Nom de la société",
        "Vat code",
        "Clé CH",
        "Numéro d'identification de l'entreprise",
        "Company Book Number",
        "Siège social/succursale",
        "Date de la dernière mise à jour",
        "Forme juridique",
        "Statut juridique",
        "Statut de la société",
        "CRIF Id",
        "Début de l'activité commerciale",
        "Date de radiation",
        "Objet RH",
        "Objet RH Langue",
        "Nombre de filiales",
        "Province",
        "Canton",
        "Commune",
        "Localité",
        "Code Postal",
        "Rue",
        "Numéro de rue",
        "Adresse-Info complémentaire",
        "Langue d'annonce FOSC",
        "Numéro de téléphone",
        "Email",
        "URL du site web",
        "Fax number",
        "Mobile number",
        "Manager Title (1)",
        "Manager Nom de famille (1)",
        "Manager Prénom(s) / Raison sociale",
        "Manager Lieu d'origine (1)",
        "Manager Lieu d'origine (1)",
        "Manager fonction (1)",
        "Manager Autorisation de signature (1)",
        "Manager - Fonction opérationnelle (1)",
        "Manager Title (2)",
        "Manager Nom de famille (2)",
        "Manager Prénom(2) / Raison sociale",
        "Manager Lieu d'origine (2)",
        "Manager Lieu d'origine (2)",
        "Manager fonction (2)",
        "Manager Autorisation de signature (2)",
        "Manager - Fonction opérationnelle (2)",
        "Manager Title (3)",
        "Manager Nom de famille (3)",
        "Manager Prénom(3) / Raison sociale",
        "Manager Lieu d'origine (3)",
        "Manager Lieu d'origine (3)",
        "Manager fonction (3)",
        "Manager Autorisation de signature (3)",
        "Manager - Fonction opérationnelle (3)",
        "Manager Title (4)",
        "Manager Nom de famille (4)",
        "Manager Prénom(4) / Raison sociale",
        "Manager Lieu d'origine (4)",
        "Manager Lieu d'origine (4)",
        "Manager fonction (4)",
        "Manager Autorisation de signature (4)",
        "Manager - Fonction opérationnelle (4)",
        "Manager Title (5)",
        "Manager Nom de famille (5)",
        "Manager Prénom(5) / Raison sociale",
        "Manager Lieu d'origine (5)",
        "Manager Lieu d'origine (5)",
        "Manager fonction (5)",
        "Manager Autorisation de signature (5)",
        "Manager - Fonction opérationnelle (5)",
        "La société fait partie d'un groupe de sociétés",
        "Organe de révision",
        "Organe de révision - pays",
        "Organe de révision - canton",
        "Organe de révision - commune",
        "Organe de révision - Ville",
      ],
    ],
  },
  completeTemplate: {
    EN: [
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Legacy CH Number",
        "Business identification number",
        "Company Book Number",
        "Office type",
        "Last update date",
        "Legal form group",
        "Legal form",
        "Company status",
        "CRIF Id",
        "Incorporation date",
        "End date",
        "Purpose",
        "Purpose - language",
        "Number of Local Units",
        "Province",
        "Canton",
        "Municipality",
        "Town",
        "Post code",
        "Street",
        "Housenumber",
        "Address-additional info",
        "Official Language of SOGC",
        "Latitude",
        "Longitude",
        "NOGA",
        "NOGA - Description",
        "NACE",
        "NACE - Description",
        "OENACE 2008",
        "OENACE 2008 - Description",
        "SIC",
        "SIC - Description",
        "Employee Range",
        "Employees",
        "Employee Trend",
        "Turnover Range",
        "Turnover",
        "Turnover Trend",
        "Phone number",
        "Email",
        "Website URL",
        "Fax number",
        "Mobile number",
        "Import partners",
        "Is import-oriented",
        "Is export-oriented",
        "Export partners",
        "Manager title (1)",
        "Manager surname (1)",
        "Manager first name / Company name (1)",
        "Manager Year of Birth (1)",
        "Manager origin (1)",
        "Manager function (1)",
        "Manager function - authority to sign (1)",
        "Manager - operative function (1)",
        "Manager title (2)",
        "Manager surname (2)",
        "Manager first name / Company name (2)",
        "Manager Year of Birth (2)",
        "Manager origin (2)",
        "Manager function (2)",
        "Manager function - authority to sign (2)",
        "Manager - operative function (2)",
        "Manager title (3)",
        "Manager surname (3)",
        "Manager first name / Company name (3)",
        "Manager Year of Birth (3)",
        "Manager origin (3)",
        "Manager function (3)",
        "Manager function - authority to sign (3)",
        "Manager - operative function (3)",
        "Manager title (4)",
        "Manager surname (4)",
        "Manager first name / Company name (4)",
        "Manager Year of Birth (4)",
        "Manager origin (4)",
        "Manager function (4)",
        "Manager function - authority to sign (4)",
        "Manager - operative function (4)",
        "Manager title (5)",
        "Manager surname (5)",
        "Manager first name / Company name (5)",
        "Manager Year of Birth (5)",
        "Manager origin (5)",
        "Manager function (5)",
        "Manager function - authority to sign (5)",
        "Manager - operative function (5)",
        "Auditing company - Company belongs to a Company group",
        "Auditing company name",
        "Auditing company - Country",
        "Auditing company - Canton",
        "Auditing company - Municipality",
        "Auditing company - City",
        "Investment assets",
        "Immaterial assets",
        "Property equipment",
        "Financial investments",
        "Current assets",
        "Inventories",
        "Receivables and other assets",
        "Securities",
        "Cash inhand balances with credit institutions",
        "Accruals",
        "Assets",
        "Equity",
        "Shareholders equity",
        "Capital reserves",
        "Profit reserves",
        "Accumulated profit loss",
        "Untaxed reserves",
        "Provisions",
        "Liabilities",
        "Liabilities accruals",
        "Total liabilities and equity",
        "Bank name (1)",
        "Bank name (2)",
        "Bank name (3)",
        "Bank name (4)",
        "Bank name (5)",
      ],
    ],
    IT: [
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Ragione Sociale",
        "Vat code",
        "CH Key",
        "Identificativo Azienda",
        "Company Book Number",
        "Tipo di sede",
        "Data ultimo aggiornamento",
        "Forma legale",
        "Forma legale dettagliata",
        "Stato impresa",
        "CRIF Id",
        "Data di costituzione",
        "Data cessazione",
        "Descrizione attività",
        "Descrizione attività - Lingua",
        "Numero unità locali",
        "Province",
        "Cantone",
        "Città metropolitana",
        "Città",
        "Cap",
        "Indirizzo",
        "Civico",
        "Indirizzo - Ulteriori informazioni",
        "Lingua del messaggio SOGC",
        "Latitude",
        "Longitude",
        "NOGA",
        "NOGA - Descrizione",
        "NACE",
        "NACE - Descrizione",
        "OENACE 2008",
        "OENACE 2008 - Descrizione",
        "SIC",
        "SIC - Descrizione",
        "Classe numero dipendenti",
        "Dipendenti",
        "Trend dipendenti",
        "Fatturato - Range",
        "Fatturato",
        "Trend fatturato",
        "Numero di telefono",
        "Email",
        "Sito web",
        "Fax number",
        "Mobile number",
        "Import partners",
        "Is import-oriented",
        "Export",
        "Export partners",
        "Titolo esponente (1)",
        "Nome esponente (1)",
        "Cognome / Denominazione esponente (1)",
        "Anno di nascita (1)",
        "Nazionalità esponente (1)",
        "Carica esponente (1)",
        "Autorizzazione a firmare esponente (1)",
        "Funzione operativa esponente (1)",
        "Titolo esponente (2)",
        "Nome esponente (2)",
        "Cognome / Denominazione esponente (2)",
        "Anno di nascita (2)",
        "Nazionalità esponente (2)",
        "Carica esponente (2)",
        "Autorizzazione a firmare esponente (2)",
        "Funzione operativa esponente (2)",
        "Titolo esponente (3)",
        "Nome esponente (3)",
        "Cognome / Denominazione esponente (3)",
        "Anno di nascita (3)",
        "Nazionalità esponente (3)",
        "Carica esponente (3)",
        "Autorizzazione a firmare esponente (3)",
        "Funzione operativa esponente (3)",
        "Titolo esponente (4)",
        "Nome esponente (4)",
        "Cognome / Denominazione esponente (4)",
        "Anno di nascita (4)",
        "Nazionalità esponente (4)",
        "Carica esponente (4)",
        "Autorizzazione a firmare esponente (4)",
        "Funzione operativa esponente (4)",
        "Titolo esponente (5)",
        "Nome esponente (5)",
        "Cognome / Denominazione esponente (5)",
        "Anno di nascita (5)",
        "Nazionalità esponente (5)",
        "Carica esponente (5)",
        "Autorizzazione a firmare esponente (5)",
        "Funzione operativa esponente (5)",
        "Appartenenza ad un gruppo",
        "Società di revisione",
        "Società di revisione - Stato",
        "Società di revisione - Cantone",
        "Società di revisione - Città metropolitana",
        "Società di revisione - Città",
        "Investment assets",
        "Immaterial assets",
        "Property equipment",
        "Financial investments",
        "Current assets",
        "Inventories",
        "Receivables and other assets",
        "Securities",
        "Cash inhand balances with credit institutions",
        "Accruals",
        "Assets",
        "Equity",
        "Shareholders equity",
        "Capital reserves",
        "Profit reserves",
        "Accumulated profit loss",
        "Untaxed reserves",
        "Provisions",
        "Liabilities",
        "Liabilities accruals",
        "Total liabilities and equity",
        "Banca (1)",
        "Banca (2)",
        "Banca (3)",
        "Banca (4)",
        "Banca (5)",
      ],
    ],
    DE: [
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Firmenname",
        "UID-Nummer / MWST-Nr.",
        "CH Key",
        "Unternehmens-Identifikationsnummer",
        "Firmenbuchnummer",
        "Hauptsitz/Zweigniederlassung",
        "Datum des letzten Updates",
        "Rechtsform",
        "Rechtsstatus",
        "Firmenstatus",
        "CRIF Id",
        "Beginn Geschäftstätigkeit",
        "Löschdatum",
        "HR-Zweck",
        "HR-Zweck Sprache",
        "Anzahl der Filialen",
        "Province",
        "Kanton",
        "Gemeinde",
        "Ort",
        "PLZ",
        "Strasse",
        "Hausnummer",
        "Adresse-Zusatzinfo",
        "SHAB-Meldungssprache",
        "Latitude",
        "Longitude",
        "NOGA",
        "NOGA - Beschreibung",
        "NACE",
        "NACE - Beschreibung",
        "OENACE 2008",
        "OENACE 2008 - Beschreibung",
        "SIC",
        "SIC - Beschreibung",
        "Mitarbeiterbereich",
        "Anzahl Mitarbeiter gesamt",
        "Mitarbeitertrend",
        "Umsatzbereich",
        "Umsatz",
        "Umsatztrend",
        "Telefonnummer",
        "Email",
        "Website URL",
        "Faxnummer",
        "Handynummer",
        "Import partner",
        "Ist Importeur",
        "Ist Exporteur",
        "Export partner",
        "Manager Title (1)",
        "Manager Nachname (1)",
        "Manager Vorname(n) / Firmenname",
        "Manager Year of Birth (1)",
        "Manager Heimatort (1)",
        "Manager Funktion (1)",
        "Manager Unterschriftsberechtigung (1)",
        "Manager – Operative Funktion (1)",
        "Manager Title (2)",
        "Manager Nachname (2)",
        "Manager Vorname(2) / Firmenname",
        "Manager Year of Birth (2)",
        "Manager Heimatort (2)",
        "Manager Funktion (2)",
        "Manager Unterschriftsberechtigung (2)",
        "Manager – Operative Funktion (2)",
        "Manager Title (3)",
        "Manager Nachname (3)",
        "Manager Vorname(3) / Firmenname",
        "Manager Year of Birth (3)",
        "Manager Heimatort (3)",
        "Manager Funktion (3)",
        "Manager Unterschriftsberechtigung (3)",
        "Manager – Operative Funktion (3)",
        "Manager Title (4)",
        "Manager Nachname (4)",
        "Manager Vorname(4) / Firmenname",
        "Manager Year of Birth (4)",
        "Manager Heimatort (4)",
        "Manager Funktion (4)",
        "Manager Unterschriftsberechtigung (4)",
        "Manager – Operative Funktion (4)",
        "Manager Title (5)",
        "Manager Nachname (5)",
        "Manager Vorname(5) / Firmenname",
        "Manager Year of Birth (5)",
        "Manager Heimatort (5)",
        "Manager Funktion (5)",
        "Manager Unterschriftsberechtigung (5)",
        "Manager – Operative Funktion (5)",
        "Firma gehört zu Firmengruppe",
        "Revisionsstelle",
        "Revisionsstelle - Land",
        "Revisionsstelle - Kanton",
        "Revisionsstelle - Gemeinde",
        "Revisionsstelle - Ort",
        "Anlagevermögen",
        "Immaterielle Vermögenswerte",
        "Sachanlagevermögen",
        "Finanzanlagen",
        "Umlaufvermögen",
        "Bestand",
        "Forderungen und sonstige Vermögenswerte",
        "Sicherheiten",
        "Kassenbestand bei Kreditinstituten",
        "Rückstellungen",
        "Aktiva",
        "Eigenkapital",
        "Eigenkapital der Aktionäre",
        "Kapitalrücklagen",
        "Gewinnrücklagen",
        "Gewinn und Verlust",
        "Unversteuerte Rücklagen",
        "Rückstellungen",
        "Passiva",
        "Rückstellungen für Verbindlichkeiten",
        "Gesamtkapital",
        "Bank name (1)",
        "Bank name (2)",
        "Bank name (3)",
        "Bank name (4)",
        "Bank name (5)",
      ],
    ],
    FR: [
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
        "Nom de la société",
        "Vat code",
        "Clé CH",
        "Numéro d'identification de l'entreprise",
        "Company Book Number",
        "Siège social/succursale",
        "Date de la dernière mise à jour",
        "Forme juridique",
        "Statut juridique",
        "Statut de la société",
        "CRIF Id",
        "Début de l'activité commerciale",
        "Date de radiation",
        "Objet RH",
        "Objet RH Langue",
        "Nombre de filiales",
        "Province",
        "Canton",
        "Commune",
        "Localité",
        "Code Postal",
        "Rue",
        "Numéro de rue",
        "Adresse-Info complémentaire",
        "Langue d'annonce FOSC",
        "Latitude",
        "Longitude",
        "NOGA",
        "NOGA - description",
        "NACE",
        "NACE - description",
        "OENACE 2008",
        "OENACE 2008 - description",
        "SIC",
        "SIC - description",
        "Secteur des employés",
        "Nombre total d'employés",
        "Tendance des effectifs",
        "Domaine du chiffre d'affaires",
        "Chiffre d'affaires",
        "Tendance du chiffre d'affaires",
        "Numéro de téléphone",
        "Email",
        "URL du site web",
        "Fax number",
        "Mobile number",
        "Import partners",
        "Is import-oriented",
        "Orienté vers l'exportation",
        "Export partners",
        "Manager Title (1)",
        "Manager Nom de famille (1)",
        "Manager Prénom(s) / Raison sociale",
        "Manager Lieu d'origine (1)",
        "Manager Lieu d'origine (1)",
        "Manager fonction (1)",
        "Manager Autorisation de signature (1)",
        "Manager - Fonction opérationnelle (1)",
        "Manager Title (2)",
        "Manager Nom de famille (2)",
        "Manager Prénom(2) / Raison sociale",
        "Manager Lieu d'origine (2)",
        "Manager Lieu d'origine (2)",
        "Manager fonction (2)",
        "Manager Autorisation de signature (2)",
        "Manager - Fonction opérationnelle (2)",
        "Manager Title (3)",
        "Manager Nom de famille (3)",
        "Manager Prénom(3) / Raison sociale",
        "Manager Lieu d'origine (3)",
        "Manager Lieu d'origine (3)",
        "Manager fonction (3)",
        "Manager Autorisation de signature (3)",
        "Manager - Fonction opérationnelle (3)",
        "Manager Title (4)",
        "Manager Nom de famille (4)",
        "Manager Prénom(4) / Raison sociale",
        "Manager Lieu d'origine (4)",
        "Manager Lieu d'origine (4)",
        "Manager fonction (4)",
        "Manager Autorisation de signature (4)",
        "Manager - Fonction opérationnelle (4)",
        "Manager Title (5)",
        "Manager Nom de famille (5)",
        "Manager Prénom(5) / Raison sociale",
        "Manager Lieu d'origine (5)",
        "Manager Lieu d'origine (5)",
        "Manager fonction (5)",
        "Manager Autorisation de signature (5)",
        "Manager - Fonction opérationnelle (5)",
        "La société fait partie d'un groupe de sociétés",
        "Organe de révision",
        "Organe de révision - pays",
        "Organe de révision - canton",
        "Organe de révision - commune",
        "Organe de révision - Ville",
        "Investment assets",
        "Immaterial assets",
        "Property equipment",
        "Financial investments",
        "Current assets",
        "Inventories",
        "Receivables and other assets",
        "Securities",
        "Cash inhand balances with credit institutions",
        "Accruals",
        "Assets",
        "Equity",
        "Shareholders equity",
        "Capital reserves",
        "Profit reserves",
        "Accumulated profit loss",
        "Untaxed reserves",
        "Provisions",
        "Liabilities",
        "Liabilities accruals",
        "Total liabilities and equity",
        "Bank name (1)",
        "Bank name (2)",
        "Bank name (3)",
        "Bank name (4)",
        "Bank name (5)",
      ],
    ],
  },
  customTemplate: {
    EN: [
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Turnover",
        "Post code",
        "Employees",
        "Turnover",
        "Import partners",
        "Export partners",
      ],
    ],
    IT: [
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Fatturato",
        "Cap",
        "Dipendenti",
        "Fatturato",
        "Import partners",
        "Export partners",
      ],
    ],
    DE: [
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Umsatz",
        "PLZ",
        "Mitarbeiterbereich",
        "Umsatz",
        "Import partner",
        "Export partner",
      ],
    ],
    FR: [
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
        "Chiffre d'affaires",
        "Code Postal",
        "Secteur des employés",
        "Chiffre d'affaires",
        "Import partners",
        "Export partners",
      ],
    ],
  },
  base: {
    EN: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Prospect $(Prospect)$",
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Prospect $(Prospect)$",
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Prospect $(Prospect)$",
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Prospect $(Prospect)$",
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Prospect $(Prospect)$",
      ],
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    IT: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Prospect $(Prospect)$",
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Prospect $(Prospect)$",
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Prospect $(Prospect)$",
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Prospect $(Prospect)$",
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Prospect $(Prospect)$",
      ],
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    DE: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Interessent $(Prospect)$",
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Interessent $(Prospect)$",
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Interessent $(Prospect)$",
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Interessent $(Prospect)$",
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Interessent $(Prospect)$",
      ],
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    FR: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Perspective $(Prospect)$",
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Perspective $(Prospect)$",
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Perspective $(Prospect)$",
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Perspective $(Prospect)$",
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Perspective $(Prospect)$",
      ],
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
      ],
    ],
  },
  marketing: {
    EN: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "öko&more, Service- und DienstleistungsgmbH",
        "ATU37717880",
        null,
        null,
        "FN370583a",
        "Headquarter",
        null,
        "Limited liability company",
        "Limited liability company",
        "Active",
        "3286000064719317",
        "20-10-2011",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Sankt Johann im Saggautal",
        "8453",
        "Saggau",
        "19",
        null,
        null,
        null,
        null,
        null,
        null,
        "9113651943",
        "",
        "Lerch",
        "Gloria",
        1945,
        null,
        "association chairman",
        null,
        null,
        "",
        "Hebenstreit",
        "Jakob",
        1985,
        null,
        null,
        null,
        null,
        "",
        "Krainz",
        "Anton",
        1994,
        null,
        null,
        null,
        null,
        "",
        "Klingler",
        "Nadia",
        1955,
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärztliche Not- und Bereitschaftsdienst Errichtungsges.m.b.H.",
        "ATU33080309",
        null,
        null,
        "FN508741z",
        "Headquarter",
        null,
        "Limited liability company",
        "Limited liability company",
        "Active",
        "3557000088055547",
        "06-03-2019",
        null,
        null,
        null,
        1,
        "Wien",
        null,
        null,
        "Wien",
        "1010",
        "Stock-im-Eisen-Platz",
        "3",
        null,
        null,
        "2441389209",
        null,
        null,
        null,
        null,
        "",
        "Puntigam",
        "Sigrid",
        1967,
        null,
        "executive committee - general director deputy",
        null,
        null,
        "",
        "Pointner",
        "Lorenz",
        1977,
        null,
        "administrator - according to AO, KO",
        null,
        null,
        "",
        "Sigl",
        "Ajna",
        1969,
        null,
        "trustee",
        null,
        null,
        "",
        "Moser",
        "Teodor",
        1995,
        null,
        null,
        null,
        null,
        "",
        "Mühlberger",
        "Maida",
        1971,
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Üllen Landmaschinenhandel GmbH",
        "ATU50316439",
        null,
        null,
        "FN283967z",
        "Headquarter",
        null,
        "Limited liability company",
        "Limited liability company",
        "Active",
        "3628000038109377",
        "25-09-2006",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Radkersburg Umgebung",
        "8490",
        "Sicheldorf",
        "1",
        null,
        null,
        "7373721035",
        "xjovanovic@lackner.at",
        null,
        "0504219384",
        null,
        "",
        "Klammer",
        "Mathias",
        1985,
        null,
        "deputy",
        null,
        null,
        "",
        "Amann",
        "Marie-Sophie",
        1969,
        null,
        null,
        null,
        null,
        "",
        "Reisinger",
        "Dora",
        1966,
        null,
        null,
        null,
        null,
        "",
        "Stöger",
        "Louisa",
        1959,
        null,
        null,
        null,
        null,
        "",
        "Neubacher",
        "Magdalena",
        1972,
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "üsers Poschtli GmbH",
        "CHE643723387",
        "CHE29375",
        "CHE1638960148",
        null,
        "Headquarter",
        "08-09-2022",
        "Limited liability company",
        "Limited liability company",
        "Active",
        "121005376243",
        "30-12-2009",
        null,
        "Die Gesellschaft bezweckt den Transport von Personen und Waren aller Art. Die Gesellschaft kann sich an ähnlichen und anderen Unternehmen beteiligen. Sie ist zu allen Massnahmen berechtigt, welche zur Erreichung des Gesellschaftszweckes dienlich erscheinen.",
        "German",
        0,
        null,
        "Appenzell Ausserrhoden",
        "Reute (AR)",
        "Reute AR",
        "9411",
        "Sturzenhard",
        "4",
        null,
        "German",
        null,
        null,
        null,
        null,
        null,
        null,
        "Widmer",
        "Milan",
        null,
        "Slovenia",
        "special secretary",
        "Limited joint signature",
        "CEO (Chief Executive Officer)",
        null,
        "Amrein",
        "Marcel",
        null,
        "Norfolk Island",
        null,
        null,
        "N. a.",
        null,
        "Stadelmann",
        "Stephanie",
        null,
        "Mauritania",
        "secretary",
        "Single procuration for branch",
        "Decision maker operations",
        null,
        "Burri",
        "Marinette",
        null,
        "Grenada",
        null,
        null,
        "Decision maker operations",
        null,
        "Hürlimann",
        "Imer",
        null,
        "China",
        null,
        null,
        "Decision maker sales",
        "False",
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärzte am werk GmbH",
        "CHE066224675",
        "CHE80022",
        "CHE3151700178",
        null,
        "Headquarter",
        "13-07-2020",
        "Limited liability company",
        "Limited liability company",
        "Active",
        "121005343425",
        "11-12-2007",
        null,
        "Vermietung von Räumlichkeiten, Geräten und Mobilien an selbständig praktizierende Aerzte und Therapeuten, Erbringung von Dienstleistungen für den Betrieb der Praxen: die Gesellschaft kann Zweigniederlassungen und Tochtergesellschaften errichten, sich an anderen Unternehmen beteiligen oder gleichartige oder verwandte Unternehmen erwerben oder errichten sowie Grundeigentum erwerben, verwalten und veräussern.",
        "German",
        0,
        null,
        "Aargau",
        "Rheinfelden",
        "Rheinfelden",
        "4310",
        "Fassbindstrasse",
        "2-4",
        null,
        "German",
        "4200616366",
        null,
        "www.hofer.info",
        null,
        null,
        null,
        "Weibel",
        "Léa",
        null,
        "Indonesia",
        "special secretary",
        "Joint procuration according to OR 459 para. 2",
        "Decision maker communication",
        null,
        "Wegmann",
        "Gertrud",
        null,
        "Palau",
        "honorary president",
        "Joint signature at two",
        "Decision maker communication",
        null,
        "Schürch",
        "Nelio",
        null,
        "Congo",
        null,
        null,
        "Decision maker quality",
        null,
        "Roth",
        "Inge",
        null,
        "Norway",
        null,
        null,
        "N. a.",
        null,
        "Zbinden",
        "Altin",
        null,
        "Turkey",
        null,
        null,
        "Manager of Finance",
        "False",
      ],
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Legacy CH Number",
        "Business identification number",
        "Company Book Number",
        "Office type",
        "Last update date",
        "Legal form group",
        "Legal form",
        "Company status",
        "CRIF Id",
        "Incorporation date",
        "End date",
        "Purpose",
        "Purpose - language",
        "Number of Local Units",
        "Province",
        "Canton",
        "Municipality",
        "Town",
        "Post code",
        "Street",
        "Housenumber",
        "Address-additional info",
        "Official Language of SOGC",
        "Phone number",
        "Email",
        "Website URL",
        "Fax number",
        "Mobile number",
        "Manager title (1)",
        "Manager surname (1)",
        "Manager first name / Company name (1)",
        "Manager Year of Birth (1)",
        "Manager origin (1)",
        "Manager function (1)",
        "Manager function - authority to sign (1)",
        "Manager - operative function (1)",
        "Manager title (2)",
        "Manager surname (2)",
        "Manager first name / Company name (2)",
        "Manager Year of Birth (2)",
        "Manager origin (2)",
        "Manager function (2)",
        "Manager function - authority to sign (2)",
        "Manager - operative function (2)",
        "Manager title (3)",
        "Manager surname (3)",
        "Manager first name / Company name (3)",
        "Manager Year of Birth (3)",
        "Manager origin (3)",
        "Manager function (3)",
        "Manager function - authority to sign (3)",
        "Manager - operative function (3)",
        "Manager title (4)",
        "Manager surname (4)",
        "Manager first name / Company name (4)",
        "Manager Year of Birth (4)",
        "Manager origin (4)",
        "Manager function (4)",
        "Manager function - authority to sign (4)",
        "Manager - operative function (4)",
        "Manager title (5)",
        "Manager surname (5)",
        "Manager first name / Company name (5)",
        "Manager Year of Birth (5)",
        "Manager origin (5)",
        "Manager function (5)",
        "Manager function - authority to sign (5)",
        "Manager - operative function (5)",
        "Auditing company - Company belongs to a Company group",
        "Auditing company name",
        "Auditing company - Country",
        "Auditing company - Canton",
        "Auditing company - Municipality",
        "Auditing company - City",
      ],
    ],
    IT: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "öko&more, Service- und DienstleistungsgmbH",
        "ATU37717880",
        null,
        null,
        "FN370583a",
        "Sede centrale",
        null,
        "Società a garanzia limitata",
        "Società a garanzia limitata",
        "Attivo",
        "3286000064719317",
        "20-10-2011",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Sankt Johann im Saggautal",
        "8453",
        "Saggau",
        "19",
        null,
        null,
        null,
        null,
        null,
        null,
        "9113651943",
        "",
        "Lerch",
        "Gloria",
        1945,
        null,
        "Verband Obmann",
        null,
        null,
        "",
        "Hebenstreit",
        "Jakob",
        1985,
        null,
        null,
        null,
        null,
        "",
        "Krainz",
        "Anton",
        1994,
        null,
        null,
        null,
        null,
        "",
        "Klingler",
        "Nadia",
        1955,
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärztliche Not- und Bereitschaftsdienst Errichtungsges.m.b.H.",
        "ATU33080309",
        null,
        null,
        "FN508741z",
        "Sede centrale",
        null,
        "Società a garanzia limitata",
        "Società a garanzia limitata",
        "Attivo",
        "3557000088055547",
        "06-03-2019",
        null,
        null,
        null,
        1,
        "Wien",
        null,
        null,
        "Wien",
        "1010",
        "Stock-im-Eisen-Platz",
        "3",
        null,
        null,
        "2441389209",
        null,
        null,
        null,
        null,
        "",
        "Puntigam",
        "Sigrid",
        1967,
        null,
        "Vorstand - Generaldirektor Stellvertreter",
        null,
        null,
        "",
        "Pointner",
        "Lorenz",
        1977,
        null,
        "Sachwalter - nach AO, KO",
        null,
        null,
        "",
        "Sigl",
        "Ajna",
        1969,
        null,
        "Treuhänder",
        null,
        null,
        "",
        "Moser",
        "Teodor",
        1995,
        null,
        null,
        null,
        null,
        "",
        "Mühlberger",
        "Maida",
        1971,
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Üllen Landmaschinenhandel GmbH",
        "ATU50316439",
        null,
        null,
        "FN283967z",
        "Sede centrale",
        null,
        "Società a garanzia limitata",
        "Società a garanzia limitata",
        "Attivo",
        "3628000038109377",
        "25-09-2006",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Radkersburg Umgebung",
        "8490",
        "Sicheldorf",
        "1",
        null,
        null,
        "7373721035",
        "xjovanovic@lackner.at",
        null,
        "0504219384",
        null,
        "",
        "Klammer",
        "Mathias",
        1985,
        null,
        "Stellvertreter",
        null,
        null,
        "",
        "Amann",
        "Marie-Sophie",
        1969,
        null,
        null,
        null,
        null,
        "",
        "Reisinger",
        "Dora",
        1966,
        null,
        null,
        null,
        null,
        "",
        "Stöger",
        "Louisa",
        1959,
        null,
        null,
        null,
        null,
        "",
        "Neubacher",
        "Magdalena",
        1972,
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "üsers Poschtli GmbH",
        "CHE643723387",
        "CHE29375",
        "CHE1638960148",
        null,
        "Sede centrale",
        "08-09-2022",
        "Società a garanzia limitata",
        "Società a garanzia limitata",
        "Attivo",
        "121005376243",
        "30-12-2009",
        null,
        "Die Gesellschaft bezweckt den Transport von Personen und Waren aller Art. Die Gesellschaft kann sich an ähnlichen und anderen Unternehmen beteiligen. Sie ist zu allen Massnahmen berechtigt, welche zur Erreichung des Gesellschaftszweckes dienlich erscheinen.",
        "Tedesco",
        0,
        null,
        "Appenzell Ausserrhoden",
        "Reute (AR)",
        "Reute AR",
        "9411",
        "Sturzenhard",
        "4",
        null,
        "Tedesco",
        null,
        null,
        null,
        null,
        null,
        null,
        "Widmer",
        "Milan",
        null,
        "Slovenia",
        "segretario speciale",
        "Firma collettiva limitata",
        "CEO (Chief Executive Officer)",
        null,
        "Amrein",
        "Marcel",
        null,
        "Norfolk, isola",
        null,
        null,
        "N. a.",
        null,
        "Stadelmann",
        "Stephanie",
        null,
        "Mauritania",
        "segretario",
        "Procura individuale limitata alla filiale",
        "Operazioni del decisore",
        null,
        "Burri",
        "Marinette",
        null,
        "Grenada",
        null,
        null,
        "Operazioni del decisore",
        null,
        "Hürlimann",
        "Imer",
        null,
        "Cina, Rep. pop.",
        null,
        null,
        "Decisore vendita",
        "False",
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärzte am werk GmbH",
        "CHE066224675",
        "CHE80022",
        "CHE3151700178",
        null,
        "Sede centrale",
        "13-07-2020",
        "Società a garanzia limitata",
        "Società a garanzia limitata",
        "Attivo",
        "121005343425",
        "11-12-2007",
        null,
        "Vermietung von Räumlichkeiten, Geräten und Mobilien an selbständig praktizierende Aerzte und Therapeuten, Erbringung von Dienstleistungen für den Betrieb der Praxen: die Gesellschaft kann Zweigniederlassungen und Tochtergesellschaften errichten, sich an anderen Unternehmen beteiligen oder gleichartige oder verwandte Unternehmen erwerben oder errichten sowie Grundeigentum erwerben, verwalten und veräussern.",
        "Tedesco",
        0,
        null,
        "Aargau",
        "Rheinfelden",
        "Rheinfelden",
        "4310",
        "Fassbindstrasse",
        "2-4",
        null,
        "Tedesco",
        "4200616366",
        null,
        "www.hofer.info",
        null,
        null,
        null,
        "Weibel",
        "Léa",
        null,
        "Indonesia",
        "segretario speciale",
        "Procura collettiva secondo l'art. 459 cpv. 2 del CO",
        "Comunicazione del decisore",
        null,
        "Wegmann",
        "Gertrud",
        null,
        "Palau, isole",
        "presidente onorario",
        "Firma congiunta di due",
        "Comunicazione del decisore",
        null,
        "Schürch",
        "Nelio",
        null,
        "Congo",
        null,
        null,
        "Qualità del decisore",
        null,
        "Roth",
        "Inge",
        null,
        "Norvegia",
        null,
        null,
        "N. a.",
        null,
        "Zbinden",
        "Altin",
        null,
        "Turchia",
        null,
        null,
        "capo die servizi finanziari / contabilità",
        "False",
      ],
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Ragione Sociale",
        "Vat code",
        "CH Key",
        "Identificativo Azienda",
        "Company Book Number",
        "Tipo di sede",
        "Data ultimo aggiornamento",
        "Forma legale",
        "Forma legale dettagliata",
        "Stato impresa",
        "CRIF Id",
        "Data di costituzione",
        "Data cessazione",
        "Descrizione attività",
        "Descrizione attività - Lingua",
        "Numero unità locali",
        "Province",
        "Cantone",
        "Città metropolitana",
        "Città",
        "Cap",
        "Indirizzo",
        "Civico",
        "Indirizzo - Ulteriori informazioni",
        "Lingua del messaggio SOGC",
        "Numero di telefono",
        "Email",
        "Sito web",
        "Fax number",
        "Mobile number",
        "Titolo esponente (1)",
        "Nome esponente (1)",
        "Cognome / Denominazione esponente (1)",
        "Anno di nascita (1)",
        "Nazionalità esponente (1)",
        "Carica esponente (1)",
        "Autorizzazione a firmare esponente (1)",
        "Funzione operativa esponente (1)",
        "Titolo esponente (2)",
        "Nome esponente (2)",
        "Cognome / Denominazione esponente (2)",
        "Anno di nascita (2)",
        "Nazionalità esponente (2)",
        "Carica esponente (2)",
        "Autorizzazione a firmare esponente (2)",
        "Funzione operativa esponente (2)",
        "Titolo esponente (3)",
        "Nome esponente (3)",
        "Cognome / Denominazione esponente (3)",
        "Anno di nascita (3)",
        "Nazionalità esponente (3)",
        "Carica esponente (3)",
        "Autorizzazione a firmare esponente (3)",
        "Funzione operativa esponente (3)",
        "Titolo esponente (4)",
        "Nome esponente (4)",
        "Cognome / Denominazione esponente (4)",
        "Anno di nascita (4)",
        "Nazionalità esponente (4)",
        "Carica esponente (4)",
        "Autorizzazione a firmare esponente (4)",
        "Funzione operativa esponente (4)",
        "Titolo esponente (5)",
        "Nome esponente (5)",
        "Cognome / Denominazione esponente (5)",
        "Anno di nascita (5)",
        "Nazionalità esponente (5)",
        "Carica esponente (5)",
        "Autorizzazione a firmare esponente (5)",
        "Funzione operativa esponente (5)",
        "Appartenenza ad un gruppo",
        "Società di revisione",
        "Società di revisione - Stato",
        "Società di revisione - Cantone",
        "Società di revisione - Città metropolitana",
        "Società di revisione - Città",
      ],
    ],
    DE: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "öko&more, Service- und DienstleistungsgmbH",
        "ATU37717880",
        null,
        null,
        "FN370583a",
        "Hauptsitz",
        null,
        "Gesellschaft mit beschränkter Haftung",
        "Gesellschaft mit beschränkter Haftung",
        "Aktiv",
        "3286000064719317",
        "20-10-2011",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Sankt Johann im Saggautal",
        "8453",
        "Saggau",
        "19",
        null,
        null,
        null,
        null,
        null,
        null,
        "9113651943",
        "",
        "Lerch",
        "Gloria",
        1945,
        null,
        "Verband Obmann",
        null,
        null,
        "",
        "Hebenstreit",
        "Jakob",
        1985,
        null,
        null,
        null,
        null,
        "",
        "Krainz",
        "Anton",
        1994,
        null,
        null,
        null,
        null,
        "",
        "Klingler",
        "Nadia",
        1955,
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärztliche Not- und Bereitschaftsdienst Errichtungsges.m.b.H.",
        "ATU33080309",
        null,
        null,
        "FN508741z",
        "Hauptsitz",
        null,
        "Gesellschaft mit beschränkter Haftung",
        "Gesellschaft mit beschränkter Haftung",
        "Aktiv",
        "3557000088055547",
        "06-03-2019",
        null,
        null,
        null,
        1,
        "Wien",
        null,
        null,
        "Wien",
        "1010",
        "Stock-im-Eisen-Platz",
        "3",
        null,
        null,
        "2441389209",
        null,
        null,
        null,
        null,
        "",
        "Puntigam",
        "Sigrid",
        1967,
        null,
        "Vorstand - Generaldirektor Stellvertreter",
        null,
        null,
        "",
        "Pointner",
        "Lorenz",
        1977,
        null,
        "Sachwalter - nach AO, KO",
        null,
        null,
        "",
        "Sigl",
        "Ajna",
        1969,
        null,
        "Treuhänder",
        null,
        null,
        "",
        "Moser",
        "Teodor",
        1995,
        null,
        null,
        null,
        null,
        "",
        "Mühlberger",
        "Maida",
        1971,
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Üllen Landmaschinenhandel GmbH",
        "ATU50316439",
        null,
        null,
        "FN283967z",
        "Hauptsitz",
        null,
        "Gesellschaft mit beschränkter Haftung",
        "Gesellschaft mit beschränkter Haftung",
        "Aktiv",
        "3628000038109377",
        "25-09-2006",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Radkersburg Umgebung",
        "8490",
        "Sicheldorf",
        "1",
        null,
        null,
        "7373721035",
        "xjovanovic@lackner.at",
        null,
        "0504219384",
        null,
        "",
        "Klammer",
        "Mathias",
        1985,
        null,
        "Stellvertreter",
        null,
        null,
        "",
        "Amann",
        "Marie-Sophie",
        1969,
        null,
        null,
        null,
        null,
        "",
        "Reisinger",
        "Dora",
        1966,
        null,
        null,
        null,
        null,
        "",
        "Stöger",
        "Louisa",
        1959,
        null,
        null,
        null,
        null,
        "",
        "Neubacher",
        "Magdalena",
        1972,
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "üsers Poschtli GmbH",
        "CHE643723387",
        "CHE29375",
        "CHE1638960148",
        null,
        "Hauptsitz",
        "08-09-2022",
        "Gesellschaft mit beschränkter Haftung",
        "Gesellschaft mit beschränkter Haftung",
        "Aktiv",
        "121005376243",
        "30-12-2009",
        null,
        "Die Gesellschaft bezweckt den Transport von Personen und Waren aller Art. Die Gesellschaft kann sich an ähnlichen und anderen Unternehmen beteiligen. Sie ist zu allen Massnahmen berechtigt, welche zur Erreichung des Gesellschaftszweckes dienlich erscheinen.",
        "Deutsch",
        0,
        null,
        "Appenzell Ausserrhoden",
        "Reute (AR)",
        "Reute AR",
        "9411",
        "Sturzenhard",
        "4",
        null,
        "Deutsch",
        null,
        null,
        null,
        null,
        null,
        null,
        "Widmer",
        "Milan",
        null,
        "Slowenien",
        "Sekretär ausgedehnt",
        "Eingeschränkte Kollektivunterschrift",
        "CEO (Chief Executive Officer)",
        null,
        "Amrein",
        "Marcel",
        null,
        "Norfolkinsel",
        null,
        null,
        "N. a.",
        null,
        "Stadelmann",
        "Stephanie",
        null,
        "Mauretanien",
        "Sekretär",
        "Einzelprokura beschränkt auf die Zweigniederlassung",
        "EntscheiderIn Betrieb",
        null,
        "Burri",
        "Marinette",
        null,
        "Grenada",
        null,
        null,
        "EntscheiderIn Betrieb",
        null,
        "Hürlimann",
        "Imer",
        null,
        "China",
        null,
        null,
        "EntscheiderIn Verkauf",
        "False",
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärzte am werk GmbH",
        "CHE066224675",
        "CHE80022",
        "CHE3151700178",
        null,
        "Hauptsitz",
        "13-07-2020",
        "Gesellschaft mit beschränkter Haftung",
        "Gesellschaft mit beschränkter Haftung",
        "Aktiv",
        "121005343425",
        "11-12-2007",
        null,
        "Vermietung von Räumlichkeiten, Geräten und Mobilien an selbständig praktizierende Aerzte und Therapeuten, Erbringung von Dienstleistungen für den Betrieb der Praxen: die Gesellschaft kann Zweigniederlassungen und Tochtergesellschaften errichten, sich an anderen Unternehmen beteiligen oder gleichartige oder verwandte Unternehmen erwerben oder errichten sowie Grundeigentum erwerben, verwalten und veräussern.",
        "Deutsch",
        0,
        null,
        "Aargau",
        "Rheinfelden",
        "Rheinfelden",
        "4310",
        "Fassbindstrasse",
        "2-4",
        null,
        "Deutsch",
        "4200616366",
        null,
        "www.hofer.info",
        null,
        null,
        null,
        "Weibel",
        "Léa",
        null,
        "Indonesien",
        "Sekretär ausgedehnt",
        "Kollektivprokura gemäss OR Art. 459 Abs. 2",
        "EntscheiderIn Kommunikation",
        null,
        "Wegmann",
        "Gertrud",
        null,
        "Palau",
        "Ehrenpräsident",
        "Kollektivunterschrift zu zweien",
        "EntscheiderIn Kommunikation",
        null,
        "Schürch",
        "Nelio",
        null,
        "Kongo",
        null,
        null,
        "EntscheiderIn Qualität",
        null,
        "Roth",
        "Inge",
        null,
        "Norwegen",
        null,
        null,
        "N. a.",
        null,
        "Zbinden",
        "Altin",
        null,
        "Türkei",
        null,
        null,
        "Finanz/Rechn.Leiter",
        "False",
      ],
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Firmenname",
        "UID-Nummer / MWST-Nr.",
        "CH Key",
        "Unternehmens-Identifikationsnummer",
        "Firmenbuchnummer",
        "Hauptsitz/Zweigniederlassung",
        "Datum des letzten Updates",
        "Rechtsform",
        "Rechtsstatus",
        "Firmenstatus",
        "CRIF Id",
        "Beginn Geschäftstätigkeit",
        "Löschdatum",
        "HR-Zweck",
        "HR-Zweck Sprache",
        "Anzahl der Filialen",
        "Province",
        "Kanton",
        "Gemeinde",
        "Ort",
        "PLZ",
        "Strasse",
        "Hausnummer",
        "Adresse-Zusatzinfo",
        "SHAB-Meldungssprache",
        "Telefonnummer",
        "Email",
        "Website URL",
        "Faxnummer",
        "Handynummer",
        "Manager Title (1)",
        "Manager Nachname (1)",
        "Manager Vorname(n) / Firmenname",
        "Manager Year of Birth (1)",
        "Manager Heimatort (1)",
        "Manager Funktion (1)",
        "Manager Unterschriftsberechtigung (1)",
        "Manager – Operative Funktion (1)",
        "Manager Title (2)",
        "Manager Nachname (2)",
        "Manager Vorname(2) / Firmenname",
        "Manager Year of Birth (2)",
        "Manager Heimatort (2)",
        "Manager Funktion (2)",
        "Manager Unterschriftsberechtigung (2)",
        "Manager – Operative Funktion (2)",
        "Manager Title (3)",
        "Manager Nachname (3)",
        "Manager Vorname(3) / Firmenname",
        "Manager Year of Birth (3)",
        "Manager Heimatort (3)",
        "Manager Funktion (3)",
        "Manager Unterschriftsberechtigung (3)",
        "Manager – Operative Funktion (3)",
        "Manager Title (4)",
        "Manager Nachname (4)",
        "Manager Vorname(4) / Firmenname",
        "Manager Year of Birth (4)",
        "Manager Heimatort (4)",
        "Manager Funktion (4)",
        "Manager Unterschriftsberechtigung (4)",
        "Manager – Operative Funktion (4)",
        "Manager Title (5)",
        "Manager Nachname (5)",
        "Manager Vorname(5) / Firmenname",
        "Manager Year of Birth (5)",
        "Manager Heimatort (5)",
        "Manager Funktion (5)",
        "Manager Unterschriftsberechtigung (5)",
        "Manager – Operative Funktion (5)",
        "Firma gehört zu Firmengruppe",
        "Revisionsstelle",
        "Revisionsstelle - Land",
        "Revisionsstelle - Kanton",
        "Revisionsstelle - Gemeinde",
        "Revisionsstelle - Ort",
      ],
    ],
    FR: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "öko&more, Service- und DienstleistungsgmbH",
        "ATU37717880",
        null,
        null,
        "FN370583a",
        "Siège social",
        null,
        "Société à responsabilité limitée",
        "Société à responsabilité limitée",
        "Actif",
        "3286000064719317",
        "20-10-2011",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Sankt Johann im Saggautal",
        "8453",
        "Saggau",
        "19",
        null,
        null,
        null,
        null,
        null,
        null,
        "9113651943",
        "",
        "Lerch",
        "Gloria",
        1945,
        null,
        "Verband Obmann",
        null,
        null,
        "",
        "Hebenstreit",
        "Jakob",
        1985,
        null,
        null,
        null,
        null,
        "",
        "Krainz",
        "Anton",
        1994,
        null,
        null,
        null,
        null,
        "",
        "Klingler",
        "Nadia",
        1955,
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärztliche Not- und Bereitschaftsdienst Errichtungsges.m.b.H.",
        "ATU33080309",
        null,
        null,
        "FN508741z",
        "Siège social",
        null,
        "Société à responsabilité limitée",
        "Société à responsabilité limitée",
        "Actif",
        "3557000088055547",
        "06-03-2019",
        null,
        null,
        null,
        1,
        "Wien",
        null,
        null,
        "Wien",
        "1010",
        "Stock-im-Eisen-Platz",
        "3",
        null,
        null,
        "2441389209",
        null,
        null,
        null,
        null,
        "",
        "Puntigam",
        "Sigrid",
        1967,
        null,
        "Vorstand - Generaldirektor Stellvertreter",
        null,
        null,
        "",
        "Pointner",
        "Lorenz",
        1977,
        null,
        "Sachwalter - nach AO, KO",
        null,
        null,
        "",
        "Sigl",
        "Ajna",
        1969,
        null,
        "Treuhänder",
        null,
        null,
        "",
        "Moser",
        "Teodor",
        1995,
        null,
        null,
        null,
        null,
        "",
        "Mühlberger",
        "Maida",
        1971,
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Üllen Landmaschinenhandel GmbH",
        "ATU50316439",
        null,
        null,
        "FN283967z",
        "Siège social",
        null,
        "Société à responsabilité limitée",
        "Société à responsabilité limitée",
        "Actif",
        "3628000038109377",
        "25-09-2006",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Radkersburg Umgebung",
        "8490",
        "Sicheldorf",
        "1",
        null,
        null,
        "7373721035",
        "xjovanovic@lackner.at",
        null,
        "0504219384",
        null,
        "",
        "Klammer",
        "Mathias",
        1985,
        null,
        "Stellvertreter",
        null,
        null,
        "",
        "Amann",
        "Marie-Sophie",
        1969,
        null,
        null,
        null,
        null,
        "",
        "Reisinger",
        "Dora",
        1966,
        null,
        null,
        null,
        null,
        "",
        "Stöger",
        "Louisa",
        1959,
        null,
        null,
        null,
        null,
        "",
        "Neubacher",
        "Magdalena",
        1972,
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "üsers Poschtli GmbH",
        "CHE643723387",
        "CHE29375",
        "CHE1638960148",
        null,
        "Siège social",
        "08-09-2022",
        "Société à responsabilité limitée",
        "Société à responsabilité limitée",
        "Actif",
        "121005376243",
        "30-12-2009",
        null,
        "Die Gesellschaft bezweckt den Transport von Personen und Waren aller Art. Die Gesellschaft kann sich an ähnlichen und anderen Unternehmen beteiligen. Sie ist zu allen Massnahmen berechtigt, welche zur Erreichung des Gesellschaftszweckes dienlich erscheinen.",
        "Allemand",
        0,
        null,
        "Appenzell Ausserrhoden",
        "Reute (AR)",
        "Reute AR",
        "9411",
        "Sturzenhard",
        "4",
        null,
        "Allemand",
        null,
        null,
        null,
        null,
        null,
        null,
        "Widmer",
        "Milan",
        null,
        "Slovénie",
        "secrétaire spécial",
        "Signature collective limitée",
        "CEO (Chief Executive Officer)",
        null,
        "Amrein",
        "Marcel",
        null,
        "Norfolk, Île",
        null,
        null,
        "N. a.",
        null,
        "Stadelmann",
        "Stephanie",
        null,
        "Mauritanie",
        "secrétaire",
        "Procuration individuelle limitée à la succursale",
        "Opérations du décideur",
        null,
        "Burri",
        "Marinette",
        null,
        "Grenade",
        null,
        null,
        "Opérations du décideur",
        null,
        "Hürlimann",
        "Imer",
        null,
        "Chine",
        null,
        null,
        "Preneur de décision ventes",
        "False",
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärzte am werk GmbH",
        "CHE066224675",
        "CHE80022",
        "CHE3151700178",
        null,
        "Siège social",
        "13-07-2020",
        "Société à responsabilité limitée",
        "Société à responsabilité limitée",
        "Actif",
        "121005343425",
        "11-12-2007",
        null,
        "Vermietung von Räumlichkeiten, Geräten und Mobilien an selbständig praktizierende Aerzte und Therapeuten, Erbringung von Dienstleistungen für den Betrieb der Praxen: die Gesellschaft kann Zweigniederlassungen und Tochtergesellschaften errichten, sich an anderen Unternehmen beteiligen oder gleichartige oder verwandte Unternehmen erwerben oder errichten sowie Grundeigentum erwerben, verwalten und veräussern.",
        "Allemand",
        0,
        null,
        "Aargau",
        "Rheinfelden",
        "Rheinfelden",
        "4310",
        "Fassbindstrasse",
        "2-4",
        null,
        "Allemand",
        "4200616366",
        null,
        "www.hofer.info",
        null,
        null,
        null,
        "Weibel",
        "Léa",
        null,
        "Indonésie",
        "secrétaire spécial",
        "Procuration collective selon CO art. 459 al. 2",
        "Communication du décideur",
        null,
        "Wegmann",
        "Gertrud",
        null,
        "Palaos",
        "président d'honneur",
        "Signature collective à deux",
        "Communication du décideur",
        null,
        "Schürch",
        "Nelio",
        null,
        "Congo",
        null,
        null,
        "Qualité du décideur",
        null,
        "Roth",
        "Inge",
        null,
        "Norvège",
        null,
        null,
        "N. a.",
        null,
        "Zbinden",
        "Altin",
        null,
        "Turquie",
        null,
        null,
        "Chef du service finances / comptabilité",
        "False",
      ],
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
        "Nom de la société",
        "Vat code",
        "Clé CH",
        "Numéro d'identification de l'entreprise",
        "Company Book Number",
        "Siège social/succursale",
        "Date de la dernière mise à jour",
        "Forme juridique",
        "Statut juridique",
        "Statut de la société",
        "CRIF Id",
        "Début de l'activité commerciale",
        "Date de radiation",
        "Objet RH",
        "Objet RH Langue",
        "Nombre de filiales",
        "Province",
        "Canton",
        "Commune",
        "Localité",
        "Code Postal",
        "Rue",
        "Numéro de rue",
        "Adresse-Info complémentaire",
        "Langue d'annonce FOSC",
        "Numéro de téléphone",
        "Email",
        "URL du site web",
        "Fax number",
        "Mobile number",
        "Manager Title (1)",
        "Manager Nom de famille (1)",
        "Manager Prénom(s) / Raison sociale",
        "Manager Lieu d'origine (1)",
        "Manager Lieu d'origine (1)",
        "Manager fonction (1)",
        "Manager Autorisation de signature (1)",
        "Manager - Fonction opérationnelle (1)",
        "Manager Title (2)",
        "Manager Nom de famille (2)",
        "Manager Prénom(2) / Raison sociale",
        "Manager Lieu d'origine (2)",
        "Manager Lieu d'origine (2)",
        "Manager fonction (2)",
        "Manager Autorisation de signature (2)",
        "Manager - Fonction opérationnelle (2)",
        "Manager Title (3)",
        "Manager Nom de famille (3)",
        "Manager Prénom(3) / Raison sociale",
        "Manager Lieu d'origine (3)",
        "Manager Lieu d'origine (3)",
        "Manager fonction (3)",
        "Manager Autorisation de signature (3)",
        "Manager - Fonction opérationnelle (3)",
        "Manager Title (4)",
        "Manager Nom de famille (4)",
        "Manager Prénom(4) / Raison sociale",
        "Manager Lieu d'origine (4)",
        "Manager Lieu d'origine (4)",
        "Manager fonction (4)",
        "Manager Autorisation de signature (4)",
        "Manager - Fonction opérationnelle (4)",
        "Manager Title (5)",
        "Manager Nom de famille (5)",
        "Manager Prénom(5) / Raison sociale",
        "Manager Lieu d'origine (5)",
        "Manager Lieu d'origine (5)",
        "Manager fonction (5)",
        "Manager Autorisation de signature (5)",
        "Manager - Fonction opérationnelle (5)",
        "La société fait partie d'un groupe de sociétés",
        "Organe de révision",
        "Organe de révision - pays",
        "Organe de révision - canton",
        "Organe de révision - commune",
        "Organe de révision - Ville",
      ],
    ],
  },
  custom: {
    EN: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        null,
        "8453",
        0,
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        15000,
        "1010",
        null,
        15000,
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        1000000,
        "8490",
        2,
        1000000,
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        4800000,
        "9411",
        1,
        4800000,
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        4800000,
        "4310",
        4,
        4800000,
      ],
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Turnover (eur)",
        "Post code",
        "Employees",
        "Turnover (eur)",
        "Import partners",
        "Export partners",
      ],
    ],
    IT: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        null,
        "8453",
        0,
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        15000,
        "1010",
        null,
        15000,
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        1000000,
        "8490",
        2,
        1000000,
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        4800000,
        "9411",
        1,
        4800000,
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        4800000,
        "4310",
        4,
        4800000,
      ],
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Fatturato (eur)",
        "Cap",
        "Dipendenti",
        "Fatturato (eur)",
        "Import partners",
        "Export partners",
      ],
    ],
    DE: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        null,
        "8453",
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        15000,
        "1010",
        null,
        15000,
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        1000000,
        "8490",
        null,
        1000000,
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        4800000,
        "9411",
        "1 - 3",
        4800000,
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        4800000,
        "4310",
        "4 - 9",
        4800000,
      ],
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Umsatz (eur)",
        "PLZ",
        "Mitarbeiterbereich",
        "Umsatz (eur)",
        "Import partner",
        "Export partner",
      ],
    ],
    FR: [
      [
        "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
        "AUT",
        "Enriched Portfolio",
        "FN370583a",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        null,
        "8453",
      ],
      [
        "AT1718012_A33B981C-6DF7-4F61-9C9B-D5E8B74C266A",
        "AUT",
        "Enriched Portfolio",
        "FN508741z",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        15000,
        "1010",
        null,
        15000,
      ],
      [
        "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
        "AUT",
        "Enriched Portfolio",
        "FN283967z",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        1000000,
        "8490",
        null,
        1000000,
      ],
      [
        "CH30040164068_7BCDCA26-8BA0-44E3-BAD0-85CC34FDD387",
        "CHE",
        "Enriched Portfolio",
        "CHE1638960148",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        4800000,
        "9411",
        "1 - 3",
        4800000,
      ],
      [
        "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
        "CHE",
        "Enriched Portfolio",
        "CHE3151700178",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        4800000,
        "4310",
        "4 - 9",
        4800000,
      ],
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
        "Chiffre d'affaires (eur)",
        "Code Postal",
        "Secteur des employés",
        "Chiffre d'affaires (eur)",
        "Import partners",
        "Export partners",
      ],
    ],
  },
  groupActionsBase: [
    [
      "AT1160407_E9E43280-B978-441B-894D-C327C6B1B5C7",
      "AUT",
      "Enriched Portfolio",
      "FN370583a",
      "Prospect $(Prospect)$",
    ],
    [
      "AT186021_ECB1D917-0284-4945-BA97-34A20E971E63",
      "AUT",
      "Enriched Portfolio",
      "FN283967z",
      "Prospect $(Prospect)$",
    ],
    [
      "CH40040300089_8C1D26C5-54F5-4E79-A61B-AB2895567D43",
      "CHE",
      "Enriched Portfolio",
      "CHE3151700178",
      "Prospect $(Prospect)$",
    ],
    [
      "MargoId",
      "Country",
      "Portfolio associated",
      "Business identification number / Vat code / Company book number",
      "Company Portfolio Status",
      "Tags",
      "Amount",
      "Area Manager",
      "Sales",
      "Product",
    ],
  ],
};
export default cheIntPortfolioSchemas;
