const cheIntPortfolioSchemas = {
  baseTemplate: {
    EN: [
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    IT: [
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    DE: [
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    FR: [
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
      ],
    ],
  },
  marketingTemplate: {
    EN: [
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Legacy CH Number",
        "Business identification number",
        "Company Book Number",
        "Office type",
        "Last update date",
        "Legal form group",
        "Legal form",
        "Company status",
        "CRIF Id",
        "Incorporation date",
        "End date",
        "Purpose",
        "Purpose - language",
        "Number of Local Units",
        "Province",
        "Canton",
        "Municipality",
        "Town",
        "Post code",
        "Street",
        "Housenumber",
        "Address-additional info",
        "Official Language of SOGC",
        "Phone number",
        "Email",
        "Website URL",
        "Fax number",
        "Mobile number",
        "Manager title (1)",
        "Manager surname (1)",
        "Manager first name / Company name (1)",
        "Manager Year of Birth (1)",
        "Manager origin (1)",
        "Manager function (1)",
        "Manager function - authority to sign (1)",
        "Manager - operative function (1)",
        "Manager title (2)",
        "Manager surname (2)",
        "Manager first name / Company name (2)",
        "Manager Year of Birth (2)",
        "Manager origin (2)",
        "Manager function (2)",
        "Manager function - authority to sign (2)",
        "Manager - operative function (2)",
        "Manager title (3)",
        "Manager surname (3)",
        "Manager first name / Company name (3)",
        "Manager Year of Birth (3)",
        "Manager origin (3)",
        "Manager function (3)",
        "Manager function - authority to sign (3)",
        "Manager - operative function (3)",
        "Manager title (4)",
        "Manager surname (4)",
        "Manager first name / Company name (4)",
        "Manager Year of Birth (4)",
        "Manager origin (4)",
        "Manager function (4)",
        "Manager function - authority to sign (4)",
        "Manager - operative function (4)",
        "Manager title (5)",
        "Manager surname (5)",
        "Manager first name / Company name (5)",
        "Manager Year of Birth (5)",
        "Manager origin (5)",
        "Manager function (5)",
        "Manager function - authority to sign (5)",
        "Manager - operative function (5)",
        "Auditing company - Company belongs to a Company group",
        "Auditing company name",
        "Auditing company - Country",
        "Auditing company - Canton",
        "Auditing company - Municipality",
        "Auditing company - City",
      ],
    ],
    IT: [
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Ragione Sociale",
        "Vat code",
        "CH Key",
        "Identificativo Azienda",
        "Company Book Number",
        "Tipo di sede",
        "Data ultimo aggiornamento",
        "Forma legale",
        "Forma legale dettagliata",
        "Stato impresa",
        "CRIF Id",
        "Data di costituzione",
        "Data cessazione",
        "Descrizione attività",
        "Descrizione attività - Lingua",
        "Numero unità locali",
        "Province",
        "Cantone",
        "Città metropolitana",
        "Città",
        "Cap",
        "Indirizzo",
        "Civico",
        "Indirizzo - Ulteriori informazioni",
        "Lingua del messaggio SOGC",
        "Numero di telefono",
        "Email",
        "Sito web",
        "Fax number",
        "Mobile number",
        "Titolo esponente (1)",
        "Nome esponente (1)",
        "Cognome / Denominazione esponente (1)",
        "Anno di nascita (1)",
        "Nazionalità esponente (1)",
        "Carica esponente (1)",
        "Autorizzazione a firmare esponente (1)",
        "Funzione operativa esponente (1)",
        "Titolo esponente (2)",
        "Nome esponente (2)",
        "Cognome / Denominazione esponente (2)",
        "Anno di nascita (2)",
        "Nazionalità esponente (2)",
        "Carica esponente (2)",
        "Autorizzazione a firmare esponente (2)",
        "Funzione operativa esponente (2)",
        "Titolo esponente (3)",
        "Nome esponente (3)",
        "Cognome / Denominazione esponente (3)",
        "Anno di nascita (3)",
        "Nazionalità esponente (3)",
        "Carica esponente (3)",
        "Autorizzazione a firmare esponente (3)",
        "Funzione operativa esponente (3)",
        "Titolo esponente (4)",
        "Nome esponente (4)",
        "Cognome / Denominazione esponente (4)",
        "Anno di nascita (4)",
        "Nazionalità esponente (4)",
        "Carica esponente (4)",
        "Autorizzazione a firmare esponente (4)",
        "Funzione operativa esponente (4)",
        "Titolo esponente (5)",
        "Nome esponente (5)",
        "Cognome / Denominazione esponente (5)",
        "Anno di nascita (5)",
        "Nazionalità esponente (5)",
        "Carica esponente (5)",
        "Autorizzazione a firmare esponente (5)",
        "Funzione operativa esponente (5)",
        "Appartenenza ad un gruppo",
        "Società di revisione",
        "Società di revisione - Stato",
        "Società di revisione - Cantone",
        "Società di revisione - Città metropolitana",
        "Società di revisione - Città",
      ],
    ],
    DE: [
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Firmenname",
        "UID-Nummer / MWST-Nr.",
        "CH Key",
        "Unternehmens-Identifikationsnummer",
        "Firmenbuchnummer",
        "Hauptsitz/Zweigniederlassung",
        "Datum des letzten Updates",
        "Rechtsform",
        "Rechtsstatus",
        "Firmenstatus",
        "CRIF Id",
        "Beginn Geschäftstätigkeit",
        "Löschdatum",
        "HR-Zweck",
        "HR-Zweck Sprache",
        "Anzahl der Filialen",
        "Province",
        "Kanton",
        "Gemeinde",
        "Ort",
        "PLZ",
        "Strasse",
        "Hausnummer",
        "Adresse-Zusatzinfo",
        "SHAB-Meldungssprache",
        "Telefonnummer",
        "Email",
        "Website URL",
        "Faxnummer",
        "Handynummer",
        "Manager Title (1)",
        "Manager Nachname (1)",
        "Manager Vorname(n) / Firmenname",
        "Manager Year of Birth (1)",
        "Manager Heimatort (1)",
        "Manager Funktion (1)",
        "Manager Unterschriftsberechtigung (1)",
        "Manager – Operative Funktion (1)",
        "Manager Title (2)",
        "Manager Nachname (2)",
        "Manager Vorname(2) / Firmenname",
        "Manager Year of Birth (2)",
        "Manager Heimatort (2)",
        "Manager Funktion (2)",
        "Manager Unterschriftsberechtigung (2)",
        "Manager – Operative Funktion (2)",
        "Manager Title (3)",
        "Manager Nachname (3)",
        "Manager Vorname(3) / Firmenname",
        "Manager Year of Birth (3)",
        "Manager Heimatort (3)",
        "Manager Funktion (3)",
        "Manager Unterschriftsberechtigung (3)",
        "Manager – Operative Funktion (3)",
        "Manager Title (4)",
        "Manager Nachname (4)",
        "Manager Vorname(4) / Firmenname",
        "Manager Year of Birth (4)",
        "Manager Heimatort (4)",
        "Manager Funktion (4)",
        "Manager Unterschriftsberechtigung (4)",
        "Manager – Operative Funktion (4)",
        "Manager Title (5)",
        "Manager Nachname (5)",
        "Manager Vorname(5) / Firmenname",
        "Manager Year of Birth (5)",
        "Manager Heimatort (5)",
        "Manager Funktion (5)",
        "Manager Unterschriftsberechtigung (5)",
        "Manager – Operative Funktion (5)",
        "Firma gehört zu Firmengruppe",
        "Revisionsstelle",
        "Revisionsstelle - Land",
        "Revisionsstelle - Kanton",
        "Revisionsstelle - Gemeinde",
        "Revisionsstelle - Ort",
      ],
    ],
    FR: [
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
        "Nom de la société",
        "Vat code",
        "Clé CH",
        "Numéro d'identification de l'entreprise",
        "Company Book Number",
        "Siège social/succursale",
        "Date de la dernière mise à jour",
        "Forme juridique",
        "Statut juridique",
        "Statut de la société",
        "CRIF Id",
        "Début de l'activité commerciale",
        "Date de radiation",
        "Objet RH",
        "Objet RH Langue",
        "Nombre de filiales",
        "Province",
        "Canton",
        "Commune",
        "Localité",
        "Code Postal",
        "Rue",
        "Numéro de rue",
        "Adresse-Info complémentaire",
        "Langue d'annonce FOSC",
        "Numéro de téléphone",
        "Email",
        "URL du site web",
        "Fax number",
        "Mobile number",
        "Manager Title (1)",
        "Manager Nom de famille (1)",
        "Manager Prénom(s) / Raison sociale",
        "Manager Lieu d'origine (1)",
        "Manager Lieu d'origine (1)",
        "Manager fonction (1)",
        "Manager Autorisation de signature (1)",
        "Manager - Fonction opérationnelle (1)",
        "Manager Title (2)",
        "Manager Nom de famille (2)",
        "Manager Prénom(2) / Raison sociale",
        "Manager Lieu d'origine (2)",
        "Manager Lieu d'origine (2)",
        "Manager fonction (2)",
        "Manager Autorisation de signature (2)",
        "Manager - Fonction opérationnelle (2)",
        "Manager Title (3)",
        "Manager Nom de famille (3)",
        "Manager Prénom(3) / Raison sociale",
        "Manager Lieu d'origine (3)",
        "Manager Lieu d'origine (3)",
        "Manager fonction (3)",
        "Manager Autorisation de signature (3)",
        "Manager - Fonction opérationnelle (3)",
        "Manager Title (4)",
        "Manager Nom de famille (4)",
        "Manager Prénom(4) / Raison sociale",
        "Manager Lieu d'origine (4)",
        "Manager Lieu d'origine (4)",
        "Manager fonction (4)",
        "Manager Autorisation de signature (4)",
        "Manager - Fonction opérationnelle (4)",
        "Manager Title (5)",
        "Manager Nom de famille (5)",
        "Manager Prénom(5) / Raison sociale",
        "Manager Lieu d'origine (5)",
        "Manager Lieu d'origine (5)",
        "Manager fonction (5)",
        "Manager Autorisation de signature (5)",
        "Manager - Fonction opérationnelle (5)",
        "La société fait partie d'un groupe de sociétés",
        "Organe de révision",
        "Organe de révision - pays",
        "Organe de révision - canton",
        "Organe de révision - commune",
        "Organe de révision - Ville",
      ],
    ],
  },
  completeTemplate: {
    EN: [
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Legacy CH Number",
        "Business identification number",
        "Company Book Number",
        "Office type",
        "Last update date",
        "Legal form group",
        "Legal form",
        "Company status",
        "CRIF Id",
        "Incorporation date",
        "End date",
        "Purpose",
        "Purpose - language",
        "Number of Local Units",
        "Province",
        "Canton",
        "Municipality",
        "Town",
        "Post code",
        "Street",
        "Housenumber",
        "Address-additional info",
        "Official Language of SOGC",
        "Latitude",
        "Longitude",
        "NOGA",
        "NOGA - Description",
        "NACE",
        "NACE - Description",
        "OENACE 2008",
        "OENACE 2008 - Description",
        "SIC",
        "SIC - Description",
        "Employee Range",
        "Employees",
        "Employee Trend",
        "Turnover Range",
        "Turnover",
        "Turnover Trend",
        "Phone number",
        "Email",
        "Website URL",
        "Fax number",
        "Mobile number",
        "Import partners",
        "Is import-oriented",
        "Is export-oriented",
        "Export partners",
        "Manager title (1)",
        "Manager surname (1)",
        "Manager first name / Company name (1)",
        "Manager Year of Birth (1)",
        "Manager origin (1)",
        "Manager function (1)",
        "Manager function - authority to sign (1)",
        "Manager - operative function (1)",
        "Manager title (2)",
        "Manager surname (2)",
        "Manager first name / Company name (2)",
        "Manager Year of Birth (2)",
        "Manager origin (2)",
        "Manager function (2)",
        "Manager function - authority to sign (2)",
        "Manager - operative function (2)",
        "Manager title (3)",
        "Manager surname (3)",
        "Manager first name / Company name (3)",
        "Manager Year of Birth (3)",
        "Manager origin (3)",
        "Manager function (3)",
        "Manager function - authority to sign (3)",
        "Manager - operative function (3)",
        "Manager title (4)",
        "Manager surname (4)",
        "Manager first name / Company name (4)",
        "Manager Year of Birth (4)",
        "Manager origin (4)",
        "Manager function (4)",
        "Manager function - authority to sign (4)",
        "Manager - operative function (4)",
        "Manager title (5)",
        "Manager surname (5)",
        "Manager first name / Company name (5)",
        "Manager Year of Birth (5)",
        "Manager origin (5)",
        "Manager function (5)",
        "Manager function - authority to sign (5)",
        "Manager - operative function (5)",
        "Auditing company - Company belongs to a Company group",
        "Auditing company name",
        "Auditing company - Country",
        "Auditing company - Canton",
        "Auditing company - Municipality",
        "Auditing company - City",
        "Investment assets",
        "Immaterial assets",
        "Property equipment",
        "Financial investments",
        "Current assets",
        "Inventories",
        "Receivables and other assets",
        "Securities",
        "Cash inhand balances with credit institutions",
        "Accruals",
        "Assets",
        "Equity",
        "Shareholders equity",
        "Capital reserves",
        "Profit reserves",
        "Accumulated profit loss",
        "Untaxed reserves",
        "Provisions",
        "Liabilities",
        "Liabilities accruals",
        "Total liabilities and equity",
        "Bank name (1)",
        "Bank name (2)",
        "Bank name (3)",
        "Bank name (4)",
        "Bank name (5)",
      ],
    ],
    IT: [
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Ragione Sociale",
        "Vat code",
        "CH Key",
        "Identificativo Azienda",
        "Company Book Number",
        "Tipo di sede",
        "Data ultimo aggiornamento",
        "Forma legale",
        "Forma legale dettagliata",
        "Stato impresa",
        "CRIF Id",
        "Data di costituzione",
        "Data cessazione",
        "Descrizione attività",
        "Descrizione attività - Lingua",
        "Numero unità locali",
        "Province",
        "Cantone",
        "Città metropolitana",
        "Città",
        "Cap",
        "Indirizzo",
        "Civico",
        "Indirizzo - Ulteriori informazioni",
        "Lingua del messaggio SOGC",
        "Latitude",
        "Longitude",
        "NOGA",
        "NOGA - Descrizione",
        "NACE",
        "NACE - Descrizione",
        "OENACE 2008",
        "OENACE 2008 - Descrizione",
        "SIC",
        "SIC - Descrizione",
        "Classe numero dipendenti",
        "Dipendenti",
        "Trend dipendenti",
        "Fatturato - Range",
        "Fatturato",
        "Trend fatturato",
        "Numero di telefono",
        "Email",
        "Sito web",
        "Fax number",
        "Mobile number",
        "Import partners",
        "Is import-oriented",
        "Export",
        "Export partners",
        "Titolo esponente (1)",
        "Nome esponente (1)",
        "Cognome / Denominazione esponente (1)",
        "Anno di nascita (1)",
        "Nazionalità esponente (1)",
        "Carica esponente (1)",
        "Autorizzazione a firmare esponente (1)",
        "Funzione operativa esponente (1)",
        "Titolo esponente (2)",
        "Nome esponente (2)",
        "Cognome / Denominazione esponente (2)",
        "Anno di nascita (2)",
        "Nazionalità esponente (2)",
        "Carica esponente (2)",
        "Autorizzazione a firmare esponente (2)",
        "Funzione operativa esponente (2)",
        "Titolo esponente (3)",
        "Nome esponente (3)",
        "Cognome / Denominazione esponente (3)",
        "Anno di nascita (3)",
        "Nazionalità esponente (3)",
        "Carica esponente (3)",
        "Autorizzazione a firmare esponente (3)",
        "Funzione operativa esponente (3)",
        "Titolo esponente (4)",
        "Nome esponente (4)",
        "Cognome / Denominazione esponente (4)",
        "Anno di nascita (4)",
        "Nazionalità esponente (4)",
        "Carica esponente (4)",
        "Autorizzazione a firmare esponente (4)",
        "Funzione operativa esponente (4)",
        "Titolo esponente (5)",
        "Nome esponente (5)",
        "Cognome / Denominazione esponente (5)",
        "Anno di nascita (5)",
        "Nazionalità esponente (5)",
        "Carica esponente (5)",
        "Autorizzazione a firmare esponente (5)",
        "Funzione operativa esponente (5)",
        "Appartenenza ad un gruppo",
        "Società di revisione",
        "Società di revisione - Stato",
        "Società di revisione - Cantone",
        "Società di revisione - Città metropolitana",
        "Società di revisione - Città",
        "Investment assets",
        "Immaterial assets",
        "Property equipment",
        "Financial investments",
        "Current assets",
        "Inventories",
        "Receivables and other assets",
        "Securities",
        "Cash inhand balances with credit institutions",
        "Accruals",
        "Assets",
        "Equity",
        "Shareholders equity",
        "Capital reserves",
        "Profit reserves",
        "Accumulated profit loss",
        "Untaxed reserves",
        "Provisions",
        "Liabilities",
        "Liabilities accruals",
        "Total liabilities and equity",
        "Banca (1)",
        "Banca (2)",
        "Banca (3)",
        "Banca (4)",
        "Banca (5)",
      ],
    ],
    DE: [
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Firmenname",
        "UID-Nummer / MWST-Nr.",
        "CH Key",
        "Unternehmens-Identifikationsnummer",
        "Firmenbuchnummer",
        "Hauptsitz/Zweigniederlassung",
        "Datum des letzten Updates",
        "Rechtsform",
        "Rechtsstatus",
        "Firmenstatus",
        "CRIF Id",
        "Beginn Geschäftstätigkeit",
        "Löschdatum",
        "HR-Zweck",
        "HR-Zweck Sprache",
        "Anzahl der Filialen",
        "Province",
        "Kanton",
        "Gemeinde",
        "Ort",
        "PLZ",
        "Strasse",
        "Hausnummer",
        "Adresse-Zusatzinfo",
        "SHAB-Meldungssprache",
        "Latitude",
        "Longitude",
        "NOGA",
        "NOGA - Beschreibung",
        "NACE",
        "NACE - Beschreibung",
        "OENACE 2008",
        "OENACE 2008 - Beschreibung",
        "SIC",
        "SIC - Beschreibung",
        "Mitarbeiterbereich",
        "Anzahl Mitarbeiter gesamt",
        "Mitarbeitertrend",
        "Umsatzbereich",
        "Umsatz",
        "Umsatztrend",
        "Telefonnummer",
        "Email",
        "Website URL",
        "Faxnummer",
        "Handynummer",
        "Import partner",
        "Ist Importeur",
        "Ist Exporteur",
        "Export partner",
        "Manager Title (1)",
        "Manager Nachname (1)",
        "Manager Vorname(n) / Firmenname",
        "Manager Year of Birth (1)",
        "Manager Heimatort (1)",
        "Manager Funktion (1)",
        "Manager Unterschriftsberechtigung (1)",
        "Manager – Operative Funktion (1)",
        "Manager Title (2)",
        "Manager Nachname (2)",
        "Manager Vorname(2) / Firmenname",
        "Manager Year of Birth (2)",
        "Manager Heimatort (2)",
        "Manager Funktion (2)",
        "Manager Unterschriftsberechtigung (2)",
        "Manager – Operative Funktion (2)",
        "Manager Title (3)",
        "Manager Nachname (3)",
        "Manager Vorname(3) / Firmenname",
        "Manager Year of Birth (3)",
        "Manager Heimatort (3)",
        "Manager Funktion (3)",
        "Manager Unterschriftsberechtigung (3)",
        "Manager – Operative Funktion (3)",
        "Manager Title (4)",
        "Manager Nachname (4)",
        "Manager Vorname(4) / Firmenname",
        "Manager Year of Birth (4)",
        "Manager Heimatort (4)",
        "Manager Funktion (4)",
        "Manager Unterschriftsberechtigung (4)",
        "Manager – Operative Funktion (4)",
        "Manager Title (5)",
        "Manager Nachname (5)",
        "Manager Vorname(5) / Firmenname",
        "Manager Year of Birth (5)",
        "Manager Heimatort (5)",
        "Manager Funktion (5)",
        "Manager Unterschriftsberechtigung (5)",
        "Manager – Operative Funktion (5)",
        "Firma gehört zu Firmengruppe",
        "Revisionsstelle",
        "Revisionsstelle - Land",
        "Revisionsstelle - Kanton",
        "Revisionsstelle - Gemeinde",
        "Revisionsstelle - Ort",
        "Anlagevermögen",
        "Immaterielle Vermögenswerte",
        "Sachanlagevermögen",
        "Finanzanlagen",
        "Umlaufvermögen",
        "Bestand",
        "Forderungen und sonstige Vermögenswerte",
        "Sicherheiten",
        "Kassenbestand bei Kreditinstituten",
        "Rückstellungen",
        "Aktiva",
        "Eigenkapital",
        "Eigenkapital der Aktionäre",
        "Kapitalrücklagen",
        "Gewinnrücklagen",
        "Gewinn und Verlust",
        "Unversteuerte Rücklagen",
        "Rückstellungen",
        "Passiva",
        "Rückstellungen für Verbindlichkeiten",
        "Gesamtkapital",
        "Bank name (1)",
        "Bank name (2)",
        "Bank name (3)",
        "Bank name (4)",
        "Bank name (5)",
      ],
    ],
    FR: [
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
        "Nom de la société",
        "Vat code",
        "Clé CH",
        "Numéro d'identification de l'entreprise",
        "Company Book Number",
        "Siège social/succursale",
        "Date de la dernière mise à jour",
        "Forme juridique",
        "Statut juridique",
        "Statut de la société",
        "CRIF Id",
        "Début de l'activité commerciale",
        "Date de radiation",
        "Objet RH",
        "Objet RH Langue",
        "Nombre de filiales",
        "Province",
        "Canton",
        "Commune",
        "Localité",
        "Code Postal",
        "Rue",
        "Numéro de rue",
        "Adresse-Info complémentaire",
        "Langue d'annonce FOSC",
        "Latitude",
        "Longitude",
        "NOGA",
        "NOGA - description",
        "NACE",
        "NACE - description",
        "OENACE 2008",
        "OENACE 2008 - description",
        "SIC",
        "SIC - description",
        "Secteur des employés",
        "Nombre total d'employés",
        "Tendance des effectifs",
        "Domaine du chiffre d'affaires",
        "Chiffre d'affaires",
        "Tendance du chiffre d'affaires",
        "Numéro de téléphone",
        "Email",
        "URL du site web",
        "Fax number",
        "Mobile number",
        "Import partners",
        "Is import-oriented",
        "Orienté vers l'exportation",
        "Export partners",
        "Manager Title (1)",
        "Manager Nom de famille (1)",
        "Manager Prénom(s) / Raison sociale",
        "Manager Lieu d'origine (1)",
        "Manager Lieu d'origine (1)",
        "Manager fonction (1)",
        "Manager Autorisation de signature (1)",
        "Manager - Fonction opérationnelle (1)",
        "Manager Title (2)",
        "Manager Nom de famille (2)",
        "Manager Prénom(2) / Raison sociale",
        "Manager Lieu d'origine (2)",
        "Manager Lieu d'origine (2)",
        "Manager fonction (2)",
        "Manager Autorisation de signature (2)",
        "Manager - Fonction opérationnelle (2)",
        "Manager Title (3)",
        "Manager Nom de famille (3)",
        "Manager Prénom(3) / Raison sociale",
        "Manager Lieu d'origine (3)",
        "Manager Lieu d'origine (3)",
        "Manager fonction (3)",
        "Manager Autorisation de signature (3)",
        "Manager - Fonction opérationnelle (3)",
        "Manager Title (4)",
        "Manager Nom de famille (4)",
        "Manager Prénom(4) / Raison sociale",
        "Manager Lieu d'origine (4)",
        "Manager Lieu d'origine (4)",
        "Manager fonction (4)",
        "Manager Autorisation de signature (4)",
        "Manager - Fonction opérationnelle (4)",
        "Manager Title (5)",
        "Manager Nom de famille (5)",
        "Manager Prénom(5) / Raison sociale",
        "Manager Lieu d'origine (5)",
        "Manager Lieu d'origine (5)",
        "Manager fonction (5)",
        "Manager Autorisation de signature (5)",
        "Manager - Fonction opérationnelle (5)",
        "La société fait partie d'un groupe de sociétés",
        "Organe de révision",
        "Organe de révision - pays",
        "Organe de révision - canton",
        "Organe de révision - commune",
        "Organe de révision - Ville",
        "Investment assets",
        "Immaterial assets",
        "Property equipment",
        "Financial investments",
        "Current assets",
        "Inventories",
        "Receivables and other assets",
        "Securities",
        "Cash inhand balances with credit institutions",
        "Accruals",
        "Assets",
        "Equity",
        "Shareholders equity",
        "Capital reserves",
        "Profit reserves",
        "Accumulated profit loss",
        "Untaxed reserves",
        "Provisions",
        "Liabilities",
        "Liabilities accruals",
        "Total liabilities and equity",
        "Bank name (1)",
        "Bank name (2)",
        "Bank name (3)",
        "Bank name (4)",
        "Bank name (5)",
      ],
    ],
  },
  customTemplate: {
    EN: [
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Turnover",
        "Post code",
        "Employees",
        "Turnover",
        "Import partners",
        "Export partners",
      ],
    ],
    IT: [
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Fatturato",
        "Cap",
        "Dipendenti",
        "Fatturato",
        "Import partners",
        "Export partners",
      ],
    ],
    DE: [
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Umsatz",
        "PLZ",
        "Mitarbeiterbereich",
        "Umsatz",
        "Import partner",
        "Export partner",
      ],
    ],
    FR: [
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
        "Chiffre d'affaires",
        "Code Postal",
        "Secteur des employés",
        "Chiffre d'affaires",
        "Import partners",
        "Export partners",
      ],
    ],
  },
  base: {
    EN: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Prospect $(Prospect)$",
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Prospect $(Prospect)$",
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Prospect $(Prospect)$",
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Prospect $(Prospect)$",
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Prospect $(Prospect)$",
      ],
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    IT: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Prospect $(Prospect)$",
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Prospect $(Prospect)$",
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Prospect $(Prospect)$",
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Prospect $(Prospect)$",
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Prospect $(Prospect)$",
      ],
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    DE: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Interessent $(Prospect)$",
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Interessent $(Prospect)$",
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Interessent $(Prospect)$",
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Interessent $(Prospect)$",
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Interessent $(Prospect)$",
      ],
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
    FR: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Perspective $(Prospect)$",
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Perspective $(Prospect)$",
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Perspective $(Prospect)$",
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Perspective $(Prospect)$",
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Perspective $(Prospect)$",
      ],
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
      ],
    ],
  },
  marketing: {
    EN: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "öko&more, Service- und DienstleistungsgmbH",
        "ATU66905977",
        null,
        null,
        "FN370583a",
        "Headquarter",
        null,
        "Limited liability company",
        "Limited liability company",
        "Active",
        "3286000064719317",
        "20-10-2011",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Sankt Johann im Saggautal",
        "8453",
        "Saggau",
        "19",
        null,
        null,
        null,
        null,
        null,
        null,
        "+43 664 4251966",
        "Mag.",
        "Poscharnegg-Kriebernegg",
        "Ulrike",
        1971,
        null,
        "managing director, CEO (chief executive officer)",
        null,
        null,
        "Mag.",
        "Scherübl",
        "Thomas",
        1971,
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärztliche Not- und Bereitschaftsdienst Errichtungsges.m.b.H.",
        "ATU74227534",
        null,
        null,
        "FN508741z",
        "Headquarter",
        null,
        "Limited liability company",
        "Limited liability company",
        "Active",
        "3557000088055547",
        "06-03-2019",
        null,
        null,
        null,
        1,
        "Wien",
        null,
        null,
        "Wien",
        "1010",
        "Stock-im-Eisen-Platz",
        "3",
        null,
        null,
        "+43 1 5139478-0",
        null,
        null,
        null,
        null,
        "Dr.",
        "Spitzauer",
        "Friedrich",
        1959,
        null,
        "managing director, CEO (chief executive officer)",
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Üllen Landmaschinenhandel GmbH",
        "ATU63018479",
        null,
        null,
        "FN283967z",
        "Headquarter",
        null,
        "Limited liability company",
        "Limited liability company",
        "Active",
        "3628000038109377",
        "25-09-2006",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Radkersburg Umgebung",
        "8490",
        "Sicheldorf",
        "1",
        null,
        null,
        "+43 3476 3248",
        "uellen@aon.at",
        null,
        "+43 3476 40792",
        null,
        null,
        "Üllen",
        "Thomas",
        1985,
        null,
        "managing director, CEO (chief executive officer)",
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Novartis AG",
        "CHE368377178",
        "CHE61446",
        "CHE5642522370",
        null,
        "Headquarter",
        "16-03-2023",
        "Limited company",
        "Limited company",
        "Active",
        "121001675697",
        "12-03-1996",
        null,
        "Zweck der Gesellschaft ist die Beteiligung an Unternehmen, die auf dem Gebiet der Gesundheit oder Ernährung tätig sind. Die Gesellschaft kann sich auch an Unternehmen der Biologie, Chemie, Physik, Informatik oder verwandter Gebiete beteiligen. Die Gesellschaft ist berechtigt, Liegenschaften und Immaterialgüterrechte im In- und Ausland zu erwerben, zu belasten, zu verwerten und zu verkaufen. Bei der Verfolgung des Gesellschaftszwecks streb die Gesellschaft die Schaffung von nachhaltigem Wert an.",
        "German",
        0,
        null,
        "Basel-Stadt",
        "Basel",
        "Basel",
        "4056",
        "Lichtstrasse",
        "35",
        null,
        "German",
        "+410388565455",
        null,
        "www.ziegler.com",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "True",
        "KPMG AG",
        "Switzerland",
        "BS",
        "2701",
        "Basel",
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Nestlé Suisse S.A.",
        "CHE499174867",
        "CHE93089",
        "CHE5906398267",
        null,
        "Headquarter",
        "19-10-2022",
        "Limited company",
        "Limited company",
        "Active",
        "121003794397",
        "09-01-1997",
        null,
        "Fabrication, vente et distribution de tous produits, essentiellement alimentaires, diététiques, pharmaceutiques, médicaux, cosmétiques et hygiéniques. Elle peut, sous n'importe quelle forme, principalement sur le marché suisse, fournir tous services et déployer toute activité, en particulier dans le domaine de l'alimentation humaine et animale, de la diététique, des soins aux nourrissons, de l'éducation, de la publicité, de la restauration, des produits pharmaceutiques, médicaux, cosmétiques et hygiéniques.",
        "French",
        0,
        null,
        "Vaud",
        "Vevey",
        "Vevey",
        "1800",
        "Entre deux Villes",
        null,
        null,
        "French",
        "+413693485984",
        "hermine76@schlatter.com",
        "www.kunz.com",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "True",
        "Ernst & Young SA",
        "Switzerland",
        "VD",
        "5586",
        "Lausanne",
      ],
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Legacy CH Number",
        "Business identification number",
        "Company Book Number",
        "Office type",
        "Last update date",
        "Legal form group",
        "Legal form",
        "Company status",
        "CRIF Id",
        "Incorporation date",
        "End date",
        "Purpose",
        "Purpose - language",
        "Number of Local Units",
        "Province",
        "Canton",
        "Municipality",
        "Town",
        "Post code",
        "Street",
        "Housenumber",
        "Address-additional info",
        "Official Language of SOGC",
        "Phone number",
        "Email",
        "Website URL",
        "Fax number",
        "Mobile number",
        "Manager title (1)",
        "Manager surname (1)",
        "Manager first name / Company name (1)",
        "Manager Year of Birth (1)",
        "Manager origin (1)",
        "Manager function (1)",
        "Manager function - authority to sign (1)",
        "Manager - operative function (1)",
        "Manager title (2)",
        "Manager surname (2)",
        "Manager first name / Company name (2)",
        "Manager Year of Birth (2)",
        "Manager origin (2)",
        "Manager function (2)",
        "Manager function - authority to sign (2)",
        "Manager - operative function (2)",
        "Manager title (3)",
        "Manager surname (3)",
        "Manager first name / Company name (3)",
        "Manager Year of Birth (3)",
        "Manager origin (3)",
        "Manager function (3)",
        "Manager function - authority to sign (3)",
        "Manager - operative function (3)",
        "Manager title (4)",
        "Manager surname (4)",
        "Manager first name / Company name (4)",
        "Manager Year of Birth (4)",
        "Manager origin (4)",
        "Manager function (4)",
        "Manager function - authority to sign (4)",
        "Manager - operative function (4)",
        "Manager title (5)",
        "Manager surname (5)",
        "Manager first name / Company name (5)",
        "Manager Year of Birth (5)",
        "Manager origin (5)",
        "Manager function (5)",
        "Manager function - authority to sign (5)",
        "Manager - operative function (5)",
        "Auditing company - Company belongs to a Company group",
        "Auditing company name",
        "Auditing company - Country",
        "Auditing company - Canton",
        "Auditing company - Municipality",
        "Auditing company - City",
      ],
    ],
    IT: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "öko&more, Service- und DienstleistungsgmbH",
        "ATU66905977",
        null,
        null,
        "FN370583a",
        "Sede centrale",
        null,
        "Società a garanzia limitata",
        "Società a garanzia limitata",
        "Attivo",
        "3286000064719317",
        "20-10-2011",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Sankt Johann im Saggautal",
        "8453",
        "Saggau",
        "19",
        null,
        null,
        null,
        null,
        null,
        null,
        "+43 664 4251966",
        "Mag.",
        "Poscharnegg-Kriebernegg",
        "Ulrike",
        1971,
        null,
        "Geschäftsführer",
        null,
        null,
        "Mag.",
        "Scherübl",
        "Thomas",
        1971,
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärztliche Not- und Bereitschaftsdienst Errichtungsges.m.b.H.",
        "ATU74227534",
        null,
        null,
        "FN508741z",
        "Sede centrale",
        null,
        "Società a garanzia limitata",
        "Società a garanzia limitata",
        "Attivo",
        "3557000088055547",
        "06-03-2019",
        null,
        null,
        null,
        1,
        "Wien",
        null,
        null,
        "Wien",
        "1010",
        "Stock-im-Eisen-Platz",
        "3",
        null,
        null,
        "+43 1 5139478-0",
        null,
        null,
        null,
        null,
        "Dr.",
        "Spitzauer",
        "Friedrich",
        1959,
        null,
        "Geschäftsführer",
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Üllen Landmaschinenhandel GmbH",
        "ATU63018479",
        null,
        null,
        "FN283967z",
        "Sede centrale",
        null,
        "Società a garanzia limitata",
        "Società a garanzia limitata",
        "Attivo",
        "3628000038109377",
        "25-09-2006",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Radkersburg Umgebung",
        "8490",
        "Sicheldorf",
        "1",
        null,
        null,
        "+43 3476 3248",
        "uellen@aon.at",
        null,
        "+43 3476 40792",
        null,
        null,
        "Üllen",
        "Thomas",
        1985,
        null,
        "Geschäftsführer",
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Novartis AG",
        "CHE368377178",
        "CHE61446",
        "CHE5642522370",
        null,
        "Sede centrale",
        "16-03-2023",
        "Società anonima",
        "Società anonima",
        "Attivo",
        "121001675697",
        "12-03-1996",
        null,
        "Zweck der Gesellschaft ist die Beteiligung an Unternehmen, die auf dem Gebiet der Gesundheit oder Ernährung tätig sind. Die Gesellschaft kann sich auch an Unternehmen der Biologie, Chemie, Physik, Informatik oder verwandter Gebiete beteiligen. Die Gesellschaft ist berechtigt, Liegenschaften und Immaterialgüterrechte im In- und Ausland zu erwerben, zu belasten, zu verwerten und zu verkaufen. Bei der Verfolgung des Gesellschaftszwecks streb die Gesellschaft die Schaffung von nachhaltigem Wert an.",
        "Tedesco",
        0,
        null,
        "Basel-Stadt",
        "Basel",
        "Basel",
        "4056",
        "Lichtstrasse",
        "35",
        null,
        "Tedesco",
        "+410388565455",
        null,
        "www.ziegler.com",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "True",
        "KPMG AG",
        "Svizzera",
        "BS",
        "2701",
        "Basel",
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Nestlé Suisse S.A.",
        "CHE499174867",
        "CHE93089",
        "CHE5906398267",
        null,
        "Sede centrale",
        "19-10-2022",
        "Società anonima",
        "Società anonima",
        "Attivo",
        "121003794397",
        "09-01-1997",
        null,
        "Fabrication, vente et distribution de tous produits, essentiellement alimentaires, diététiques, pharmaceutiques, médicaux, cosmétiques et hygiéniques. Elle peut, sous n'importe quelle forme, principalement sur le marché suisse, fournir tous services et déployer toute activité, en particulier dans le domaine de l'alimentation humaine et animale, de la diététique, des soins aux nourrissons, de l'éducation, de la publicité, de la restauration, des produits pharmaceutiques, médicaux, cosmétiques et hygiéniques.",
        "Francese",
        0,
        null,
        "Vaud",
        "Vevey",
        "Vevey",
        "1800",
        "Entre deux Villes",
        null,
        null,
        "Francese",
        "+413693485984",
        "hermine76@schlatter.com",
        "www.kunz.com",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "True",
        "Ernst & Young SA",
        "Svizzera",
        "VD",
        "5586",
        "Lausanne",
      ],
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Ragione Sociale",
        "Vat code",
        "CH Key",
        "Identificativo Azienda",
        "Company Book Number",
        "Tipo di sede",
        "Data ultimo aggiornamento",
        "Forma legale",
        "Forma legale dettagliata",
        "Stato impresa",
        "CRIF Id",
        "Data di costituzione",
        "Data cessazione",
        "Descrizione attività",
        "Descrizione attività - Lingua",
        "Numero unità locali",
        "Province",
        "Cantone",
        "Città metropolitana",
        "Città",
        "Cap",
        "Indirizzo",
        "Civico",
        "Indirizzo - Ulteriori informazioni",
        "Lingua del messaggio SOGC",
        "Numero di telefono",
        "Email",
        "Sito web",
        "Fax number",
        "Mobile number",
        "Titolo esponente (1)",
        "Nome esponente (1)",
        "Cognome / Denominazione esponente (1)",
        "Anno di nascita (1)",
        "Nazionalità esponente (1)",
        "Carica esponente (1)",
        "Autorizzazione a firmare esponente (1)",
        "Funzione operativa esponente (1)",
        "Titolo esponente (2)",
        "Nome esponente (2)",
        "Cognome / Denominazione esponente (2)",
        "Anno di nascita (2)",
        "Nazionalità esponente (2)",
        "Carica esponente (2)",
        "Autorizzazione a firmare esponente (2)",
        "Funzione operativa esponente (2)",
        "Titolo esponente (3)",
        "Nome esponente (3)",
        "Cognome / Denominazione esponente (3)",
        "Anno di nascita (3)",
        "Nazionalità esponente (3)",
        "Carica esponente (3)",
        "Autorizzazione a firmare esponente (3)",
        "Funzione operativa esponente (3)",
        "Titolo esponente (4)",
        "Nome esponente (4)",
        "Cognome / Denominazione esponente (4)",
        "Anno di nascita (4)",
        "Nazionalità esponente (4)",
        "Carica esponente (4)",
        "Autorizzazione a firmare esponente (4)",
        "Funzione operativa esponente (4)",
        "Titolo esponente (5)",
        "Nome esponente (5)",
        "Cognome / Denominazione esponente (5)",
        "Anno di nascita (5)",
        "Nazionalità esponente (5)",
        "Carica esponente (5)",
        "Autorizzazione a firmare esponente (5)",
        "Funzione operativa esponente (5)",
        "Appartenenza ad un gruppo",
        "Società di revisione",
        "Società di revisione - Stato",
        "Società di revisione - Cantone",
        "Società di revisione - Città metropolitana",
        "Società di revisione - Città",
      ],
    ],
    DE: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "öko&more, Service- und DienstleistungsgmbH",
        "ATU66905977",
        null,
        null,
        "FN370583a",
        "Hauptsitz",
        null,
        "Gesellschaft mit beschränkter Haftung",
        "Gesellschaft mit beschränkter Haftung",
        "Aktiv",
        "3286000064719317",
        "20-10-2011",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Sankt Johann im Saggautal",
        "8453",
        "Saggau",
        "19",
        null,
        null,
        null,
        null,
        null,
        null,
        "+43 664 4251966",
        "Mag.",
        "Poscharnegg-Kriebernegg",
        "Ulrike",
        1971,
        null,
        "Geschäftsführer",
        null,
        null,
        "Mag.",
        "Scherübl",
        "Thomas",
        1971,
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärztliche Not- und Bereitschaftsdienst Errichtungsges.m.b.H.",
        "ATU74227534",
        null,
        null,
        "FN508741z",
        "Hauptsitz",
        null,
        "Gesellschaft mit beschränkter Haftung",
        "Gesellschaft mit beschränkter Haftung",
        "Aktiv",
        "3557000088055547",
        "06-03-2019",
        null,
        null,
        null,
        1,
        "Wien",
        null,
        null,
        "Wien",
        "1010",
        "Stock-im-Eisen-Platz",
        "3",
        null,
        null,
        "+43 1 5139478-0",
        null,
        null,
        null,
        null,
        "Dr.",
        "Spitzauer",
        "Friedrich",
        1959,
        null,
        "Geschäftsführer",
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Üllen Landmaschinenhandel GmbH",
        "ATU63018479",
        null,
        null,
        "FN283967z",
        "Hauptsitz",
        null,
        "Gesellschaft mit beschränkter Haftung",
        "Gesellschaft mit beschränkter Haftung",
        "Aktiv",
        "3628000038109377",
        "25-09-2006",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Radkersburg Umgebung",
        "8490",
        "Sicheldorf",
        "1",
        null,
        null,
        "+43 3476 3248",
        "uellen@aon.at",
        null,
        "+43 3476 40792",
        null,
        null,
        "Üllen",
        "Thomas",
        1985,
        null,
        "Geschäftsführer",
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Novartis AG",
        "CHE368377178",
        "CHE61446",
        "CHE5642522370",
        null,
        "Hauptsitz",
        "16-03-2023",
        "Aktiengesellschaft",
        "Gesellschaft mit beschränkter Haftung",
        "Aktiv",
        "121001675697",
        "12-03-1996",
        null,
        "Zweck der Gesellschaft ist die Beteiligung an Unternehmen, die auf dem Gebiet der Gesundheit oder Ernährung tätig sind. Die Gesellschaft kann sich auch an Unternehmen der Biologie, Chemie, Physik, Informatik oder verwandter Gebiete beteiligen. Die Gesellschaft ist berechtigt, Liegenschaften und Immaterialgüterrechte im In- und Ausland zu erwerben, zu belasten, zu verwerten und zu verkaufen. Bei der Verfolgung des Gesellschaftszwecks streb die Gesellschaft die Schaffung von nachhaltigem Wert an.",
        "Deutsch",
        0,
        null,
        "Basel-Stadt",
        "Basel",
        "Basel",
        "4056",
        "Lichtstrasse",
        "35",
        null,
        "Deutsch",
        "+410388565455",
        null,
        "www.ziegler.com",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "True",
        "KPMG AG",
        "Schweizerisch ",
        "BS",
        "2701",
        "Basel",
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Nestlé Suisse S.A.",
        "CHE499174867",
        "CHE93089",
        "CHE5906398267",
        null,
        "Hauptsitz",
        "19-10-2022",
        "Aktiengesellschaft",
        "Gesellschaft mit beschränkter Haftung",
        "Aktiv",
        "121003794397",
        "09-01-1997",
        null,
        "Fabrication, vente et distribution de tous produits, essentiellement alimentaires, diététiques, pharmaceutiques, médicaux, cosmétiques et hygiéniques. Elle peut, sous n'importe quelle forme, principalement sur le marché suisse, fournir tous services et déployer toute activité, en particulier dans le domaine de l'alimentation humaine et animale, de la diététique, des soins aux nourrissons, de l'éducation, de la publicité, de la restauration, des produits pharmaceutiques, médicaux, cosmétiques et hygiéniques.",
        "Französisch",
        0,
        null,
        "Vaud",
        "Vevey",
        "Vevey",
        "1800",
        "Entre deux Villes",
        null,
        null,
        "Französisch",
        "+413693485984",
        "hermine76@schlatter.com",
        "www.kunz.com",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "True",
        "Ernst & Young SA",
        "Schweizerisch ",
        "VD",
        "5586",
        "Lausanne",
      ],
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Firmenname",
        "UID-Nummer / MWST-Nr.",
        "CH Key",
        "Unternehmens-Identifikationsnummer",
        "Firmenbuchnummer",
        "Hauptsitz/Zweigniederlassung",
        "Datum des letzten Updates",
        "Rechtsform",
        "Rechtsstatus",
        "Firmenstatus",
        "CRIF Id",
        "Beginn Geschäftstätigkeit",
        "Löschdatum",
        "HR-Zweck",
        "HR-Zweck Sprache",
        "Anzahl der Filialen",
        "Province",
        "Kanton",
        "Gemeinde",
        "Ort",
        "PLZ",
        "Strasse",
        "Hausnummer",
        "Adresse-Zusatzinfo",
        "SHAB-Meldungssprache",
        "Telefonnummer",
        "Email",
        "Website URL",
        "Faxnummer",
        "Handynummer",
        "Manager Title (1)",
        "Manager Nachname (1)",
        "Manager Vorname(n) / Firmenname",
        "Manager Year of Birth (1)",
        "Manager Heimatort (1)",
        "Manager Funktion (1)",
        "Manager Unterschriftsberechtigung (1)",
        "Manager – Operative Funktion (1)",
        "Manager Title (2)",
        "Manager Nachname (2)",
        "Manager Vorname(2) / Firmenname",
        "Manager Year of Birth (2)",
        "Manager Heimatort (2)",
        "Manager Funktion (2)",
        "Manager Unterschriftsberechtigung (2)",
        "Manager – Operative Funktion (2)",
        "Manager Title (3)",
        "Manager Nachname (3)",
        "Manager Vorname(3) / Firmenname",
        "Manager Year of Birth (3)",
        "Manager Heimatort (3)",
        "Manager Funktion (3)",
        "Manager Unterschriftsberechtigung (3)",
        "Manager – Operative Funktion (3)",
        "Manager Title (4)",
        "Manager Nachname (4)",
        "Manager Vorname(4) / Firmenname",
        "Manager Year of Birth (4)",
        "Manager Heimatort (4)",
        "Manager Funktion (4)",
        "Manager Unterschriftsberechtigung (4)",
        "Manager – Operative Funktion (4)",
        "Manager Title (5)",
        "Manager Nachname (5)",
        "Manager Vorname(5) / Firmenname",
        "Manager Year of Birth (5)",
        "Manager Heimatort (5)",
        "Manager Funktion (5)",
        "Manager Unterschriftsberechtigung (5)",
        "Manager – Operative Funktion (5)",
        "Firma gehört zu Firmengruppe",
        "Revisionsstelle",
        "Revisionsstelle - Land",
        "Revisionsstelle - Kanton",
        "Revisionsstelle - Gemeinde",
        "Revisionsstelle - Ort",
      ],
    ],
    FR: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "öko&more, Service- und DienstleistungsgmbH",
        "ATU66905977",
        null,
        null,
        "FN370583a",
        "Siège social",
        null,
        "Société à responsabilité limitée",
        "Société à responsabilité limitée",
        "Actif",
        "3286000064719317",
        "20-10-2011",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Sankt Johann im Saggautal",
        "8453",
        "Saggau",
        "19",
        null,
        null,
        null,
        null,
        null,
        null,
        "+43 664 4251966",
        "Mag.",
        "Poscharnegg-Kriebernegg",
        "Ulrike",
        1971,
        null,
        "Geschäftsführer",
        null,
        null,
        "Mag.",
        "Scherübl",
        "Thomas",
        1971,
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ärztliche Not- und Bereitschaftsdienst Errichtungsges.m.b.H.",
        "ATU74227534",
        null,
        null,
        "FN508741z",
        "Siège social",
        null,
        "Société à responsabilité limitée",
        "Société à responsabilité limitée",
        "Actif",
        "3557000088055547",
        "06-03-2019",
        null,
        null,
        null,
        1,
        "Wien",
        null,
        null,
        "Wien",
        "1010",
        "Stock-im-Eisen-Platz",
        "3",
        null,
        null,
        "+43 1 5139478-0",
        null,
        null,
        null,
        null,
        "Dr.",
        "Spitzauer",
        "Friedrich",
        1959,
        null,
        "Geschäftsführer",
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Üllen Landmaschinenhandel GmbH",
        "ATU63018479",
        null,
        null,
        "FN283967z",
        "Siège social",
        null,
        "Société à responsabilité limitée",
        "Société à responsabilité limitée",
        "Actif",
        "3628000038109377",
        "25-09-2006",
        null,
        null,
        null,
        1,
        "Steiermark",
        null,
        null,
        "Radkersburg Umgebung",
        "8490",
        "Sicheldorf",
        "1",
        null,
        null,
        "+43 3476 3248",
        "uellen@aon.at",
        null,
        "+43 3476 40792",
        null,
        null,
        "Üllen",
        "Thomas",
        1985,
        null,
        "Geschäftsführer",
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Novartis AG",
        "CHE368377178",
        "CHE61446",
        "CHE5642522370",
        null,
        "Siège social",
        "16-03-2023",
        "Société anonyme",
        "Société à responsabilité limitée",
        "Actif",
        "121001675697",
        "12-03-1996",
        null,
        "Zweck der Gesellschaft ist die Beteiligung an Unternehmen, die auf dem Gebiet der Gesundheit oder Ernährung tätig sind. Die Gesellschaft kann sich auch an Unternehmen der Biologie, Chemie, Physik, Informatik oder verwandter Gebiete beteiligen. Die Gesellschaft ist berechtigt, Liegenschaften und Immaterialgüterrechte im In- und Ausland zu erwerben, zu belasten, zu verwerten und zu verkaufen. Bei der Verfolgung des Gesellschaftszwecks streb die Gesellschaft die Schaffung von nachhaltigem Wert an.",
        "Allemand",
        0,
        null,
        "Basel-Stadt",
        "Basel",
        "Basel",
        "4056",
        "Lichtstrasse",
        "35",
        null,
        "Allemand",
        "+410388565455",
        null,
        "www.ziegler.com",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "True",
        "KPMG AG",
        "Suisse",
        "BS",
        "2701",
        "Basel",
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Nestlé Suisse S.A.",
        "CHE499174867",
        "CHE93089",
        "CHE5906398267",
        null,
        "Siège social",
        "19-10-2022",
        "Société anonyme",
        "Société à responsabilité limitée",
        "Actif",
        "121003794397",
        "09-01-1997",
        null,
        "Fabrication, vente et distribution de tous produits, essentiellement alimentaires, diététiques, pharmaceutiques, médicaux, cosmétiques et hygiéniques. Elle peut, sous n'importe quelle forme, principalement sur le marché suisse, fournir tous services et déployer toute activité, en particulier dans le domaine de l'alimentation humaine et animale, de la diététique, des soins aux nourrissons, de l'éducation, de la publicité, de la restauration, des produits pharmaceutiques, médicaux, cosmétiques et hygiéniques.",
        "Français",
        0,
        null,
        "Vaud",
        "Vevey",
        "Vevey",
        "1800",
        "Entre deux Villes",
        null,
        null,
        "Français",
        "+413693485984",
        "hermine76@schlatter.com",
        "www.kunz.com",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "True",
        "Ernst & Young SA",
        "Suisse",
        "VD",
        "5586",
        "Lausanne",
      ],
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
        "Nom de la société",
        "Vat code",
        "Clé CH",
        "Numéro d'identification de l'entreprise",
        "Company Book Number",
        "Siège social/succursale",
        "Date de la dernière mise à jour",
        "Forme juridique",
        "Statut juridique",
        "Statut de la société",
        "CRIF Id",
        "Début de l'activité commerciale",
        "Date de radiation",
        "Objet RH",
        "Objet RH Langue",
        "Nombre de filiales",
        "Province",
        "Canton",
        "Commune",
        "Localité",
        "Code Postal",
        "Rue",
        "Numéro de rue",
        "Adresse-Info complémentaire",
        "Langue d'annonce FOSC",
        "Numéro de téléphone",
        "Email",
        "URL du site web",
        "Fax number",
        "Mobile number",
        "Manager Title (1)",
        "Manager Nom de famille (1)",
        "Manager Prénom(s) / Raison sociale",
        "Manager Lieu d'origine (1)",
        "Manager Lieu d'origine (1)",
        "Manager fonction (1)",
        "Manager Autorisation de signature (1)",
        "Manager - Fonction opérationnelle (1)",
        "Manager Title (2)",
        "Manager Nom de famille (2)",
        "Manager Prénom(2) / Raison sociale",
        "Manager Lieu d'origine (2)",
        "Manager Lieu d'origine (2)",
        "Manager fonction (2)",
        "Manager Autorisation de signature (2)",
        "Manager - Fonction opérationnelle (2)",
        "Manager Title (3)",
        "Manager Nom de famille (3)",
        "Manager Prénom(3) / Raison sociale",
        "Manager Lieu d'origine (3)",
        "Manager Lieu d'origine (3)",
        "Manager fonction (3)",
        "Manager Autorisation de signature (3)",
        "Manager - Fonction opérationnelle (3)",
        "Manager Title (4)",
        "Manager Nom de famille (4)",
        "Manager Prénom(4) / Raison sociale",
        "Manager Lieu d'origine (4)",
        "Manager Lieu d'origine (4)",
        "Manager fonction (4)",
        "Manager Autorisation de signature (4)",
        "Manager - Fonction opérationnelle (4)",
        "Manager Title (5)",
        "Manager Nom de famille (5)",
        "Manager Prénom(5) / Raison sociale",
        "Manager Lieu d'origine (5)",
        "Manager Lieu d'origine (5)",
        "Manager fonction (5)",
        "Manager Autorisation de signature (5)",
        "Manager - Fonction opérationnelle (5)",
        "La société fait partie d'un groupe de sociétés",
        "Organe de révision",
        "Organe de révision - pays",
        "Organe de révision - canton",
        "Organe de révision - commune",
        "Organe de révision - Ville",
      ],
    ],
  },
  custom: {
    EN: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        null,
        "8453",
        0,
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        15000,
        "1010",
        null,
        15000,
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        1000000,
        "8490",
        2,
        1000000,
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        45065568000,
        "4056",
        118700,
        45065568000,
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        88865280000,
        "1800",
        291000,
        88865280000,
      ],
      [
        "MargoId",
        "Country",
        "Portfolio associated",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Turnover (eur)",
        "Post code",
        "Employees",
        "Turnover (eur)",
        "Import partners",
        "Export partners",
      ],
    ],
    IT: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        null,
        "8453",
        0,
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        15000,
        "1010",
        null,
        15000,
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        1000000,
        "8490",
        2,
        1000000,
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        45065568000,
        "4056",
        118700,
        45065568000,
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        88865280000,
        "1800",
        291000,
        88865280000,
      ],
      [
        "MargoId",
        "Stato",
        "Portafoglio di appartenenza",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Fatturato (eur)",
        "Cap",
        "Dipendenti",
        "Fatturato (eur)",
        "Import partners",
        "Export partners",
      ],
    ],
    DE: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        null,
        "8453",
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        15000,
        "1010",
        null,
        15000,
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        1000000,
        "8490",
        null,
        1000000,
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        45065568000,
        "4056",
        "1000 +",
        45065568000,
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Interessent $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        88865280000,
        "1800",
        "1000 +",
        88865280000,
      ],
      [
        "MargoId",
        "Land",
        "Source Portfolio",
        "Unternehmens-Identifikatinosnummer / UID-Nummer / MWST-Nr. /  Firmenbuchnummer",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Umsatz (eur)",
        "PLZ",
        "Mitarbeiterbereich",
        "Umsatz (eur)",
        "Import partner",
        "Export partner",
      ],
    ],
    FR: [
      [
        "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
        "AUT",
        "Enriched Portfolio",
        "ATU66905977",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        null,
        "8453",
      ],
      [
        "AT1718012_E35B454E-562D-424B-9CE8-1A8285B9F3CF",
        "AUT",
        "Enriched Portfolio",
        "ATU74227534",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        15000,
        "1010",
        null,
        15000,
      ],
      [
        "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
        "AUT",
        "Enriched Portfolio",
        "ATU63018479",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        1000000,
        "8490",
        null,
        1000000,
      ],
      [
        "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
        "CHE",
        "Enriched Portfolio",
        "CHE5642522370",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        45065568000,
        "4056",
        "1000 +",
        45065568000,
      ],
      [
        "CH55001161421_30736F63-1B37-4DEC-9ECF-6B1773B1579C",
        "CHE",
        "Enriched Portfolio",
        "CHE5906398267",
        "Perspective $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        88865280000,
        "1800",
        "1000 +",
        88865280000,
      ],
      [
        "MargoId",
        "Pays",
        "Portefeuille de membres",
        "Business identification number / Vat code / Company book number",
        "Company Portfolio Status",
        "Tags",
        "Amount",
        "Area Manager",
        "Commercial",
        "Product",
        "Chiffre d'affaires (eur)",
        "Code Postal",
        "Secteur des employés",
        "Chiffre d'affaires (eur)",
        "Import partners",
        "Export partners",
      ],
    ],
  },
  groupActionsBase: [
    [
      "AT1160407_93415685-A07A-4BD4-9664-F4F271347A6A",
      "AUT",
      "Enriched Portfolio",
      "ATU66905977",
      "Prospect $(Prospect)$",
    ],
    [
      "AT186021_D4C88FDE-C599-42F3-8465-5944B15E929C",
      "AUT",
      "Enriched Portfolio",
      "ATU63018479",
      "Prospect $(Prospect)$",
    ],
    [
      "CH27030020612_A201BA60-BB2F-4699-83CA-A457FE85BA45",
      "CHE",
      "Enriched Portfolio",
      "CHE5642522370",
      "Prospect $(Prospect)$",
    ],
    [
      "MargoId",
      "Country",
      "Portfolio associated",
      "Business identification number / Vat code / Company book number",
      "Company Portfolio Status",
      "Tags",
      "Amount",
      "Area Manager",
      "Sales",
      "Product",
    ],
  ],
}; 
export default cheIntPortfolioSchemas;
