const czIntPortfolioSchemas = {
  baseTemplate: {
    CZ: [
      [
        "MargoId",
        "IČ",
        "Status company",
        "Tag",
        "Množství",
        "Area Manažer",
        "Obchodník",
        "Produkt",
      ],
    ],
    SK: [
      [
        "MargoId",
        "IČO",
        "Status company",
        "Tag",
        "Množstvo",
        "Oblastný manažér",
        "Obchodník",
        "Produkt",
      ],
    ],
    EN: [
      [
        "MargoId",
        "CompanyID/TaxId/VatId",
        "Status company",
        "Tag",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
    ],
  },
  marketingTemplate: {
    CZ: [
      [
        "MargoId",
        "IČ",
        "Status company",
        "Tag",
        "Množství",
        "Area Manažer",
        "Obchodník",
        "Produkt",
        "Název společnosti",
        "DIČ",
        "Daňové číslo",
        "Skupina právních forem",
        "Právní forma",
        "Stav",
        "Datum založení",
        "Stát",
        "Kraj",
        "Okres",
        "Město",
        "PSČ",
        "Adresa sídla",
        "Zeměpisná délka",
        "Zeměpisná šířka",
        "Distribuce Převažující činnosti (NACE)",
        "Popis distribuce Převažující činnosti (NACE)",
        "SIC",
        "Popis přiárního SIC",
        "Kategorie počtu zaměstnanců",
        "Trend počtu zaměstnanců",
        "Rok kategorie počtu zaměstnanců (CZ)",
        "Rok kategorie počtu zaměstnanců (SK)",
        "Kategorie obratu (CZ)",
        "Kategorie obratu (SK)",
        "Trend obratu",
        "Rok kategorie obratu (CZ)",
        "Rok kategorie obratu (SK) ",
        "Telefon",
        "Fax",
        "Web",
        "Email",
        "E-shop",
        "Facebook",
        "Státem vlastněná společnost",
        "Export",
        "Import",
        "Kontrolní a statutární orgány - Jméno / Název společnosti (1)",
        "Kontrolní a statutární orgány - Datum narození (1)",
        "Kontrolní a statutární orgány - Pozice (1)",
        "Kontrolní a statutární orgány - Platné od (1)",
        "Kontrolní a statutární orgány - Země (1)",
        "Kontrolní a statutární orgány - Jméno / Název společnosti (2)",
        "Kontrolní a statutární orgány - Datum narození (2)",
        "Kontrolní a statutární orgány - Pozice (2)",
        "Kontrolní a statutární orgány - Platné od (2)",
        "Kontrolní a statutární orgány - Země (2)",
        "Kontrolní a statutární orgány - Jméno / Název společnosti (3)",
        "Kontrolní a statutární orgány - Datum narození (3)",
        "Kontrolní a statutární orgány - Pozice (3)",
        "Kontrolní a statutární orgány - Platné od (3)",
        "Kontrolní a statutární orgány - Země (3)",
      ],
    ],
    SK: [
      [
        "MargoId",
        "IČO",
        "Status company",
        "Tag",
        "Množstvo",
        "Oblastný manažér",
        "Obchodník",
        "Produkt",
        "Názov spoločnosti",
        "IČ DPH",
        "DIČ",
        "Skupina právnych foriem",
        "Právna forma",
        "Stav",
        "Dátum založenia",
        "Krajina",
        "Kraj",
        "Okres",
        "Obec",
        "PSČ",
        "Adresa sídla",
        "Zemepisná dĺžka",
        "Zemepisná šírka",
        "Distribúcia Prevažujúcej činnosti (NACE)",
        "Popis distribúcia Prevažujúcej činnosti (NACE)",
        "SIC",
        "Popis primárneho SIC",
        "Kategória počtu zamestnancov",
        "Trend počtu zamestnancov",
        "Rok kategórie počtu zamestnancov (CZ)",
        "Rok kategórie počtu zamestnancov (SK)",
        "Kategória obratu (CZ)",
        "Kategória obratu (SK)",
        "Trend obratu",
        "Rok kategórie obratu (CZ)",
        "Rok kategórie obratu (SK)",
        "Telefón",
        "Fax",
        "Web",
        "Email",
        "E-shop",
        "Facebook",
        "Štátom vlastnená spoločnosť",
        "Export",
        "Import",
        "Kontrolné a štatutárne orgány - Meno / Názov spoločnosti (1)",
        "Kontrolné a štatutárne orgány - Dátum narodenia (1)",
        "Kontrolné a štatutárne orgány - Pozícia (1)",
        "Kontrolné a štatutárne orgány - Platné od (1)",
        "Kontrolné a štatutárne orgány - Krajina (1)",
        "Kontrolné a štatutárne orgány - Meno / Názov spoločnosti (2)",
        "Kontrolné a štatutárne orgány - Dátum narodenia (2)",
        "Kontrolné a štatutárne orgány - Pozícia (2)",
        "Kontrolné a štatutárne orgány - Platné od (2)",
        "Kontrolné a štatutárne orgány - Krajina (2)",
        "Kontrolné a štatutárne orgány - Meno / Názov spoločnosti (3)",
        "Kontrolné a štatutárne orgány - Dátum narodenia (3)",
        "Kontrolné a štatutárne orgány - Pozícia (3)",
        "Kontrolné a štatutárne orgány - Platné od (3)",
        "Kontrolné a štatutárne orgány - Krajina (3)",
      ],
    ],
    EN: [
      [
        "MargoId",
        "CompanyID/TaxId/VatId",
        "Status company",
        "Tag",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Tax code",
        "Legal forms group",
        "Legal form",
        "Status company",
        "Date of registration",
        "Country",
        "Region",
        "District",
        "City",
        "Zip code",
        "Address",
        "Longitude",
        "Latitude",
        "Prevailing activity (NACE)",
        "Description prevailing activity (NACE)",
        "Primary SIC",
        "Description primary SIC",
        "Range of employees count",
        "Employee trend",
        "Employees category year (CZ)",
        "Employees category year (SK)",
        "Turnover category (CZ)",
        "Turnover category (SK)",
        "Turnover trend",
        "Turnover category year (CZ)",
        "Turnover category year (SK)",
        "Phone number",
        "Fax",
        "Website URL",
        "Email",
        "Ecommerce",
        "Facebook",
        "State-owned company",
        "Export",
        "Import",
        "Supervisory board & statutory body - Name / business name (1)",
        "Supervisory board & statutory body - d. o. b. (1)",
        "Supervisory board & statutory body - Position (1)",
        "Supervisory board & statutory body - Valid From (1)",
        "Supervisory board & statutory body - Country (1)",
        "Supervisory board & statutory body - Name / business name (2)",
        "Supervisory board & statutory body - d. o. b. (2)",
        "Supervisory board & statutory body - Position (2)",
        "Supervisory board & statutory body - Valid From (2)",
        "Supervisory board & statutory body - Country (2)",
        "Supervisory board & statutory body - Name / business name (3)",
        "Supervisory board & statutory body - d. o. b. (3)",
        "Supervisory board & statutory body - Position (3)",
        "Supervisory board & statutory body - Valid From (3)",
        "Supervisory board & statutory body - Country (3)",
      ],
    ],
  },
  completeTemplate: {
    CZ: [
      [
        "MargoId",
        "IČ",
        "Status company",
        "Tag",
        "Množství",
        "Area Manažer",
        "Obchodník",
        "Produkt",
        "Název společnosti",
        "DIČ",
        "Daňové číslo",
        "Skupina právních forem",
        "Právní forma",
        "Stav",
        "Datum založení",
        "Základní kapitál",
        "Vznik provozování živností",
        "Datum výmazu",
        "Počet poboček",
        "Stát",
        "Kraj",
        "Okres",
        "Město",
        "PSČ",
        "Adresa sídla",
        "Zeměpisná délka",
        "Zeměpisná šířka",
        "Distribuce Převažující činnosti (NACE)",
        "Popis distribuce Převažující činnosti (NACE)",
        "SIC",
        "Popis přiárního SIC",
        "Kategorie počtu zaměstnanců",
        "Trend počtu zaměstnanců",
        "Rok kategorie počtu zaměstnanců (CZ)",
        "Rok kategorie počtu zaměstnanců (SK)",
        "Kategorie obratu (CZ)",
        "Kategorie obratu (SK)",
        "Trend obratu",
        "Rok kategorie obratu (CZ)",
        "Rok kategorie obratu (SK) ",
        "Tržby",
        "Zisk / ztráta",
        "Aktiva celkem",
        "Období od (1)",
        "Období od (2)",
        "Období od (3)",
        "Období do (1)",
        "Období do (2)",
        "Období do (3)",
        "Tržby (1)",
        "Tržby (2)",
        "Tržby (3)",
        "Provozní náklady (1)",
        "Provozní náklady (2)",
        "Provozní náklady (3)",
        "Výsledek hospodaření z finanční činnosti (1)",
        "Výsledek hospodaření z finanční činnosti (2)",
        "Výsledek hospodaření z finanční činnosti (3)",
        "Zisk / ztráta před zdaněním (1)",
        "Zisk / ztráta před zdaněním (2)",
        "Zisk / ztráta před zdaněním (3)",
        "Zisk / ztráta po zdanění (1)",
        "Zisk / ztráta po zdanění (2)",
        "Zisk / ztráta po zdanění (3)",
        "EBITDA (1)",
        "EBITDA (2)",
        "EBITDA (3)",
        "Cash flow (1)",
        "Cash flow (2)",
        "Cash flow (3)",
        "Aktiva (1)",
        "Aktiva (2)",
        "Aktiva (3)",
        "Dlouhodobá aktiva (1)",
        "Dlouhodobá aktiva (2)",
        "Dlouhodobá aktiva (3)",
        "Krátkodobá aktiva (1)",
        "Krátkodobá aktiva (2)",
        "Krátkodobá aktiva (3)",
        "Dluhy - PP a PE (1)",
        "Dluhy - PP a PE (2)",
        "Dluhy - PP a PE (3)",
        "Dlouhodobé dluhy (1)",
        "Dlouhodobé dluhy (2)",
        "Dlouhodobé dluhy (3)",
        "Krátkodobé dluhy (1)",
        "Krátkodobé dluhy (2)",
        "Krátkodobé dluhy (3)",
        "Celkové pohledávky (1)",
        "Celkové pohledávky (2)",
        "Celkové pohledávky (3)",
        "Krátkodobé pohledávky (1)",
        "Krátkodobé pohledávky (2)",
        "Krátkodobé pohledávky (3)",
        "Krátkodobé pohledávky z OS (1)",
        "Krátkodobé pohledávky z OS (2)",
        "Krátkodobé pohledávky z OS (3)",
        "Celkové závazky (1)",
        "Celkové závazky (2)",
        "Celkové závazky (3)",
        "Krátkodobé závazky (1)",
        "Krátkodobé závazky (2)",
        "Krátkodobé závazky (3)",
        "Krátkodobé závazky z OS (1)",
        "Krátkodobé závazky z OS (2)",
        "Krátkodobé závazky z OS (3)",
        "Vlastní kapitál (1)",
        "Vlastní kapitál (2)",
        "Vlastní kapitál (3)",
        "Rentabilita vlastního kapitálu (1)",
        "Rentabilita vlastního kapitálu (2)",
        "Rentabilita vlastního kapitálu (3)",
        "Rentabilita aktiv (1)",
        "Rentabilita aktiv (2)",
        "Rentabilita aktiv (3)",
        "Provozní rentabilita tržeb (1)",
        "Provozní rentabilita tržeb (2)",
        "Provozní rentabilita tržeb (3)",
        "Bankovní úvěry (1)",
        "Bankovní úvěry (2)",
        "Bankovní úvěry (3)",
        "Telefon",
        "Fax",
        "Web",
        "Email",
        "E-shop",
        "Facebook",
        "Twitter",
        "Linked-In",
        "Státem vlastněná společnost",
        "Dceřiná společnost státu",
        "Přidružená společnosti státu",
        "Vítěz veřejné zakázky",
        "Vyhrané veřejné zakázky (poslední 3R)",
        "Hodnota veřejných zakázek vyhrála (poslední 3R) ",
        "Příjemce dotací",
        "Získané dotace (poslední 3r)",
        "Hodonta získaných dotací (poslední 3r)",
        "Počet regsitrovaných vozidel",
        "Export",
        "Exportní partner",
        "Import",
        "Importní partner",
        "Kontrolní a statutární orgány - Jméno / Název společnosti (1)",
        "Kontrolní a statutární orgány - IČO (1)",
        "Kontrolní a statutární orgány - Datum narození (1)",
        "Kontrolní a statutární orgány - Pozice (1)",
        "Kontrolní a statutární orgány - Platné od (1)",
        "Kontrolní a statutární orgány - Země (1)",
        "Kontrolní a statutární orgány - Věk (1)",
        "Kontrolní a statutární orgány - Jméno / Název společnosti (2)",
        "Kontrolní a statutární orgány - IČO (2)",
        "Kontrolní a statutární orgány - Datum narození (2)",
        "Kontrolní a statutární orgány - Pozice (2)",
        "Kontrolní a statutární orgány - Platné od (2)",
        "Kontrolní a statutární orgány - Země (2)",
        "Kontrolní a statutární orgány - Věk (2)",
        "Kontrolní a statutární orgány - Jméno / Název společnosti (3)",
        "Kontrolní a statutární orgány - IČO (3)",
        "Kontrolní a statutární orgány - Datum narození (3)",
        "Kontrolní a statutární orgány - Pozice (3)",
        "Kontrolní a statutární orgány - Platné od (3)",
        "Kontrolní a statutární orgány - Země (3)",
        "Kontrolní a statutární orgány - Věk (3)",
        "Vlastníci - Jméno / Název společnosti (1)",
        "Vlastníci - IČO (1)",
        "Vlastníci - Datum narození (1)",
        "Vlastníci - Pozice (1)",
        "Vlastníci - Podíl (%) (1)",
        "Vlastníci - Vklad (1)",
        "Vlastníci - Platné od (1)",
        "Vlastníci - Země (1)",
        "Vlastníci - Věk (1)",
        "Vlastníci - Jméno / Název společnosti (2)",
        "Vlastníci - IČO (2)",
        "Vlastníci - Datum narození (2)",
        "Vlastníci - Pozice (2)",
        "Vlastníci - Podíl (%) (2)",
        "Vlastníci - Vklad (2)",
        "Vlastníci - Platné od (2)",
        "Vlastníci - Země (2)",
        "Vlastníci - Věk (2)",
        "Vlastníci - Jméno / Název společnosti (3)",
        "Vlastníci - IČO (3)",
        "Vlastníci - Datum narození (3)",
        "Vlastníci - Pozice (3)",
        "Vlastníci - Podíl (%) (3)",
        "Vlastníci - Vklad (3)",
        "Vlastníci - Platné od (3)",
        "Vlastníci - Země (3)",
        "Vlastníci - Věk (3)",
        "Majetkové účasti ve společnostech - Název společnosti (1)",
        "Majetkové účasti ve společnostech - IČO (1)",
        "Majetkové účasti ve společnostech - Pozice (1)",
        "Majetkové účasti ve společnostech - Podíl (%) (1)",
        "Majetkové účasti ve společnostech - Vklad (1)",
        "Majetkové účasti ve společnostech - Platné od (1)",
        "Majetkové účasti ve společnostech - Země (1)",
        "Majetkové účasti ve společnostech - Název společnosti (2)",
        "Majetkové účasti ve společnostech - IČO (2)",
        "Majetkové účasti ve společnostech - Pozice (2)",
        "Majetkové účasti ve společnostech - Podíl (%) (2)",
        "Majetkové účasti ve společnostech - Vklad (2)",
        "Majetkové účasti ve společnostech - Platné od (2)",
        "Majetkové účasti ve společnostech - Země (2)",
        "Majetkové účasti ve společnostech - Název společnosti (3)",
        "Majetkové účasti ve společnostech - IČO (3)",
        "Majetkové účasti ve společnostech - Pozice (3)",
        "Majetkové účasti ve společnostech - Podíl (%) (3)",
        "Majetkové účasti ve společnostech - Vklad (3)",
        "Majetkové účasti ve společnostech - Platné od (3)",
        "Majetkové účasti ve společnostech - Země (3)",
        "Index CRIBIS",
        "Skupinový semafor CRIBIS",
        "Pravděpodobnost bankrotu (%)",
        "Úvěrová kapacita",
        "Volná krátkodobá úvěrová kapacita",
        "Stupeň rizika",
        "Finanční situace",
        "Ekonomicky spjatá skupina (ESS)",
      ],
    ],
    SK: [
      [
        "MargoId",
        "IČO",
        "Status company",
        "Tag",
        "Množstvo",
        "Oblastný manažér",
        "Obchodník",
        "Produkt",
        "Názov spoločnosti",
        "IČ DPH",
        "DIČ",
        "Skupina právnych foriem",
        "Právna forma",
        "Stav",
        "Dátum založenia",
        "Základné imanie",
        "Vznik prevádzkovania živností",
        "Dátum výmazu",
        "Počet pobočiek",
        "Krajina",
        "Kraj",
        "Okres",
        "Obec",
        "PSČ",
        "Adresa sídla",
        "Zemepisná dĺžka",
        "Zemepisná šírka",
        "Distribúcia Prevažujúcej činnosti (NACE)",
        "Popis distribúcia Prevažujúcej činnosti (NACE)",
        "SIC",
        "Popis primárneho SIC",
        "Kategória počtu zamestnancov",
        "Trend počtu zamestnancov",
        "Rok kategórie počtu zamestnancov (CZ)",
        "Rok kategórie počtu zamestnancov (SK)",
        "Kategória obratu (CZ)",
        "Kategória obratu (SK)",
        "Trend obratu",
        "Rok kategórie obratu (CZ)",
        "Rok kategórie obratu (SK)",
        "Tržby",
        "Zisk / strata",
        "Aktíva celkom",
        "Obdobie od (1)",
        "Obdobie od (2)",
        "Obdobie od (3)",
        "Obdobie do (1)",
        "Obdobie do (2)",
        "Obdobie do (3)",
        "Tržby (1)",
        "Tržby (2)",
        "Tržby (3)",
        "Prevádzkové náklady (1)",
        "Prevádzkové náklady (2)",
        "Prevádzkové náklady (3)",
        "Výsledok hospodárenia z finančnej činnosti (1)",
        "Výsledok hospodárenia z finančnej činnosti (2)",
        "Výsledok hospodárenia z finančnej činnosti (3)",
        "Zisk / strata pred zdanením (1)",
        "Zisk / strata pred zdanením (2)",
        "Zisk / strata pred zdanením (3)",
        "Zisk / strata po zdanení (1)",
        "Zisk / strata po zdanení (2)",
        "Zisk / strata po zdanení (3)",
        "EBITDA (1)",
        "EBITDA (2)",
        "EBITDA (3)",
        "Cash flow (1)",
        "Cash flow (2)",
        "Cash flow (3)",
        "Aktíva (1)",
        "Aktíva (2)",
        "Aktíva (3)",
        "Dlhodobé aktíva (1)",
        "Dlhodobé aktíva (2)",
        "Dlhodobé aktíva (3)",
        "Krátkodobé aktíva (1)",
        "Krátkodobé aktíva (2)",
        "Krátkodobé aktíva (3)",
        "Dlhy - PP a PE (1)",
        "Dlhy - PP a PE (2)",
        "Dlhy - PP a PE (3)",
        "Dlhodobé dlhy (1)",
        "Dlhodobé dlhy (2)",
        "Dlhodobé dlhy (3)",
        "Krátkodobé dlhy (1)",
        "Krátkodobé dlhy (2)",
        "Krátkodobé dlhy (3)",
        "Celkové pohľadávky (1)",
        "Celkové pohľadávky (2)",
        "Celkové pohľadávky (3)",
        "Krátkodobé pohľadávky (1)",
        "Krátkodobé pohľadávky (2)",
        "Krátkodobé pohľadávky (3)",
        "Krátkodobé pohľadávky z OS (1)",
        "Krátkodobé pohľadávky z OS (2)",
        "Krátkodobé pohľadávky z OS (3)",
        "Celkové záväzky (1)",
        "Celkové záväzky (2)",
        "Celkové záväzky (3)",
        "Krátkodobé záväzky (1)",
        "Krátkodobé záväzky (2)",
        "Krátkodobé záväzky (3)",
        "Krátkodobé záväzky z OS (1)",
        "Krátkodobé záväzky z OS (2)",
        "Krátkodobé záväzky z OS (3)",
        "Vlastné imanie (1)",
        "Vlastné imanie (2)",
        "Vlastné imanie (3)",
        "Rentabilita vlastného imania (1)",
        "Rentabilita vlastného imania (2)",
        "Rentabilita vlastného imania (3)",
        "Rentabilita aktív (1)",
        "Rentabilita aktív (2)",
        "Rentabilita aktív (3)",
        "Prevádzková rentabilita tržieb (1)",
        "Prevádzková rentabilita tržieb (2)",
        "Prevádzková rentabilita tržieb (3)",
        "Bankové úvery  (1)",
        "Bankové úvery  (2)",
        "Bankové úvery  (3)",
        "Telefón",
        "Fax",
        "Web",
        "Email",
        "E-shop",
        "Facebook",
        "Twitter",
        "Linked-In",
        "Štátom vlastnená spoločnosť",
        "Dcérska spoločnosť štátu",
        "Pridružená spoločnosti štátu",
        "Víťaz verejného obstarávania",
        "Vyhrali verejné súťaže (posledné 3R)",
        "Hodnota verejných súťaží vyhraná (posledné 3 r.) ",
        "Príjemca dotácií",
        "Získané dotácie (posledné 3r)",
        "Hodnota získaných dotácií (za posledné 3r)",
        "Počet registrovaných vozidiel",
        "Export",
        "Krajiny exportu",
        "Import",
        "Krajiny importu",
        "Kontrolné a štatutárne orgány - Meno / Názov spoločnosti (1)",
        "Kontrolné a štatutárne orgány - IČO (1)",
        "Kontrolné a štatutárne orgány - Dátum narodenia (1)",
        "Kontrolné a štatutárne orgány - Pozícia (1)",
        "Kontrolné a štatutárne orgány - Platné od (1)",
        "Kontrolné a štatutárne orgány - Krajina (1)",
        "Kontrolné a štatutárne orgány - Vek (1)",
        "Kontrolné a štatutárne orgány - Meno / Názov spoločnosti (2)",
        "Kontrolné a štatutárne orgány - IČO (2)",
        "Kontrolné a štatutárne orgány - Dátum narodenia (2)",
        "Kontrolné a štatutárne orgány - Pozícia (2)",
        "Kontrolné a štatutárne orgány - Platné od (2)",
        "Kontrolné a štatutárne orgány - Krajina (2)",
        "Kontrolné a štatutárne orgány - Vek (2)",
        "Kontrolné a štatutárne orgány - Meno / Názov spoločnosti (3)",
        "Kontrolné a štatutárne orgány - IČO (3)",
        "Kontrolné a štatutárne orgány - Dátum narodenia (3)",
        "Kontrolné a štatutárne orgány - Pozícia (3)",
        "Kontrolné a štatutárne orgány - Platné od (3)",
        "Kontrolné a štatutárne orgány - Krajina (3)",
        "Kontrolné a štatutárne orgány - Vek (3)",
        "Vlastníci - Meno / Názov spoločnosti (1)",
        "Vlastníci - IČO (1)",
        "Vlastníci - Dátum narodenia (1)",
        "Vlastníci - Pozícia (1)",
        "Vlastníci - Podiel (%) (1)",
        "Vlastníci - Vklad (1)",
        "Vlastníci - Platné od (1)",
        "Vlastníci - Krajina (1)",
        "Vlastníci - Vek (1)",
        "Vlastníci - Meno / Názov spoločnosti (2)",
        "Vlastníci - IČO (2)",
        "Vlastníci - Dátum narodenia (2)",
        "Vlastníci - Pozícia (2)",
        "Vlastníci - Podiel (%) (2)",
        "Vlastníci - Vklad (2)",
        "Vlastníci - Platné od (2)",
        "Vlastníci - Krajina (2)",
        "Vlastníci - Vek (2)",
        "Vlastníci - Meno / Názov spoločnosti (3)",
        "Vlastníci - IČO (3)",
        "Vlastníci - Dátum narodenia (3)",
        "Vlastníci - Pozícia (3)",
        "Vlastníci - Podiel (%) (3)",
        "Vlastníci - Vklad (3)",
        "Vlastníci - Platné od (3)",
        "Vlastníci - Krajina (3)",
        "Vlastníci - Vek (3)",
        "Majetkové účasti v spoločnostiach - Názov spoločnosti (1)",
        "Majetkové účasti v spoločnostiach - IČO (1)",
        "Majetkové účasti v spoločnostiach - Pozícia (1)",
        "Majetkové účasti v spoločnostiach - Podiel (%) (1)",
        "Majetkové účasti v spoločnostiach - Vklad (1)",
        "Majetkové účasti v spoločnostiach - Platné od (1)",
        "Majetkové účasti v spoločnostiach - Krajina (1)",
        "Majetkové účasti v spoločnostiach - Názov spoločnosti (2)",
        "Majetkové účasti v spoločnostiach - IČO (2)",
        "Majetkové účasti v spoločnostiach - Pozícia (2)",
        "Majetkové účasti v spoločnostiach - Podiel (%) (2)",
        "Majetkové účasti v spoločnostiach - Vklad (2)",
        "Majetkové účasti v spoločnostiach - Platné od (2)",
        "Majetkové účasti v spoločnostiach - Krajina (2)",
        "Majetkové účasti v spoločnostiach - Názov spoločnosti (3)",
        "Majetkové účasti v spoločnostiach - IČO (3)",
        "Majetkové účasti v spoločnostiach - Pozícia (3)",
        "Majetkové účasti v spoločnostiach - Podiel (%) (3)",
        "Majetkové účasti v spoločnostiach - Vklad (3)",
        "Majetkové účasti v spoločnostiach - Platné od (3)",
        "Majetkové účasti v spoločnostiach - Krajina (3)",
        "Index CRIBIS",
        "Skupinový semafor CRIBIS",
        "Pravdepodobnosť bankrotu (%)",
        "Úverová kapacita",
        "Voľná ​​krátkodobá úverová kapacita",
        "Stupeň rizika",
        "Finančná situácia",
        "Skupina prepojených (ESS)",
      ],
    ],
    EN: [
      [
        "MargoId",
        "CompanyID/TaxId/VatId",
        "Status company",
        "Tag",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Tax code",
        "Legal forms group",
        "Legal form",
        "Status company",
        "Date of registration",
        "Registered Capital",
        "Creation of business trading",
        "End date",
        "Number of branches",
        "Country",
        "Region",
        "District",
        "City",
        "Zip code",
        "Address",
        "Longitude",
        "Latitude",
        "Prevailing activity (NACE)",
        "Description prevailing activity (NACE)",
        "Primary SIC",
        "Description primary SIC",
        "Range of employees count",
        "Employee trend",
        "Employees category year (CZ)",
        "Employees category year (SK)",
        "Turnover category (CZ)",
        "Turnover category (SK)",
        "Turnover trend",
        "Turnover category year (CZ)",
        "Turnover category year (SK)",
        "Revenues",
        "Profit / loss",
        "Total Assets",
        "Period from (1)",
        "Period from (2)",
        "Period from (3)",
        "Period to (1)",
        "Period to (2)",
        "Period to (3)",
        "Sales (1)",
        "Sales (2)",
        "Sales (3)",
        "Operating expenses (1)",
        "Operating expenses (2)",
        "Operating expenses (3)",
        "Profit/loss from financial activities (1)",
        "Profit/loss from financial activities (2)",
        "Profit/loss from financial activities (3)",
        "Profit before tax (1)",
        "Profit before tax (2)",
        "Profit before tax (3)",
        "Profit after tax (1)",
        "Profit after tax (2)",
        "Profit after tax (3)",
        "EBITDA (1)",
        "EBITDA (2)",
        "EBITDA (3)",
        "Cash flow (1)",
        "Cash flow (2)",
        "Cash flow (3)",
        "Total assets (1)",
        "Total assets (2)",
        "Total assets (3)",
        "Long-term assets (1)",
        "Long-term assets (2)",
        "Long-term assets (3)",
        "Short-term assets (1)",
        "Short-term assets (2)",
        "Short-term assets (3)",
        "Liabilities without cash and cash equivalents (1)",
        "Liabilities without cash and cash equivalents (2)",
        "Liabilities without cash and cash equivalents (3)",
        "Long-term liabilities (1)",
        "Long-term liabilities (2)",
        "Long-term liabilities (3)",
        "Short-term liabilities (1)",
        "Short-term liabilities (2)",
        "Short-term liabilities (3)",
        "Total credits (1)",
        "Total credits (2)",
        "Total credits (3)",
        "Short-term credits (1)",
        "Short-term credits (2)",
        "Short-term credits (3)",
        "Short-term trade credits (1)",
        "Short-term trade credits (2)",
        "Short-term trade credits (3)",
        "Total debts (1)",
        "Total debts (2)",
        "Total debts (3)",
        "Short-term debts (1)",
        "Short-term debts (2)",
        "Short-term debts (3)",
        "Short-term trade debts (1)",
        "Short-term trade debts (2)",
        "Short-term trade debts (3)",
        "Net worth (1)",
        "Net worth (2)",
        "Net worth (3)",
        "Return on Equity (1)",
        "Return on Equity (2)",
        "Return on Equity (3)",
        "Return on Assets (1)",
        "Return on Assets (2)",
        "Return on Assets (3)",
        "Operating Return on Sales (1)",
        "Operating Return on Sales (2)",
        "Operating Return on Sales (3)",
        "Loans (1)",
        "Loans (2)",
        "Loans (3)",
        "Phone number",
        "Fax",
        "Website URL",
        "Email",
        "Ecommerce",
        "Facebook",
        "Twitter",
        "LinkedIn",
        "State-owned company",
        "State subsidiary company",
        "State-affiliated company",
        "Public tenders winner",
        "Public tenders won (last 3Y)",
        "Public tenders value won (last 3Y)",
        "Grants winner",
        "Grants won (last 3Y)",
        "Grants value won (last 3Y)",
        "Register vehicles count",
        "Export",
        "Export partner",
        "Import",
        "Import partner",
        "Supervisory board & statutory body - Name / business name (1)",
        "Supervisory board & statutory body - Company ID (1)",
        "Supervisory board & statutory body - d. o. b. (1)",
        "Supervisory board & statutory body - Position (1)",
        "Supervisory board & statutory body - Valid From (1)",
        "Supervisory board & statutory body - Country (1)",
        "Supervisory board & statutory body - Age (1)",
        "Supervisory board & statutory body - Name / business name (2)",
        "Supervisory board & statutory body - Company ID (2)",
        "Supervisory board & statutory body - d. o. b. (2)",
        "Supervisory board & statutory body - Position (2)",
        "Supervisory board & statutory body - Valid From (2)",
        "Supervisory board & statutory body - Country (2)",
        "Supervisory board & statutory body - Age (2)",
        "Supervisory board & statutory body - Name / business name (3)",
        "Supervisory board & statutory body - Company ID (3)",
        "Supervisory board & statutory body - d. o. b. (3)",
        "Supervisory board & statutory body - Position (3)",
        "Supervisory board & statutory body - Valid From (3)",
        "Supervisory board & statutory body - Country (3)",
        "Supervisory board & statutory body - Age (3)",
        "Owners - Name / business name (1)",
        "Owners - Company ID  (1)",
        "Owners - d. o. b. (1)",
        "Owners - Position (1)",
        "Owners - Share (%) (1)",
        "Owners - Deposit (1)",
        "Owners - Valid From (1)",
        "Owners - Country (1)",
        "Owners - Age (1)",
        "Owners - Name / business name (2)",
        "Owners - Company ID  (2)",
        "Owners - d. o. b. (2)",
        "Owners - Position (2)",
        "Owners - Share (%) (2)",
        "Owners - Deposit (2)",
        "Owners - Valid From (2)",
        "Owners - Country (2)",
        "Owners - Age (2)",
        "Owners - Name / business name (3)",
        "Owners - Company ID  (3)",
        "Owners - d. o. b. (3)",
        "Owners - Position (3)",
        "Owners - Share (%) (3)",
        "Owners - Deposit (3)",
        "Owners - Valid From (3)",
        "Owners - Country (3)",
        "Owners - Age (3)",
        "Ownership interests in companies - Name / business name (1)",
        "Ownership interests in companies - Company ID (1)",
        "Ownership interests in companies - Position (1)",
        "Ownership interests in companies - Share (%) (1)",
        "Ownership interests in companies - Deposit (1)",
        "Ownership interests in companies - Valid From (1)",
        "Ownership interests in companies - Country (1)",
        "Ownership interests in companies - Name / business name (2)",
        "Ownership interests in companies - Company ID (2)",
        "Ownership interests in companies - Position (2)",
        "Ownership interests in companies - Share (%) (2)",
        "Ownership interests in companies - Deposit (2)",
        "Ownership interests in companies - Valid From (2)",
        "Ownership interests in companies - Country (2)",
        "Ownership interests in companies - Name / business name (3)",
        "Ownership interests in companies - Company ID (3)",
        "Ownership interests in companies - Position (3)",
        "Ownership interests in companies - Share (%) (3)",
        "Ownership interests in companies - Deposit (3)",
        "Ownership interests in companies - Valid From (3)",
        "Ownership interests in companies - Country (3)",
        "Index Cribis",
        "Group Semaphore Cribis",
        "Probability of bankruptcy (%)",
        "Credit Limit",
        "Possible Credit Accrual",
        "Risk level",
        "Financial condition",
        "Economic group (ESS)",
      ],
    ],
  },
  customTemplate: {
    CZ: [
      [
        "MargoId",
        "IČ",
        "Status company",
        "Tag",
        "Množství",
        "Area Manažer",
        "Obchodník",
        "Produkt",
        "PSČ",
        "PSČ",
        "Kategorie počtu zaměstnanců",
        "Kategorie obratu (CZ)",
        "Export",
        "Import",
      ],
    ],
    SK: [
      [
        "MargoId",
        "IČO",
        "Status company",
        "Tag",
        "Množstvo",
        "Oblastný manažér",
        "Obchodník",
        "Produkt",
        "PSČ",
        "PSČ",
        "Kategória počtu zamestnancov",
        "Kategória obratu (SK)",
        "Export",
        "Import",
      ],
    ],
  },
  base: {
    CZ: [
      [
        "CZ-25501143_48B57143-2D5B-49C4-AEFC-250B9505E9B0",
        "25501143",
        "Prospekt $(Prospect)$",
      ],
      [
        "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
        "26178541",
        "Prospekt $(Prospect)$",
      ],
      [
        "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
        "46345965",
        "Prospekt $(Prospect)$",
      ],
      [
        "MargoId",
        "IČ",
        "Status company",
        "Tag",
        "Množství",
        "Area Manažer",
        "Obchodník",
        "Produkt",
      ],
      [
        "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
        "31333532",
        "Prospekt $(Prospect)$",
      ],
      [
        "SK-35876832_30D2B337-552F-4030-9DC6-C4E9CA471C8D",
        "35876832",
        "Prospekt $(Prospect)$",
      ],
    ],
    SK: [
      [
        "CZ-25501143_48B57143-2D5B-49C4-AEFC-250B9505E9B0",
        "25501143",
        "Prospekt $(Prospect)$",
      ],
      [
        "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
        "26178541",
        "Prospekt $(Prospect)$",
      ],
      [
        "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
        "46345965",
        "Prospekt $(Prospect)$",
      ],
      [
        "MargoId",
        "IČO",
        "Status company",
        "Tag",
        "Množstvo",
        "Oblastný manažér",
        "Obchodník",
        "Produkt",
      ],
      [
        "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
        "31333532",
        "Prospekt $(Prospect)$",
      ],
      [
        "SK-35876832_30D2B337-552F-4030-9DC6-C4E9CA471C8D",
        "35876832",
        "Prospekt $(Prospect)$",
      ],
    ],
    EN: [
      [
        "CZ-25501143_48B57143-2D5B-49C4-AEFC-250B9505E9B0",
        "25501143",
        "Prospect $(Prospect)$",
      ],
      [
        "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
        "26178541",
        "Prospect $(Prospect)$",
      ],
      [
        "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
        "46345965",
        "Prospect $(Prospect)$",
      ],
      [
        "MargoId",
        "CompanyID/TaxId/VatId",
        "Status company",
        "Tag",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
      ],
      [
        "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
        "31333532",
        "Prospect $(Prospect)$",
      ],
      [
        "SK-35876832_30D2B337-552F-4030-9DC6-C4E9CA471C8D",
        "35876832",
        "Prospect $(Prospect)$",
      ],
    ],
  },
  marketing: {
    CZ: [
      [
        "CZ-25501143_48B57143-2D5B-49C4-AEFC-250B9505E9B0",
        "25501143",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Ptáček - velkoobchod, a.s.",
        "CZ25501143",
        null,
        "Právnické osoby podnikatelské",
        "Akciová společnost",
        "Aktivní",
        "05-09-1997",
        "Česká republika",
        "Jihomoravský kraj",
        "Brno-město",
        "Brno-Kohoutovice",
        "CZ551147_62300",
        "U Velké ceny 413/4",
        16.53093,
        49.19749,
        "0G4601",
        "Zprostředkování velkoobchodu a velkoobchod v zastoupení ",
        "5199",
        "Velkoobchody s různým zbožím krátkodobé spotřeby",
        "1 000 - 1 999",
        "Stabilní",
        2021,
        null,
        "1 500 000 000 Kč a více",
        "Nedostupné",
        "Stabilní",
        2021,
        null,
        "+420 220 800 100, +420 518 325 174",
        "+420 518 325 205",
        "www.ptacek.cz",
        "hodonin@ptacek.cz, sekretariat@ptacek.cz",
        null,
        "https://www.facebook.com/ptacek.velkoobchod",
        "False",
        "True",
        "True",
        "ING. ZDENĚK PTÁČEK",
        "24-06-1947",
        "Předseda správní rady",
        "09-04-2021",
        "Česká republika",
        "ING. JIŘÍ PTÁČEK",
        "27-03-1972",
        "Člen správní rady",
        "09-04-2021",
        "Česká republika",
        "ING. ZDENĚK PTÁČEK",
        "04-08-1974",
        "Člen správní rady",
        "09-04-2021",
        "Česká republika",
      ],
      [
        "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
        "26178541",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Lidl Česká republika v.o.s.",
        "CZ26178541",
        null,
        "Právnické osoby podnikatelské",
        "Veřejná obchodní společnost",
        "Aktivní",
        "05-06-2000",
        "Česká republika",
        "Hlavní město Praha",
        "Praha",
        "Praha 13",
        "CZ539694_15800",
        "Nárožní 1359/11",
        14.33119,
        50.05276,
        "0G4701",
        "Maloobchod v nespecializovaných prodejnách",
        "5399",
        "Všeobecný maloobchod",
        "10 000",
        "Stabilní",
        2021,
        null,
        "1 500 000 000 Kč a více",
        "Nedostupné",
        "Stabilní",
        2021,
        null,
        "+420 257 086 111, +420 800 115 435",
        "+420 257 011 700",
        "www.lidl.cz",
        "hotline@lidl.cz, lidl@lidl.cz",
        "https://www.lidl-shop.cz/?utm_source=lidl.cz&utm_medium=header&utm_campaign=e-shop",
        "https://www.facebook.com/lidlcesko/",
        "False",
        "False",
        "False",
        "LIDL HOLDING S.R.O.",
        null,
        "Statutární zástupce (n/a)",
        "05-06-2000",
        "Česká republika",
      ],
      [
        "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
        "46345965",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Česká zbrojovka a.s.",
        "CZ46345965",
        null,
        "Právnické osoby podnikatelské",
        "Akciová společnost",
        "Aktivní",
        "27-04-1992",
        "Česká republika",
        "Zlínský kraj",
        "Uherské Hradiště",
        "Uherský Brod",
        "CZ592731_68801",
        "Svat. Čecha 1283",
        17.63395,
        49.02589,
        "0C250400",
        "Výroba zbraní a střeliva",
        "3483",
        "Výrobci různého střeliva (kromě střeliva pro ruční zbraně)",
        "1 000 - 1 999",
        "Stabilní",
        2021,
        null,
        "1 500 000 000 Kč a více",
        "Nedostupné",
        "Stabilní",
        2021,
        null,
        "+420 572 653 911, +420 572 655 230",
        "+420 572 655 231",
        "www.cz-auto.com, www.czub.cz",
        "info@cz-auto.com, prodejna@czub.cz, info@czub.cz",
        null,
        "https://www.facebook.com/cz-auto-systems-as-1794631114143391/?view_public_for=1794631114143391",
        "False",
        "False",
        "True",
        "ING. JAN ZAJÍC",
        "05-01-1976",
        "Předseda představenstva",
        "15-01-2021",
        "Česká republika",
        "ING. TOMÁŠ HAUERLAND MBA",
        "06-10-1970",
        "Místopředseda představenstva",
        "13-04-2019",
        "Česká republika",
        "ING. TOMÁŠ STOSZEK",
        "08-02-1968",
        "Místopředseda představenstva",
        "15-01-2021",
        "Česká republika",
      ],
      [
        "MargoId",
        "IČ",
        "Status company",
        "Tag",
        "Množství",
        "Area Manažer",
        "Obchodník",
        "Produkt",
        "Název společnosti",
        "DIČ",
        "Daňové číslo",
        "Skupina právních forem",
        "Právní forma",
        "Stav",
        "Datum založení",
        "Stát",
        "Kraj",
        "Okres",
        "Město",
        "PSČ",
        "Adresa sídla",
        "Zeměpisná délka",
        "Zeměpisná šířka",
        "Distribuce Převažující činnosti (NACE)",
        "Popis distribuce Převažující činnosti (NACE)",
        "SIC",
        "Popis přiárního SIC",
        "Kategorie počtu zaměstnanců",
        "Trend počtu zaměstnanců",
        "Rok kategorie počtu zaměstnanců (CZ)",
        "Rok kategorie počtu zaměstnanců (SK)",
        "Kategorie obratu (CZ)",
        "Kategorie obratu (SK)",
        "Trend obratu",
        "Rok kategorie obratu (CZ)",
        "Rok kategorie obratu (SK) ",
        "Telefon",
        "Fax",
        "Web",
        "Email",
        "E-shop",
        "Facebook",
        "Státem vlastněná společnost",
        "Export",
        "Import",
        "Kontrolní a statutární orgány - Jméno / Název společnosti (1)",
        "Kontrolní a statutární orgány - Datum narození (1)",
        "Kontrolní a statutární orgány - Pozice (1)",
        "Kontrolní a statutární orgány - Platné od (1)",
        "Kontrolní a statutární orgány - Země (1)",
        "Kontrolní a statutární orgány - Jméno / Název společnosti (2)",
        "Kontrolní a statutární orgány - Datum narození (2)",
        "Kontrolní a statutární orgány - Pozice (2)",
        "Kontrolní a statutární orgány - Platné od (2)",
        "Kontrolní a statutární orgány - Země (2)",
        "Kontrolní a statutární orgány - Jméno / Název společnosti (3)",
        "Kontrolní a statutární orgány - Datum narození (3)",
        "Kontrolní a statutární orgány - Pozice (3)",
        "Kontrolní a statutární orgány - Platné od (3)",
        "Kontrolní a statutární orgány - Země (3)",
      ],
      [
        "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
        "31333532",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ESET, spol. s r.o.",
        "SK2020317068",
        "2020317068",
        "Právnické osoby podnikatelské",
        "Společnost s ručením omezeným",
        "Aktivní",
        "17-09-1992",
        "Slovenská republika",
        "Bratislavský kraj",
        "Bratislava V",
        "Bratislava-Petržalka",
        "SK529460_85101",
        "Einsteinova 24",
        17.10543,
        48.13415,
        "0J620009",
        "Ostatní činnosti v oblasti informačních technologií",
        "7379",
        "Různé počítačové služby",
        "1 000 - 1 999",
        "Pozitivní",
        null,
        2020,
        "Nedostupné",
        ">= 500 000 tis. Eur",
        "Pozitivní",
        null,
        2019,
        "+421 232 244 109, +421 232 244 444, +421 232 244 250, +421 232 244 111",
        null,
        null,
        "info@eset.sk",
        null,
        null,
        "False",
        "False",
        "False",
        "ING. PETER PAŠKO",
        "18-05-1955",
        "Jednatel",
        "17-09-1992",
        "Slovenská republika",
        "ING. MIROSLAV TRNKA",
        "29-03-1961",
        "Jednatel",
        "17-09-1992",
        "Slovenská republika",
        "RUDOLF HRUBÝ",
        "14-04-1954",
        "Jednatel",
        "17-09-1992",
        "Slovenská republika",
      ],
      [
        "SK-35876832_30D2B337-552F-4030-9DC6-C4E9CA471C8D",
        "35876832",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Kia Motors Slovakia s.r.o.",
        "SK2021787801",
        "2021787801",
        "Právnické osoby podnikatelské",
        "Společnost s ručením omezeným",
        "Aktivní",
        "26-02-2004",
        "Slovenská republika",
        "Žilinský kraj",
        "Žilina",
        "Teplička nad Váhom",
        "SK518034_01301",
        "Sv. Jána Nepomuckého 1282/1",
        null,
        null,
        "0C290100",
        "Výroba motorových vozidel a jejich motorů",
        "3711",
        "Výrobci motorových vozidel",
        "3 000 - 3 999",
        "Stabilní",
        null,
        2020,
        "Nedostupné",
        ">= 500 000 tis. Eur",
        "Stabilní",
        null,
        2019,
        "+421 415 150 111",
        null,
        null,
        "media@kia.sk, rvrabel@kia.sk",
        null,
        null,
        "False",
        "False",
        "False",
        "DONGEUN LEE",
        null,
        "Člen dozorčí rady",
        "20-03-2019",
        "Korejská republika",
        "WOOJEONG JOO",
        null,
        "Člen dozorčí rady",
        "20-03-2019",
        "Korejská republika",
        "HO SUNG SONG",
        null,
        "Člen dozorčí rady",
        "17-07-2020",
        "Korejská republika",
      ],
    ],
    SK: [
      [
        "CZ-25501143_48B57143-2D5B-49C4-AEFC-250B9505E9B0",
        "25501143",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Ptáček - velkoobchod, a.s.",
        "CZ25501143",
        null,
        "Právnické osoby podnikateľské",
        "Akciová spoločnosť",
        "Aktívna",
        "05-09-1997",
        "Česká republika",
        "Juhomoravský kraj",
        "Brno-město",
        "Brno-Kohoutovice",
        "CZ551147_62300",
        "U Velké ceny 413/4",
        16.53093,
        49.19749,
        "0G4601",
        "Sprostredkovanie veľkoobchodu",
        "5199",
        "Veľkoobchodníci s rôznym netrvanlivým tovarom",
        "1 000 - 1 999",
        "Stabilný",
        2021,
        null,
        "1 500 000 000 Kč a viac",
        "Nedost.",
        "Stabilný",
        2021,
        null,
        "+420 220 800 100, +420 518 325 174",
        "+420 518 325 205",
        "www.ptacek.cz",
        "hodonin@ptacek.cz, sekretariat@ptacek.cz",
        null,
        "https://www.facebook.com/ptacek.velkoobchod",
        "False",
        "True",
        "True",
        "ING. ZDENĚK PTÁČEK",
        "24-06-1947",
        "Predseda správnej rady",
        "09-04-2021",
        "Česká republika",
        "ING. JIŘÍ PTÁČEK",
        "27-03-1972",
        "Člen správnej rady",
        "09-04-2021",
        "Česká republika",
        "ING. ZDENĚK PTÁČEK",
        "04-08-1974",
        "Člen správnej rady",
        "09-04-2021",
        "Česká republika",
      ],
      [
        "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
        "26178541",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Lidl Česká republika v.o.s.",
        "CZ26178541",
        null,
        "Právnické osoby podnikateľské",
        "Verejná obchodná spoločnosť",
        "Aktívna",
        "05-06-2000",
        "Česká republika",
        "Hlavné mesto Praha",
        "Praha",
        "Praha 13",
        "CZ539694_15800",
        "Nárožní 1359/11",
        14.33119,
        50.05276,
        "0G4701",
        "Maloobchod v nešpecializovaných predajniach",
        "5399",
        "Všeobecní maloobchodníci",
        "10 000",
        "Stabilný",
        2021,
        null,
        "1 500 000 000 Kč a viac",
        "Nedost.",
        "Stabilný",
        2021,
        null,
        "+420 257 086 111, +420 800 115 435",
        "+420 257 011 700",
        "www.lidl.cz",
        "hotline@lidl.cz, lidl@lidl.cz",
        "https://www.lidl-shop.cz/?utm_source=lidl.cz&utm_medium=header&utm_campaign=e-shop",
        "https://www.facebook.com/lidlcesko/",
        "False",
        "False",
        "False",
        "LIDL HOLDING S.R.O.",
        null,
        "Štatutárny zástupca (n/a)",
        "05-06-2000",
        "Česká republika",
      ],
      [
        "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
        "46345965",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Česká zbrojovka a.s.",
        "CZ46345965",
        null,
        "Právnické osoby podnikateľské",
        "Akciová spoločnosť",
        "Aktívna",
        "27-04-1992",
        "Česká republika",
        "Zlínsky kraj",
        "Uherské Hradiště",
        "Uherský Brod",
        "CZ592731_68801",
        "Svat. Čecha 1283",
        17.63395,
        49.02589,
        "0C250400",
        "Výroba zbraní a munície",
        "3483",
        "Výrobcovia rôzneho streliva (okrem ručných zbraní)",
        "1 000 - 1 999",
        "Stabilný",
        2021,
        null,
        "1 500 000 000 Kč a viac",
        "Nedost.",
        "Stabilný",
        2021,
        null,
        "+420 572 653 911, +420 572 655 230",
        "+420 572 655 231",
        "www.cz-auto.com, www.czub.cz",
        "info@cz-auto.com, prodejna@czub.cz, info@czub.cz",
        null,
        "https://www.facebook.com/cz-auto-systems-as-1794631114143391/?view_public_for=1794631114143391",
        "False",
        "False",
        "True",
        "ING. JAN ZAJÍC",
        "05-01-1976",
        "Predseda predstavenstva",
        "15-01-2021",
        "Česká republika",
        "ING. TOMÁŠ HAUERLAND MBA",
        "06-10-1970",
        "Podpredseda predstavenstva",
        "13-04-2019",
        "Česká republika",
        "ING. TOMÁŠ STOSZEK",
        "08-02-1968",
        "Podpredseda predstavenstva",
        "15-01-2021",
        "Česká republika",
      ],
      [
        "MargoId",
        "IČO",
        "Status company",
        "Tag",
        "Množstvo",
        "Oblastný manažér",
        "Obchodník",
        "Produkt",
        "Názov spoločnosti",
        "IČ DPH",
        "DIČ",
        "Skupina právnych foriem",
        "Právna forma",
        "Stav",
        "Dátum založenia",
        "Krajina",
        "Kraj",
        "Okres",
        "Obec",
        "PSČ",
        "Adresa sídla",
        "Zemepisná dĺžka",
        "Zemepisná šírka",
        "Distribúcia Prevažujúcej činnosti (NACE)",
        "Popis distribúcia Prevažujúcej činnosti (NACE)",
        "SIC",
        "Popis primárneho SIC",
        "Kategória počtu zamestnancov",
        "Trend počtu zamestnancov",
        "Rok kategórie počtu zamestnancov (CZ)",
        "Rok kategórie počtu zamestnancov (SK)",
        "Kategória obratu (CZ)",
        "Kategória obratu (SK)",
        "Trend obratu",
        "Rok kategórie obratu (CZ)",
        "Rok kategórie obratu (SK)",
        "Telefón",
        "Fax",
        "Web",
        "Email",
        "E-shop",
        "Facebook",
        "Štátom vlastnená spoločnosť",
        "Export",
        "Import",
        "Kontrolné a štatutárne orgány - Meno / Názov spoločnosti (1)",
        "Kontrolné a štatutárne orgány - Dátum narodenia (1)",
        "Kontrolné a štatutárne orgány - Pozícia (1)",
        "Kontrolné a štatutárne orgány - Platné od (1)",
        "Kontrolné a štatutárne orgány - Krajina (1)",
        "Kontrolné a štatutárne orgány - Meno / Názov spoločnosti (2)",
        "Kontrolné a štatutárne orgány - Dátum narodenia (2)",
        "Kontrolné a štatutárne orgány - Pozícia (2)",
        "Kontrolné a štatutárne orgány - Platné od (2)",
        "Kontrolné a štatutárne orgány - Krajina (2)",
        "Kontrolné a štatutárne orgány - Meno / Názov spoločnosti (3)",
        "Kontrolné a štatutárne orgány - Dátum narodenia (3)",
        "Kontrolné a štatutárne orgány - Pozícia (3)",
        "Kontrolné a štatutárne orgány - Platné od (3)",
        "Kontrolné a štatutárne orgány - Krajina (3)",
      ],
      [
        "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
        "31333532",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ESET, spol. s r.o.",
        "SK2020317068",
        "2020317068",
        "Právnické osoby podnikateľské",
        "Spoločnosť s ručením obmedzeným",
        "Aktívna",
        "17-09-1992",
        "Slovenská republika",
        "Bratislavský kraj",
        "Bratislava V",
        "Bratislava-Petržalka",
        "SK529460_85101",
        "Einsteinova 24",
        17.10543,
        48.13415,
        "0J620009",
        "Ostatné služby týkajúce sa informačných technológií a počítačov",
        "7379",
        "Rôzne počítačové služby",
        "1 000 - 1 999",
        "Pozitívny",
        null,
        2020,
        "Nedost.",
        ">= 500 000 tis. Eur",
        "Pozitívny",
        null,
        2019,
        "+421 232 244 109, +421 232 244 444, +421 232 244 250, +421 232 244 111",
        null,
        null,
        "info@eset.sk",
        null,
        null,
        "False",
        "False",
        "False",
        "ING. PETER PAŠKO",
        "18-05-1955",
        "Konateľ",
        "17-09-1992",
        "Slovenská republika",
        "ING. MIROSLAV TRNKA",
        "29-03-1961",
        "Konateľ",
        "17-09-1992",
        "Slovenská republika",
        "RUDOLF HRUBÝ",
        "14-04-1954",
        "Konateľ",
        "17-09-1992",
        "Slovenská republika",
      ],
      [
        "SK-35876832_30D2B337-552F-4030-9DC6-C4E9CA471C8D",
        "35876832",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Kia Motors Slovakia s.r.o.",
        "SK2021787801",
        "2021787801",
        "Právnické osoby podnikateľské",
        "Spoločnosť s ručením obmedzeným",
        "Aktívna",
        "26-02-2004",
        "Slovenská republika",
        "Žilinský kraj",
        "Žilina",
        "Teplička nad Váhom",
        "SK518034_01301",
        "Sv. Jána Nepomuckého 1282/1",
        null,
        null,
        "0C290100",
        "Výroba motorových vozidiel",
        "3711",
        "Výrobcovia motorových vozidiel",
        "3 000 - 3 999",
        "Stabilný",
        null,
        2020,
        "Nedost.",
        ">= 500 000 tis. Eur",
        "Stabilný",
        null,
        2019,
        "+421 415 150 111",
        null,
        null,
        "media@kia.sk, rvrabel@kia.sk",
        null,
        null,
        "False",
        "False",
        "False",
        "DONGEUN LEE",
        null,
        "Člen dozornej rady",
        "20-03-2019",
        "Južná Kórea",
        "WOOJEONG JOO",
        null,
        "Člen dozornej rady",
        "20-03-2019",
        "Južná Kórea",
        "HO SUNG SONG",
        null,
        "Člen dozornej rady",
        "17-07-2020",
        "Južná Kórea",
      ],
    ],
    EN: [
      [
        "CZ-25501143_48B57143-2D5B-49C4-AEFC-250B9505E9B0",
        "25501143",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Ptáček - velkoobchod, a.s.",
        "CZ25501143",
        null,
        "Legal persons entrepreneurial",
        "Joint stock company",
        "Active",
        "05-09-1997",
        "Czech Republic",
        "South Moravia Region",
        "Brno-město",
        "Brno-Kohoutovice",
        "CZ551147_62300",
        "U Velké ceny 413/4",
        16.53093,
        49.19749,
        "0G4601",
        "Wholesale on a fee or contract basis",
        "5199",
        "Misc nondurable goods wholesalers",
        "1,000 - 1,999",
        "Stable",
        2021,
        null,
        "1,500,000,000 Kč and more",
        "N. a.",
        "Stable",
        2021,
        null,
        "+420 220 800 100, +420 518 325 174",
        "+420 518 325 205",
        "www.ptacek.cz",
        "hodonin@ptacek.cz, sekretariat@ptacek.cz",
        null,
        "https://www.facebook.com/ptacek.velkoobchod",
        "False",
        "True",
        "True",
        "ING. ZDENĚK PTÁČEK",
        "24-06-1947",
        "Chairman of the Managing Board",
        "09-04-2021",
        "Czech Republic",
        "ING. JIŘÍ PTÁČEK",
        "27-03-1972",
        "Member of the Managing Board",
        "09-04-2021",
        "Czech Republic",
        "ING. ZDENĚK PTÁČEK",
        "04-08-1974",
        "Member of the Managing Board",
        "09-04-2021",
        "Czech Republic",
      ],
      [
        "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
        "26178541",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Lidl Česká republika v.o.s.",
        "CZ26178541",
        null,
        "Legal persons entrepreneurial",
        "Public commercial company",
        "Active",
        "05-06-2000",
        "Czech Republic",
        "Capital City Prague",
        "Prague",
        "Prague 13",
        "CZ539694_15800",
        "Nárožní 1359/11",
        14.33119,
        50.05276,
        "0G4701",
        "Retail sale in non-specialised stores",
        "5399",
        "General retailers",
        "10,000",
        "Stable",
        2021,
        null,
        "1,500,000,000 Kč and more",
        "N. a.",
        "Stable",
        2021,
        null,
        "+420 257 086 111, +420 800 115 435",
        "+420 257 011 700",
        "www.lidl.cz",
        "hotline@lidl.cz, lidl@lidl.cz",
        "https://www.lidl-shop.cz/?utm_source=lidl.cz&utm_medium=header&utm_campaign=e-shop",
        "https://www.facebook.com/lidlcesko/",
        "False",
        "False",
        "False",
        "LIDL HOLDING S.R.O.",
        null,
        "Statutory substitute (n/a)",
        "05-06-2000",
        "Czech Republic",
      ],
      [
        "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
        "46345965",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Česká zbrojovka a.s.",
        "CZ46345965",
        null,
        "Legal persons entrepreneurial",
        "Joint stock company",
        "Active",
        "27-04-1992",
        "Czech Republic",
        "Zlín Region",
        "Uherské Hradiště",
        "Uherský Brod",
        "CZ592731_68801",
        "Svat. Čecha 1283",
        17.63395,
        49.02589,
        "0C250400",
        "Manufacture of weapons and ammunition",
        "3483",
        "Misc ammunition mfrs (ex small arms)",
        "1,000 - 1,999",
        "Stable",
        2021,
        null,
        "1,500,000,000 Kč and more",
        "N. a.",
        "Stable",
        2021,
        null,
        "+420 572 653 911, +420 572 655 230",
        "+420 572 655 231",
        "www.cz-auto.com, www.czub.cz",
        "info@cz-auto.com, prodejna@czub.cz, info@czub.cz",
        null,
        "https://www.facebook.com/cz-auto-systems-as-1794631114143391/?view_public_for=1794631114143391",
        "False",
        "False",
        "True",
        "ING. JAN ZAJÍC",
        "05-01-1976",
        "Chairman of the Board of Directors",
        "15-01-2021",
        "Czech Republic",
        "ING. TOMÁŠ HAUERLAND MBA",
        "06-10-1970",
        "Vice-Chairman of the Board of Directors",
        "13-04-2019",
        "Czech Republic",
        "ING. TOMÁŠ STOSZEK",
        "08-02-1968",
        "Vice-Chairman of the Board of Directors",
        "15-01-2021",
        "Czech Republic",
      ],
      [
        "MargoId",
        "CompanyID/TaxId/VatId",
        "Status company",
        "Tag",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Tax code",
        "Legal forms group",
        "Legal form",
        "Status company",
        "Date of registration",
        "Country",
        "Region",
        "District",
        "City",
        "Zip code",
        "Address",
        "Longitude",
        "Latitude",
        "Prevailing activity (NACE)",
        "Description prevailing activity (NACE)",
        "Primary SIC",
        "Description primary SIC",
        "Range of employees count",
        "Employee trend",
        "Employees category year (CZ)",
        "Employees category year (SK)",
        "Turnover category (CZ)",
        "Turnover category (SK)",
        "Turnover trend",
        "Turnover category year (CZ)",
        "Turnover category year (SK)",
        "Phone number",
        "Fax",
        "Website URL",
        "Email",
        "Ecommerce",
        "Facebook",
        "State-owned company",
        "Export",
        "Import",
        "Supervisory board & statutory body - Name / business name (1)",
        "Supervisory board & statutory body - d. o. b. (1)",
        "Supervisory board & statutory body - Position (1)",
        "Supervisory board & statutory body - Valid From (1)",
        "Supervisory board & statutory body - Country (1)",
        "Supervisory board & statutory body - Name / business name (2)",
        "Supervisory board & statutory body - d. o. b. (2)",
        "Supervisory board & statutory body - Position (2)",
        "Supervisory board & statutory body - Valid From (2)",
        "Supervisory board & statutory body - Country (2)",
        "Supervisory board & statutory body - Name / business name (3)",
        "Supervisory board & statutory body - d. o. b. (3)",
        "Supervisory board & statutory body - Position (3)",
        "Supervisory board & statutory body - Valid From (3)",
        "Supervisory board & statutory body - Country (3)",
      ],
      [
        "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
        "31333532",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ESET, spol. s r.o.",
        "SK2020317068",
        "2020317068",
        "Legal persons entrepreneurial",
        "Limited liability company",
        "Active",
        "17-09-1992",
        "Slovak Republic",
        "Bratislava Region",
        "Bratislava V",
        "Bratislava-Petržalka",
        "SK529460_85101",
        "Einsteinova 24",
        17.10543,
        48.13415,
        "0J620009",
        "Other information technology and computer service activities",
        "7379",
        "Miscellaneous computer services",
        "1,000 - 1,999",
        "Positive",
        null,
        2020,
        "N. a.",
        ">= 500,000 Thous. Eur",
        "Positive",
        null,
        2019,
        "+421 232 244 109, +421 232 244 444, +421 232 244 250, +421 232 244 111",
        null,
        null,
        "info@eset.sk",
        null,
        null,
        "False",
        "False",
        "False",
        "ING. PETER PAŠKO",
        "18-05-1955",
        "Executive",
        "17-09-1992",
        "Slovak Republic",
        "ING. MIROSLAV TRNKA",
        "29-03-1961",
        "Executive",
        "17-09-1992",
        "Slovak Republic",
        "RUDOLF HRUBÝ",
        "14-04-1954",
        "Executive",
        "17-09-1992",
        "Slovak Republic",
      ],
      [
        "SK-35876832_30D2B337-552F-4030-9DC6-C4E9CA471C8D",
        "35876832",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Kia Motors Slovakia s.r.o.",
        "SK2021787801",
        "2021787801",
        "Legal persons entrepreneurial",
        "Limited liability company",
        "Active",
        "26-02-2004",
        "Slovak Republic",
        "Žilina Region",
        "Žilina",
        "Teplička nad Váhom",
        "SK518034_01301",
        "Sv. Jána Nepomuckého 1282/1",
        null,
        null,
        "0C290100",
        "Manufacture of motor vehicles",
        "3711",
        "Motor vehicle manufacturers",
        "3,000 - 3,999",
        "Stable",
        null,
        2020,
        "N. a.",
        ">= 500,000 Thous. Eur",
        "Stable",
        null,
        2019,
        "+421 415 150 111",
        null,
        null,
        "media@kia.sk, rvrabel@kia.sk",
        null,
        null,
        "False",
        "False",
        "False",
        "DONGEUN LEE",
        null,
        "Member of the Supervisory Board",
        "20-03-2019",
        "Republic of Korea",
        "WOOJEONG JOO",
        null,
        "Member of the Supervisory Board",
        "20-03-2019",
        "Republic of Korea",
        "HO SUNG SONG",
        null,
        "Member of the Supervisory Board",
        "17-07-2020",
        "Republic of Korea",
      ],
    ],
  },
  complete: {
    CZ: [
      [
        "CZ-25501143_48B57143-2D5B-49C4-AEFC-250B9505E9B0",
        "25501143",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Ptáček - velkoobchod, a.s.",
        "CZ25501143",
        null,
        "Legal persons entrepreneurial",
        "Joint stock company",
        "Active",
        "05-09-1997",
        "Czech Republic",
        "South Moravia Region",
        "Brno-město",
        "Brno-Kohoutovice",
        "CZ551147_62300",
        "U Velké ceny 413/4",
        16.53093,
        49.19749,
        "0G4601",
        "Wholesale on a fee or contract basis",
        "5199",
        "Misc nondurable goods wholesalers",
        "1,000 - 1,999",
        "Stable",
        2021,
        null,
        "1,500,000,000 Kč and more",
        "N. a.",
        "Stable",
        2021,
        null,
        "+420 220 800 100, +420 518 325 174",
        "+420 518 325 205",
        "www.ptacek.cz",
        "hodonin@ptacek.cz, sekretariat@ptacek.cz",
        null,
        "https://www.facebook.com/ptacek.velkoobchod",
        "False",
        "True",
        "True",
        "ING. ZDENĚK PTÁČEK",
        "24-06-1947",
        "Chairman of the Managing Board",
        "09-04-2021",
        "Czech Republic",
        "ING. JIŘÍ PTÁČEK",
        "27-03-1972",
        "Member of the Managing Board",
        "09-04-2021",
        "Czech Republic",
        "ING. ZDENĚK PTÁČEK",
        "04-08-1974",
        "Member of the Managing Board",
        "09-04-2021",
        "Czech Republic",
      ],
      [
        "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
        "26178541",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Lidl Česká republika v.o.s.",
        "CZ26178541",
        null,
        "Legal persons entrepreneurial",
        "Public commercial company",
        "Active",
        "05-06-2000",
        "Czech Republic",
        "Capital City Prague",
        "Prague",
        "Prague 13",
        "CZ539694_15800",
        "Nárožní 1359/11",
        14.33119,
        50.05276,
        "0G4701",
        "Retail sale in non-specialised stores",
        "5399",
        "General retailers",
        "10,000",
        "Stable",
        2021,
        null,
        "1,500,000,000 Kč and more",
        "N. a.",
        "Stable",
        2021,
        null,
        "+420 257 086 111, +420 800 115 435",
        "+420 257 011 700",
        "www.lidl.cz",
        "hotline@lidl.cz, lidl@lidl.cz",
        "https://www.lidl-shop.cz/?utm_source=lidl.cz&utm_medium=header&utm_campaign=e-shop",
        "https://www.facebook.com/lidlcesko/",
        "False",
        "False",
        "False",
        "LIDL HOLDING S.R.O.",
        null,
        "Statutory substitute (n/a)",
        "05-06-2000",
        "Czech Republic",
      ],
      [
        "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
        "46345965",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Česká zbrojovka a.s.",
        "CZ46345965",
        null,
        "Legal persons entrepreneurial",
        "Joint stock company",
        "Active",
        "27-04-1992",
        "Czech Republic",
        "Zlín Region",
        "Uherské Hradiště",
        "Uherský Brod",
        "CZ592731_68801",
        "Svat. Čecha 1283",
        17.63395,
        49.02589,
        "0C250400",
        "Manufacture of weapons and ammunition",
        "3483",
        "Misc ammunition mfrs (ex small arms)",
        "1,000 - 1,999",
        "Stable",
        2021,
        null,
        "1,500,000,000 Kč and more",
        "N. a.",
        "Stable",
        2021,
        null,
        "+420 572 653 911, +420 572 655 230",
        "+420 572 655 231",
        "www.cz-auto.com, www.czub.cz",
        "info@cz-auto.com, prodejna@czub.cz, info@czub.cz",
        null,
        "https://www.facebook.com/cz-auto-systems-as-1794631114143391/?view_public_for=1794631114143391",
        "False",
        "False",
        "True",
        "ING. JAN ZAJÍC",
        "05-01-1976",
        "Chairman of the Board of Directors",
        "15-01-2021",
        "Czech Republic",
        "ING. TOMÁŠ HAUERLAND MBA",
        "06-10-1970",
        "Vice-Chairman of the Board of Directors",
        "13-04-2019",
        "Czech Republic",
        "ING. TOMÁŠ STOSZEK",
        "08-02-1968",
        "Vice-Chairman of the Board of Directors",
        "15-01-2021",
        "Czech Republic",
      ],
      [
        "MargoId",
        "CompanyID/TaxId/VatId",
        "Status company",
        "Tag",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Tax code",
        "Legal forms group",
        "Legal form",
        "Status company",
        "Date of registration",
        "Country",
        "Region",
        "District",
        "City",
        "Zip code",
        "Address",
        "Longitude",
        "Latitude",
        "Prevailing activity (NACE)",
        "Description prevailing activity (NACE)",
        "Primary SIC",
        "Description primary SIC",
        "Range of employees count",
        "Employee trend",
        "Employees category year (CZ)",
        "Employees category year (SK)",
        "Turnover category (CZ)",
        "Turnover category (SK)",
        "Turnover trend",
        "Turnover category year (CZ)",
        "Turnover category year (SK)",
        "Phone number",
        "Fax",
        "Website URL",
        "Email",
        "Ecommerce",
        "Facebook",
        "State-owned company",
        "Export",
        "Import",
        "Supervisory board & statutory body - Name / business name (1)",
        "Supervisory board & statutory body - d. o. b. (1)",
        "Supervisory board & statutory body - Position (1)",
        "Supervisory board & statutory body - Valid From (1)",
        "Supervisory board & statutory body - Country (1)",
        "Supervisory board & statutory body - Name / business name (2)",
        "Supervisory board & statutory body - d. o. b. (2)",
        "Supervisory board & statutory body - Position (2)",
        "Supervisory board & statutory body - Valid From (2)",
        "Supervisory board & statutory body - Country (2)",
        "Supervisory board & statutory body - Name / business name (3)",
        "Supervisory board & statutory body - d. o. b. (3)",
        "Supervisory board & statutory body - Position (3)",
        "Supervisory board & statutory body - Valid From (3)",
        "Supervisory board & statutory body - Country (3)",
      ],
      [
        "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
        "31333532",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ESET, spol. s r.o.",
        "SK2020317068",
        "2020317068",
        "Legal persons entrepreneurial",
        "Limited liability company",
        "Active",
        "17-09-1992",
        "Slovak Republic",
        "Bratislava Region",
        "Bratislava V",
        "Bratislava-Petržalka",
        "SK529460_85101",
        "Einsteinova 24",
        17.10543,
        48.13415,
        "0J620009",
        "Other information technology and computer service activities",
        "7379",
        "Miscellaneous computer services",
        "1,000 - 1,999",
        "Positive",
        null,
        2020,
        "N. a.",
        ">= 500,000 Thous. Eur",
        "Positive",
        null,
        2019,
        "+421 232 244 109, +421 232 244 444, +421 232 244 250, +421 232 244 111",
        null,
        null,
        "info@eset.sk",
        null,
        null,
        "False",
        "False",
        "False",
        "ING. PETER PAŠKO",
        "18-05-1955",
        "Executive",
        "17-09-1992",
        "Slovak Republic",
        "ING. MIROSLAV TRNKA",
        "29-03-1961",
        "Executive",
        "17-09-1992",
        "Slovak Republic",
        "RUDOLF HRUBÝ",
        "14-04-1954",
        "Executive",
        "17-09-1992",
        "Slovak Republic",
      ],
      [
        "SK-35876832_30D2B337-552F-4030-9DC6-C4E9CA471C8D",
        "35876832",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Kia Motors Slovakia s.r.o.",
        "SK2021787801",
        "2021787801",
        "Legal persons entrepreneurial",
        "Limited liability company",
        "Active",
        "26-02-2004",
        "Slovak Republic",
        "Žilina Region",
        "Žilina",
        "Teplička nad Váhom",
        "SK518034_01301",
        "Sv. Jána Nepomuckého 1282/1",
        null,
        null,
        "0C290100",
        "Manufacture of motor vehicles",
        "3711",
        "Motor vehicle manufacturers",
        "3,000 - 3,999",
        "Stable",
        null,
        2020,
        "N. a.",
        ">= 500,000 Thous. Eur",
        "Stable",
        null,
        2019,
        "+421 415 150 111",
        null,
        null,
        "media@kia.sk, rvrabel@kia.sk",
        null,
        null,
        "False",
        "False",
        "False",
        "DONGEUN LEE",
        null,
        "Member of the Supervisory Board",
        "20-03-2019",
        "Republic of Korea",
        "WOOJEONG JOO",
        null,
        "Member of the Supervisory Board",
        "20-03-2019",
        "Republic of Korea",
        "HO SUNG SONG",
        null,
        "Member of the Supervisory Board",
        "17-07-2020",
        "Republic of Korea",
      ],
    ],
    SK: [
      [
        "CZ-25501143_48B57143-2D5B-49C4-AEFC-250B9505E9B0",
        "25501143",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Ptáček - velkoobchod, a.s.",
        "CZ25501143",
        null,
        "Legal persons entrepreneurial",
        "Joint stock company",
        "Active",
        "05-09-1997",
        "Czech Republic",
        "South Moravia Region",
        "Brno-město",
        "Brno-Kohoutovice",
        "CZ551147_62300",
        "U Velké ceny 413/4",
        16.53093,
        49.19749,
        "0G4601",
        "Wholesale on a fee or contract basis",
        "5199",
        "Misc nondurable goods wholesalers",
        "1,000 - 1,999",
        "Stable",
        2021,
        null,
        "1,500,000,000 Kč and more",
        "N. a.",
        "Stable",
        2021,
        null,
        "+420 220 800 100, +420 518 325 174",
        "+420 518 325 205",
        "www.ptacek.cz",
        "hodonin@ptacek.cz, sekretariat@ptacek.cz",
        null,
        "https://www.facebook.com/ptacek.velkoobchod",
        "False",
        "True",
        "True",
        "ING. ZDENĚK PTÁČEK",
        "24-06-1947",
        "Chairman of the Managing Board",
        "09-04-2021",
        "Czech Republic",
        "ING. JIŘÍ PTÁČEK",
        "27-03-1972",
        "Member of the Managing Board",
        "09-04-2021",
        "Czech Republic",
        "ING. ZDENĚK PTÁČEK",
        "04-08-1974",
        "Member of the Managing Board",
        "09-04-2021",
        "Czech Republic",
      ],
      [
        "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
        "26178541",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Lidl Česká republika v.o.s.",
        "CZ26178541",
        null,
        "Legal persons entrepreneurial",
        "Public commercial company",
        "Active",
        "05-06-2000",
        "Czech Republic",
        "Capital City Prague",
        "Prague",
        "Prague 13",
        "CZ539694_15800",
        "Nárožní 1359/11",
        14.33119,
        50.05276,
        "0G4701",
        "Retail sale in non-specialised stores",
        "5399",
        "General retailers",
        "10,000",
        "Stable",
        2021,
        null,
        "1,500,000,000 Kč and more",
        "N. a.",
        "Stable",
        2021,
        null,
        "+420 257 086 111, +420 800 115 435",
        "+420 257 011 700",
        "www.lidl.cz",
        "hotline@lidl.cz, lidl@lidl.cz",
        "https://www.lidl-shop.cz/?utm_source=lidl.cz&utm_medium=header&utm_campaign=e-shop",
        "https://www.facebook.com/lidlcesko/",
        "False",
        "False",
        "False",
        "LIDL HOLDING S.R.O.",
        null,
        "Statutory substitute (n/a)",
        "05-06-2000",
        "Czech Republic",
      ],
      [
        "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
        "46345965",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Česká zbrojovka a.s.",
        "CZ46345965",
        null,
        "Legal persons entrepreneurial",
        "Joint stock company",
        "Active",
        "27-04-1992",
        "Czech Republic",
        "Zlín Region",
        "Uherské Hradiště",
        "Uherský Brod",
        "CZ592731_68801",
        "Svat. Čecha 1283",
        17.63395,
        49.02589,
        "0C250400",
        "Manufacture of weapons and ammunition",
        "3483",
        "Misc ammunition mfrs (ex small arms)",
        "1,000 - 1,999",
        "Stable",
        2021,
        null,
        "1,500,000,000 Kč and more",
        "N. a.",
        "Stable",
        2021,
        null,
        "+420 572 653 911, +420 572 655 230",
        "+420 572 655 231",
        "www.cz-auto.com, www.czub.cz",
        "info@cz-auto.com, prodejna@czub.cz, info@czub.cz",
        null,
        "https://www.facebook.com/cz-auto-systems-as-1794631114143391/?view_public_for=1794631114143391",
        "False",
        "False",
        "True",
        "ING. JAN ZAJÍC",
        "05-01-1976",
        "Chairman of the Board of Directors",
        "15-01-2021",
        "Czech Republic",
        "ING. TOMÁŠ HAUERLAND MBA",
        "06-10-1970",
        "Vice-Chairman of the Board of Directors",
        "13-04-2019",
        "Czech Republic",
        "ING. TOMÁŠ STOSZEK",
        "08-02-1968",
        "Vice-Chairman of the Board of Directors",
        "15-01-2021",
        "Czech Republic",
      ],
      [
        "MargoId",
        "CompanyID/TaxId/VatId",
        "Status company",
        "Tag",
        "Amount",
        "Area Manager",
        "Sales",
        "Product",
        "Company Name",
        "Vat code",
        "Tax code",
        "Legal forms group",
        "Legal form",
        "Status company",
        "Date of registration",
        "Country",
        "Region",
        "District",
        "City",
        "Zip code",
        "Address",
        "Longitude",
        "Latitude",
        "Prevailing activity (NACE)",
        "Description prevailing activity (NACE)",
        "Primary SIC",
        "Description primary SIC",
        "Range of employees count",
        "Employee trend",
        "Employees category year (CZ)",
        "Employees category year (SK)",
        "Turnover category (CZ)",
        "Turnover category (SK)",
        "Turnover trend",
        "Turnover category year (CZ)",
        "Turnover category year (SK)",
        "Phone number",
        "Fax",
        "Website URL",
        "Email",
        "Ecommerce",
        "Facebook",
        "State-owned company",
        "Export",
        "Import",
        "Supervisory board & statutory body - Name / business name (1)",
        "Supervisory board & statutory body - d. o. b. (1)",
        "Supervisory board & statutory body - Position (1)",
        "Supervisory board & statutory body - Valid From (1)",
        "Supervisory board & statutory body - Country (1)",
        "Supervisory board & statutory body - Name / business name (2)",
        "Supervisory board & statutory body - d. o. b. (2)",
        "Supervisory board & statutory body - Position (2)",
        "Supervisory board & statutory body - Valid From (2)",
        "Supervisory board & statutory body - Country (2)",
        "Supervisory board & statutory body - Name / business name (3)",
        "Supervisory board & statutory body - d. o. b. (3)",
        "Supervisory board & statutory body - Position (3)",
        "Supervisory board & statutory body - Valid From (3)",
        "Supervisory board & statutory body - Country (3)",
      ],
      [
        "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
        "31333532",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "ESET, spol. s r.o.",
        "SK2020317068",
        "2020317068",
        "Legal persons entrepreneurial",
        "Limited liability company",
        "Active",
        "17-09-1992",
        "Slovak Republic",
        "Bratislava Region",
        "Bratislava V",
        "Bratislava-Petržalka",
        "SK529460_85101",
        "Einsteinova 24",
        17.10543,
        48.13415,
        "0J620009",
        "Other information technology and computer service activities",
        "7379",
        "Miscellaneous computer services",
        "1,000 - 1,999",
        "Positive",
        null,
        2020,
        "N. a.",
        ">= 500,000 Thous. Eur",
        "Positive",
        null,
        2019,
        "+421 232 244 109, +421 232 244 444, +421 232 244 250, +421 232 244 111",
        null,
        null,
        "info@eset.sk",
        null,
        null,
        "False",
        "False",
        "False",
        "ING. PETER PAŠKO",
        "18-05-1955",
        "Executive",
        "17-09-1992",
        "Slovak Republic",
        "ING. MIROSLAV TRNKA",
        "29-03-1961",
        "Executive",
        "17-09-1992",
        "Slovak Republic",
        "RUDOLF HRUBÝ",
        "14-04-1954",
        "Executive",
        "17-09-1992",
        "Slovak Republic",
      ],
      [
        "SK-35876832_30D2B337-552F-4030-9DC6-C4E9CA471C8D",
        "35876832",
        "Prospect $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "Kia Motors Slovakia s.r.o.",
        "SK2021787801",
        "2021787801",
        "Legal persons entrepreneurial",
        "Limited liability company",
        "Active",
        "26-02-2004",
        "Slovak Republic",
        "Žilina Region",
        "Žilina",
        "Teplička nad Váhom",
        "SK518034_01301",
        "Sv. Jána Nepomuckého 1282/1",
        null,
        null,
        "0C290100",
        "Manufacture of motor vehicles",
        "3711",
        "Motor vehicle manufacturers",
        "3,000 - 3,999",
        "Stable",
        null,
        2020,
        "N. a.",
        ">= 500,000 Thous. Eur",
        "Stable",
        null,
        2019,
        "+421 415 150 111",
        null,
        null,
        "media@kia.sk, rvrabel@kia.sk",
        null,
        null,
        "False",
        "False",
        "False",
        "DONGEUN LEE",
        null,
        "Member of the Supervisory Board",
        "20-03-2019",
        "Republic of Korea",
        "WOOJEONG JOO",
        null,
        "Member of the Supervisory Board",
        "20-03-2019",
        "Republic of Korea",
        "HO SUNG SONG",
        null,
        "Member of the Supervisory Board",
        "17-07-2020",
        "Republic of Korea",
      ],
    ],
  },
  custom: {
    CZ: [
      [
        "CZ-25501143_48B57143-2D5B-49C4-AEFC-250B9505E9B0",
        "25501143",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "CZ551147_62300",
        "CZ551147_62300",
        "1 000 - 1 999",
        "1 500 000 000 Kč a více",
        "True",
        "True",
      ],
      [
        "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
        "26178541",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "CZ539694_15800",
        "CZ539694_15800",
        "10 000",
        "1 500 000 000 Kč a více",
        "False",
        "False",
      ],
      [
        "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
        "46345965",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "CZ592731_68801",
        "CZ592731_68801",
        "1 000 - 1 999",
        "1 500 000 000 Kč a více",
        "False",
        "True",
      ],
      [
        "MargoId",
        "IČ",
        "Status company",
        "Tag",
        "Množství",
        "Area Manažer",
        "Obchodník",
        "Produkt",
        "PSČ",
        "PSČ",
        "Kategorie počtu zaměstnanců",
        "Kategorie obratu (CZ)",
        "Export",
        "Import",
      ],
      [
        "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
        "31333532",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "SK529460_85101",
        "SK529460_85101",
        "1 000 - 1 999",
        "Nedostupné",
        "False",
        "False",
      ],
      [
        "SK-35876832_30D2B337-552F-4030-9DC6-C4E9CA471C8D",
        "35876832",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "SK518034_01301",
        "SK518034_01301",
        "3 000 - 3 999",
        "Nedostupné",
        "False",
        "False",
      ],
    ],
    SK: [
      [
        "CZ-25501143_48B57143-2D5B-49C4-AEFC-250B9505E9B0",
        "25501143",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "CZ551147_62300",
        "CZ551147_62300",
        "1 000 - 1 999",
        "Nedost.",
        "True",
        "True",
      ],
      [
        "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
        "26178541",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "CZ539694_15800",
        "CZ539694_15800",
        "10 000",
        "Nedost.",
        "False",
        "False",
      ],
      [
        "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
        "46345965",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "CZ592731_68801",
        "CZ592731_68801",
        "1 000 - 1 999",
        "Nedost.",
        "False",
        "True",
      ],
      [
        "MargoId",
        "IČO",
        "Status company",
        "Tag",
        "Množstvo",
        "Oblastný manažér",
        "Obchodník",
        "Produkt",
        "PSČ",
        "PSČ",
        "Kategória počtu zamestnancov",
        "Kategória obratu (SK)",
        "Export",
        "Import",
      ],
      [
        "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
        "31333532",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "SK529460_85101",
        "SK529460_85101",
        "1 000 - 1 999",
        ">= 500 000 tis. Eur",
        "False",
        "False",
      ],
      [
        "SK-35876832_30D2B337-552F-4030-9DC6-C4E9CA471C8D",
        "35876832",
        "Prospekt $(Prospect)$",
        null,
        null,
        null,
        null,
        null,
        "SK518034_01301",
        "SK518034_01301",
        "3 000 - 3 999",
        ">= 500 000 tis. Eur",
        "False",
        "False",
      ],
    ],
  },
  portfolioBeforeUpdate: [[]],
  groupActionsBase: [
    [
      "CZ-26178541_F0741B80-4144-4F92-A387-6468615ED266",
      "26178541",
      "Prospect $(Prospect)$",
    ],
    [
      "CZ-46345965_4F945183-B183-425B-A2B1-59DC02D4FF42",
      "46345965",
      "Prospect $(Prospect)$",
    ],
    [
      "MargoId",
      "CompanyID/TaxId/VatId",
      "Status company",
      "Tag",
      "Amount",
      "Area Manager",
      "Sales",
      "Product",
    ],
    [
      "SK-31333532_3C3EEF8C-DA74-440E-9A32-10AA30C22876",
      "31333532",
      "Prospect $(Prospect)$",
    ],
  ],
};
export default czIntPortfolioSchemas;
